### PR TITLE
Generate sourcemaps with relative paths 

### LINKED ISSUE #17046: Generated Source Maps using absolute paths
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] serve
- [x] build
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] test
- [ ] lint
- [ ] xi18n
- [ ] new
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't think so.

### Description

When building an Angular application that imports a local library, the source maps for files outside of the apps' folder contain absolute paths instead of relative ones. 

This happens because the context for the default Webpack config generated by the CLI internally is [set to `projectRoot`](https://github.com/angular/angular-cli/blob/c9a5f3ced6689feac9cc0ccbd15b0fed6f454d6e/packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts#L497). Webpack shortens the paths by looking into the [current and the parent directory](https://github.com/webpack/webpack/blob/11e94dd2d0a8d8baae75e715ff8a69f27a9e3014/lib/RequestShortener.js#L63), which is not enough for the provided setup.

I propose to use either the TSConfig `baseUrl` as the context for the Webpack config (would make the most sense in my opinion because the paths aliases are relative to this path), or the workspaces `root` property.

## 🔬 Minimal Reproduction
Create a new project containing an application and a library. Import the library in the application through TS path aliases and build it with source maps enabled. The source maps will be using absolute paths.

A simple repo can be found here: https://github.com/FERNman/angular-source-maps
Just run `ng build playground` and go to any of the generated source maps in the `dist` folder. The path should be an absolute path.

## Workaround
For anybody else stumbling across this issue, an easy workaround until this gets fixed is to change the `root` property of the app in question in the `angular.json` to the repositories' root.

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 12.10.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
... service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              7.3.9
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

### PR DESCRIPTION
**Pull request by alan-agius4**
**fix(@angular-devkit/buid-angular): generate sourcemaps with relative paths in monorepo**
    
With this change we fix the issue that when having a monorepo style workspace, sourcemaps sources references absolute paths.
    
Closes #17046

**fix(@angular-devkit/build-angular): improve debugging experience**

With this change we improve the debugging experience with 2 things.

1. Cleaner Karma stack traces in the terminal
Before
```
Chrome 84.0.4147.105 (Mac OS 10.15.5) AppComponent should have as title 'foo' FAILED
        Error: Expected 'foo' to equal 'fox'.
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/projects/foo/src/app/app.component.spec.ts:22:23)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-testing.js:292:1)
Chrome 84.0.4147.105 (Mac OS 10.15.5): Executed 3 of 3 (1 FAILED) (0 secs / 0.214 secs)
Chrome 84.0.4147.105 (Mac OS 10.15.5) AppComponent should have as title 'foo' FAILED
        Error: Expected 'foo' to equal 'fox'.
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9876/_karma_webpack_/webpack:/projects/foo/src/app/app.component.spec.ts:22:23)
            at ZoneDelegate.invoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (http://localhost:9876/_karma_webpack_/webpack:/node_modules/zone.js/dist/zChrome 84.0.4147.105 (Mac OS 10.15.5): Executed 3 of 3 (1 FAILED) (0.225 secs / 0.214 secs)
```

After
```
Chrome 84.0.4147.105 (Mac OS 10.15.5) AppComponent should have as title 'foo' FAILED
        Error: Expected 'foo' to equal 'fox'.
            at <Jasmine>
            at UserContext.<anonymous> (projects/foo/src/app/app.component.spec.ts:22:23)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:364:1)
            at ProxyZoneSpec.push../node_modules/zone.js/dist/zone-testing.js.ProxyZoneSpec.onInvoke (node_modules/zone.js/dist/zone-testing.js:292:1)
Chrome 84.0.4147.105 (Mac OS 10.15.5): Executed 2 of 3 (1 FAILED) (0 secs / 0.225 secs)
Chrome 84.0.4147.105 (Mac OS 10.15.5) AppComponent should have as title 'foo' FAILED
        Error: Expected 'foo' to equal 'fox'.
            at <Jasmine>
            at UserContext.<anonymous> (projects/foo/src/app/app.component.spec.ts:22:23)
            at ZoneDelegate.invoke (node_modules/zone.js/dist/zone-evergreen.js:364:1)
Chrome 84.0.4147.105 (Mac OS 10.15.5): Executed 3 of 3 (1 FAILED) (0.281 secs / 0.237 secs)
```

2. Reduce VS Code configuration
Before
```
{
  "name": "ng test",
  "type": "chrome",
  "request": "launch",
  "url": "http://localhost:9876/debug.html",
  "webRoot": "${workspaceFolder}",
  "sourceMaps": true,
  "sourceMapPathOverrides": {
    "webpack:/*": "${webRoot}/*",
    "/./*": "${webRoot}/*",
    "/src/*": "${webRoot}/*",
    "/*": "*",
    "/./~/*": "${webRoot}/node_modules/*"
  }
},
```

After
```
{
  "name": "ng test",
  "type": "chrome",
  "request": "launch",
  "url": "http://localhost:9876/debug.html",
  "webRoot": "${workspaceFolder}"
},
```

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts [hunk 1]
```diff
@@ -24,6 +24,7 @@ import {
   compilation,
   debug,
 } from 'webpack';
+import webpack = require('webpack');
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts:27]: This appears unused.

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts]: Yup, removed
