### PR TITLE
fix(deploy): gh-pages deploy fail after repo create

### LINKED ISSUE #3385: github-pages:deploy failing after first creating repo
The function `cleanGhPagesBranch()` is failing due to my prior sloppiness. It is running `git rm -r` with no file arguments, because there are none immediately after creating.

For that I must apologize. The fix is coming right up.

### PR DESCRIPTION
**Pull request by taylorjb**
Catches the error as they are no files to clean up on repo create.

Closes #3385

### CODE REVIEW

File: packages/angular-cli/commands/github-pages-deploy.ts [hunk 1]
```diff
@@ -216,7 +216,8 @@ const githubPagesDeployCommand = Command.extend({
               files = files.concat(`"${f}" `);
             }
           });
-          return execPromise(`git rm -r ${files}`);
+          return execPromise(`git rm -r ${files}`)
+            .catch(() => Promise.resolve());
```
Comment (hansl) [inline packages/angular-cli/commands/github-pages-deploy.ts]: Could you please replace this line with:

```typescript
.catch(() => {
  // Ignoring errors when trying to erase files.
});
```

**Comment by hansl** [comment]
LGTM. Cheers!
