### PR TITLE
fix(@angular-devkit/build-angular): correctly handle glob negation in proxy config when using vite

### LINKED ISSUE #26970: Angular CLI messes up proxy.conf.js regex proxy -settings passed to Vite when using esbuild
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Angular CLI messes up proxy.conf.js regex proxy -settings passed to Vite when using esbuild. 

`^\\/(?!hui).*` becomes `\^\/(?!hui)\.[^/]*?\/?`

### Minimal Reproduction

Vite doesn't seem to support glob patterns in proxy.conf.js. It supports regular expressions which would do fine but Angular CLI proxy configuration normalization messes up regular expressions. Normalization is done here:

https://github.com/angular/angular-cli/blob/main/packages/angular_devkit/build_angular/src/utils/load-proxy-config.ts

This step perhaps mistakenly treats regular expressions as globs:

```
  // TODO: Consider upstreaming glob support
  for (const key of Object.keys(normalizedProxy)) {
    if (isDynamicPattern(key)) {
      const { output } = parseGlob(key);
      normalizedProxy[`^${output}$`] = normalizedProxy[key];
      delete normalizedProxy[key];
    }
  }
```

Previously with @angular-devkit/build-angular:browser we had:

```
module.exports = [
  {
    context: "/internal-api",
    target: "http://localhost:8082",
    logLevel: "debug",
    secure: false
  },
  {
    context: "!/hui/**",
    target: "http://localhost:8080",
    logLevel: "debug",
    secure: false
  }
]
```

With @angular-devkit/build-angular:browser-esbuild something like this should be equivalent if the configuration would go to Vite without changes:

```
module.exports = {
  "/internal-api": {
    target: "http://localhost:8082",
    secure: false,
  },
  "^\\/(?!hui).*": {
    target: "http://localhost:8080",
    secure: false
  },
  "^\\/$": {
    target: "http://localhost:8080",
    secure: false,
  }
};
```

### Exception or Error

_No response_

### Your Environment

```text
Angular CLI: 17.1.0
Node: 20.11.0
Package Manager: npm 10.2.4
OS: win32 x64

Angular: 17.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1701.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@schematics/angular             17.1.0
ng-packagr                      17.1.1
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.3
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit fixes an issue were negated globs in proxy config were not process correctly when using vite.

Closes #26970

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/utils/load-proxy-config.ts [hunk 1]
```diff
@@ -129,8 +129,9 @@ function normalizeProxyConfiguration(
   // TODO: Consider upstreaming glob support
   for (const key of Object.keys(normalizedProxy)) {
     if (isDynamicPattern(key)) {
-      const { output } = parseGlob(key);
-      normalizedProxy[`^${output}$`] = normalizedProxy[key];
+      // Remove leading and trailing '/'.
+      const pattern = makeRegExpFromGlob(key).toString().slice(1, -1);
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/utils/load-proxy-config.ts:133]:
```suggestion
      const pattern = makeRegExpFromGlob(key).source;
```

File: packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts [hunk 2]
```diff
@@ -232,18 +212,39 @@ describeServeBuilder(executeDevServer, DEV_SERVER_BUILDER_INFO, (harness, setupT
         }),
       );
     });
+
+    it('supports negatation of globs', async () => {
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/builders/dev-server/tests/options/proxy-config_spec.ts:216]:
```suggestion
    it('supports negation of globs', async () => {
```

**Review by clydin — APPROVED** [review]
