### PR TITLE
fix(@schematics/angular): update default app component welcome message

### LINKED ISSUE #32176: Inconsistent default templates in for app.ts for inline template vs external template file
### Command

new

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When generating a new project, an App component is created with inconsistent templates, depending on whether you use internal or external templates.

When you use `ng new -t` (inline template), the default `h1` contains `Welcome to {{ title() }}!`:
- https://github.com/angular/angular-cli/blob/aef7d65438306911b59d3cb16c74a2bd0567bd77/packages/schematics/angular/application/files/standalone-files/src/app/app__suffix__.ts.template#L8
- https://github.com/angular/angular-cli/blob/aef7d65438306911b59d3cb16c74a2bd0567bd77/packages/schematics/angular/application/files/module-files/src/app/app__suffix__.ts.template#L6

When you use `ng new` (external template file), the default `h1` contains  `Hello, {{ title() }}`:
- https://github.com/angular/angular-cli/blob/aef7d65438306911b59d3cb16c74a2bd0567bd77/packages/schematics/angular/application/files/common-files/src/app/app__suffix__.html.template#L233

When I add Cypress using `ng e2e`, it will create this default assertion: `cy.contains('app is running') `. This assertion fails when you use inline templates.

The inline and external default templates should be consistent in my opinion, so external tooling can assert on it. 

### Minimal Reproduction

When you use `ng new -t` (inline template), the default `h1` contains `Welcome to {{ title() }}!`:
- https://github.com/angular/angular-cli/blob/aef7d65438306911b59d3cb16c74a2bd0567bd77/packages/schematics/angular/application/files/standalone-files/src/app/app__suffix__.ts.template#L8
- https://github.com/angular/angular-cli/blob/aef7d65438306911b59d3cb16c74a2bd0567bd77/packages/schematics/angular/application/files/module-files/src/app/app__suffix__.ts.template#L6

When you use `ng new` (external template file), the default `h1` contains  `Hello, {{ title() }}`:
- https://github.com/angular/angular-cli/blob/aef7d65438306911b59d3cb16c74a2bd0567bd77/packages/schematics/angular/application/files/common-files/src/app/app__suffix__.html.template#L233

### Exception or Error

```text

```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI       : 21.0.4
Node.js           : 22.21.1
Package Manager   : npm 10.9.4
Operating System  : win32 x64
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
Aligns the inline welcome message with the external template for consistency.

Closes #32176

### CODE REVIEW

File: packages/schematics/angular/application/files/module-files/src/app/app__suffix__.ts.template [hunk 1]
```diff
@@ -3,7 +3,7 @@ import { Component, signal } from '@angular/core';
 @Component({
   selector: '<%= selector %>',<% if(inlineTemplate) { %>
   template: `
-    <h1>Welcome to {{ title() }}!</h1>
+    <h1>Hello, {{ title() }}</h1>
```
Comment (mikem-of) [inline packages/schematics/angular/application/files/module-files/src/app/app__suffix__.ts.template:7]: Please also add: `<p>Congratulations! Your app is running. 🎉</p>`

File: packages/schematics/angular/application/files/standalone-files/src/app/app__suffix__.ts.template [hunk 2]
```diff
@@ -5,7 +5,7 @@ import { RouterOutlet } from '@angular/router';<% } %>
   selector: '<%= selector %>',
   imports: [<% if(routing) { %>RouterOutlet<% } %>],<% if(inlineTemplate) { %>
   template: `
-    <h1>Welcome to {{ title() }}!</h1>
+    <h1>Hello, {{ title() }}</h1>
```
Comment (mikem-of) [inline packages/schematics/angular/application/files/standalone-files/src/app/app__suffix__.ts.template:9]: Please also add: `<p>Congratulations! Your app is running. 🎉</p>`

**Review by clydin — APPROVED** [review]

**Comment by alan-agius4** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 424a465df7fa131803de4184f787ad9573a65090
- 21.0.x: c37dccb093f7b48027fac27bd78abe7f3e3e15ad
