### PR TITLE
fix(@angular-devkit/build-angular): ensure vitest code coverage handles virtual files correctly

### LINKED ISSUE #31601: Vitest code coverage is always 0
### Command

test

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

21.0.0-next.8

### Description

Since the internal migration to vitest v4, code coverage with Vitest is always 0.

### Minimal Reproduction

```
npx @angular/cli@21.0.0-next.9 new vitest-coverage --defaults --no-routing
cd vitest-coverage
npm i --save-dev @vitest/coverage-v8
```

Update angular.json:

```json
"test": {
  "builder": "@angular/build:unit-test",
  "options": {
    "coverage": true,
    "coverageInclude": ["src/**/*.ts", "src/**/*.html"]
  }
}
```

Launch the tests: `ng test --no-watch`

Results:

```
 % Coverage report from v8
----------------|---------|----------|---------|---------|-------------------
File            | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------------|---------|----------|---------|---------|-------------------
All files       |       0 |      100 |       0 |       0 |                   
 src            |       0 |      100 |       0 |       0 |                   
  main.ts       |       0 |      100 |       0 |       0 | 5-6               
 src/app        |       0 |      100 |     100 |       0 |                   
  app.config.ts |       0 |      100 |     100 |       0 | 3                 
  app.ts        |       0 |      100 |     100 |       0 | 9-10              
----------------|---------|----------|---------|---------|-------------------
```

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI       : 21.0.0-next.9
Angular           : 21.0.0-next.9
Node.js           : 22.18.0
Package Manager   : npm 10.9.0
Operating System  : darwin arm64

┌───────────────────────────┬───────────────────┬───────────────────┐
│ Package                   │ Installed Version │ Requested Version │
├───────────────────────────┼───────────────────┼───────────────────┤
│ @angular/build            │ 21.0.0-next.9     │ ^21.0.0-next.9    │
│ @angular/cli              │ 21.0.0-next.9     │ ^21.0.0-next.9    │
│ @angular/common           │ 21.0.0-next.9     │ ^21.0.0-next.0    │
│ @angular/compiler         │ 21.0.0-next.9     │ ^21.0.0-next.0    │
│ @angular/compiler-cli     │ 21.0.0-next.9     │ ^21.0.0-next.0    │
│ @angular/core             │ 21.0.0-next.9     │ ^21.0.0-next.0    │
│ @angular/forms            │ 21.0.0-next.9     │ ^21.0.0-next.0    │
│ @angular/platform-browser │ 21.0.0-next.9     │ ^21.0.0-next.0    │
│ @angular/router           │ 21.0.0-next.9     │ ^21.0.0-next.0    │
│ rxjs                      │ 7.8.2             │ ~7.8.0            │
│ typescript                │ 5.9.3             │ ~5.9.2            │
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by clydin**
Vitest's default coverage provider checks for the physical existence of files to determine inclusion in the coverage report. This behavior excludes in-memory files generated by the build process from the final report. This change patches the `isIncluded` method of Vitest's `BaseCoverageProvider` to correctly account for these virtual files, ensuring they are included in the coverage analysis.

Additionally, bundler-generated helper code chunks without any original source code can have empty sourcemaps. Vitest includes files with such sourcemaps in the coverage report, which is incorrect. This change adds a virtual source to these sourcemaps to prevent them from being included in the final coverage output.

Closes #31601

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

File: packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts [hunk 1]
```diff
@@ -154,6 +157,21 @@ export class VitestExecutor implements TestExecutor {
     }
     const { startVitest } = vitestNodeModule;
 
+    // Augment BaseCoverageProvider to include logic to support the built virtual files.
+    // Temporary workaround to avoid the direct filesystem checks in the base provider that
+    // were introduced in v4. Also ensures that all built virtual files are available.
+    const builtVirtualFiles = this.buildResultFiles;
+    vitestCoverageModule.BaseCoverageProvider.prototype.isIncluded = function (filename) {
```
Comment (AriPerkkio) [inline packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts:164]: Patching private APIs instead of filing bug report on upstream is not recommended, ever.

I'm not sure why exactly Angular requires such hacky patch but it might as well be real bug on Vitest.

Comment (clydin) [reply packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts:164]: Understood.  It's temporary and we will be filing a bug and investigating further.  This is intended to unblock downstream integration testing and allows us to test for potential breakage across a wider array of user projects in the interim.  Additionally, in this case `isIncluded` is a public method on a public class that if it were changed upstream would cause breakage for all concrete providers so could not effectively be changed outside a major version.

**Comment by clydin** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 2c846fbfd81ea92ffa85c920c8953e0213c6c5af
- 21.0.x: 6e395fc0c4505dd32b3237ea116e8db6bde25758

File: packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts (hunk 1 above)
Comment (yjaaidi) [reply packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts:164]: Btw, @clydin, is there any design doc or anything that highlights the pros and cons of separate build + virtual files vs. a vite transform plugin?

I am myself passionate about symmetry and would love to have everything built and bundled the same way but I feel that this is also breaking some of Vitest assumptions.
