### PR TITLE
fix(@ngtools/webpack): elide imports for `implements` keywords

### LINKED ISSUE #16907: Webpack complain about d.ts
# 🐞 Bug report

### Command (mark with an `x`)

ng build --prod

- [ ] new
- [ x ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ x ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.14

### Description

I have updated my project to 9.0.0 and this happend.

I have component with type imports from `'../@types.d.ts'`, but when run build, CLI throw an error that can't resolve `'../@types'`(+ `Field 'browser' doesn't contain a valid alias configuration`). If I fixed it like `'../@types.d'` it passes, but throw another error which  `'../@types.d.ts' is missing from typescript compilation` and I should include it's path.

But things doesn't workout even though I add path to both `tsconfig.json` and `tsconfig.app.json`.
Is it because of the ivy typescript and webpack configuration?

## 🔥 Exception or Error
<pre><code>

Module not found: Error: Can't resolve '../@types' in '{{ project root }}\src\app\account\sign-up'
resolve '../@types' in '{{ project root }}\src\app\account\sign-up'
  using description file: {{ project root }}\package.json (relative path: ./src/app/account/sign-up)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: {{ project root }}\package.json (relative path: ./src/app/account/@types)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        {{ project root }}\src\app\account\@types doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        {{ project root }}\src\app\account\@types.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        {{ project root }}\src\app\account\@types.tsx doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        {{ project root }}\src\app\account\@types.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        {{ project root }}\src\app\account\@types.js doesn't exist
      as directory
        {{ project root }}\src\app\account\@types doesn't exist
[{{ project root }}\src\app\account\@types]
[{{ project root }}\src\app\account\@types.ts]
[{{ project root }}\src\app\account\@types.tsx]
[{{ project root }}\src\app\account\@types.mjs]
[{{ project root }}\src\app\account\@types.js]
 @ ./src/app/account/sign-up/sign-up.component.ts 7:0-50
 @ ./src/app/account/account-routing.module.ts
 @ ./src/app/account/account.module.ts
 @ ./src/app/app-routing.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts

</code></pre>

## 🌍 Your Environment
<pre><code>

@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cdk                      8.2.3
@angular/cli                      9.0.1
@angular/material                 8.2.3
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by alan-agius4**
Running the `remove-ivy-jit-support-calls` and `remove_decorators` transformers causes the following TS bug https://github.com/microsoft/TypeScript/issues/17552 which is why the `elide-imports` transformer exists in the first place.

However, when having a syntax like the below;
```ts
import { AccountComponentChild } from '../@types';
export class SignUpComponent implements AccountComponentChild{}
```

The `implements` parts of the class is called a `HeritageClause` with child statements of `ExpressionWithTypeArguments` also the same is for `abstract`. With this change we check the token of the `HeritageClause` and if it's an `ImplementsKeyword` we elide the import.

Closes #16907
Ref TOOL-1324

### CODE REVIEW

**Comment by filipesilva** [comment]
Asking @clydin for review instead since he's more familiar with this transformer and I am mostly out of office.

File: packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls_spec.ts [hunk 1]
```diff
@@ -164,5 +164,53 @@ describe('@ngtools/webpack transformers', () => {
       expect(tags.oneLine`${result}`).toEqual(tags.oneLine`${output}`);
     });
 
+    it(`should strip unused imports for 'ExpressionWithTypeArguments' when parent token is 'ImplementsKeyword`, () => {
```
Comment (clydin) [inline packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls_spec.ts]: Can a general elide imports test be added as well (or instead if preferred) since this can technically happen any time the import eliding transformer is run regardless of Ivy usage?

Comment (alan-agius4) [reply packages/ngtools/webpack/src/transformers/remove-ivy-jit-support-calls_spec.ts]: Yeah it can. I’ll add a test tomorrow.
