### PR TITLE
fix(@angular/cli): handle cases were having completion enabled but running in an older CLI workspace

### LINKED ISSUE #23518: 14.0.5 not installed globaly
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [x] version
- [ ] doc

### Is this a regression?

Yes, the previous version installed correctly

### Description
I'm not in any workspace 

1.  npm uninstall -g @angular/cli
2.  npm cache verify
3.  npm install -g @angular/cli
4. ng version

```
❯ ng version
Your global Angular CLI version (14.0.5) is greater than your local version (13.3.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.3.7
Node: 16.15.1
Package Manager: npm 8.5.1
OS: win32 x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1303.7
@angular-devkit/core         13.3.7
@angular-devkit/schematics   13.3.7
@schematics/angular          13.3.7
```
 
5. ng config -g cli.warnings.versionMismatch false
```
Your global Angular CLI version (14.0.5) is greater than your local version (13.3.7). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Schema validation failed with the following errors:
  Data path "/cli" must NOT have additional properties(completion).
```
6. which ng

```
/c/Users/tomaz/AppData/Roaming/npm/ng
```
7.  in C:\Users\tomaz\AppData\Roaming\npm\node_modules\@angular\cli\package.json I see
```
"name": "@angular/cli",
  "version": "14.0.5",
  "description": "CLI tool for Angular",
  "main": "lib/cli/index.js",
  "bin": {
    "ng": "./bin/ng.js"
  },
```
8.   ng completion
```
The specified command ("completion") is invalid. For a list of available options,
run "ng help".

Did you mean "analytics"?
```

### PR DESCRIPTION
**Pull request by alan-agius4**
Previously when having completion enabled and the current workspaces has an older version of the Angular CLI installed in the terminal the below errors is show. This is because the older versions of the CLI do not implement this command. Now we exit gracefully.

```
The specified command ("completion") is invalid. For a list of available options,
run "ng help".

Did you mean "analytics"?
```

Closes #23518

### CODE REVIEW

File: packages/angular/cli/lib/init.ts [hunk 1]
```diff
@@ -79,14 +79,14 @@ let forceExit = false;
...
+    if (isGlobalGreater) {
+      // If using the update/completion command and the global version is greater. Use the global version.
+      // - update: This allows improvements in update to be used in older versions that do not have bootstrapping.
+      // - completion: This allows improvements to the completion command and handles the case where older local
+      //   versions of the CLI don't have this command.
       if (
-        rawCommandName === 'update' &&
-        cli.VERSION &&
-        cli.VERSION.major - globalVersion.major <= 1
+        rawCommandName === 'completion' ||
```
Comment (clydin) [inline packages/angular/cli/lib/init.ts:88]: I think we should consider limiting this to versions that don't have the command (< 14) so that differences in future versions don't lead to discrepancies in completion behavior.

**Review by clydin — APPROVED** [review]
