### PR TITLE
fix(@angular/build): allow non-prefixed requests when using SSR and base href

### LINKED ISSUE #31896: Angular SSR: Express routes are only prefixed in development with baseHref set
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When setting the `baseHref`, all dev server requests are required to be prefixed, even if I have routes in my `server.ts` that do not need the baseHref, such as health check endpoints.

Then when building the application the endpoint works without the baseHref, causing a mismatch of behavior between dev and build.

### Minimal Reproduction

https://github.com/brandonroberts/angular-ssr-base-href

1. Clone the repo
2. Run npm install
3. Run npm start
4. Visit `http://localhost:4200/ping`
5. Note the error message that the URL should be `http://localhost:4200/custom/ping`
6. Stop the dev server
7. Run npm run build
8. Run `npm run serve:ssr:angular-ssr-base-href`
9. Visit `http://localhost:4000/ping`
10. Note the route displays correctly

### Exception or Error

```text

```

### Your Environment

```text
Angular: 20.3.12
... common, compiler, compiler-cli, core, forms
... platform-browser, platform-server, router

Package                      Version
------------------------------------
@angular-devkit/architect    0.2003.10
@angular-devkit/core         20.3.10
@angular-devkit/schematics   20.3.10
@angular/build               20.3.10
@angular/cli                 20.3.10
@angular/ssr                 20.3.10
@schematics/angular          20.3.10
rxjs                         7.8.2
typescript                   5.9.3
zone.js                      0.15.1
```

### Anything else relevant?

Tested with Angular v21 also

### PR DESCRIPTION
**Pull request by alan-agius4**
When using SSR with a configured baseHref, the Vite dev server's default base middleware would intercept and reject requests that did not start with the base path. This created a mismatch with production behavior, where such requests (e.g., health check endpoints or custom routes defined in server.ts) could be handled correctly without the base prefix.

This change patches the Vite base middleware to allow requests that do not match the base path to proceed, enabling them to be handled by subsequent middlewares like the Angular SSR middleware.

Fixes #31896

### CODE REVIEW

File: packages/angular/build/src/tools/vite/middlewares/base-middleware.ts [hunk 1]
```diff
@@ -0,0 +1,56 @@
...
+      return next();
+    }
+
+    const { pathname, hash, search } = new URL(url, 'http://localhost');
+    if (pathname === '/' || pathname === '/index.html') {
+      res.writeHead(302, { Location: `${base}${search}${hash}` });
+      res.end();
+
+      return;
+    }
```
Comment (clydin) [inline packages/angular/build/src/tools/vite/middlewares/base-middleware.ts:52]: Would the existing fallback middleware handle this case?

Comment (alan-agius4) [reply packages/angular/build/src/tools/vite/middlewares/base-middleware.ts:52]: Yes, the existing middleware handle this https://github.com/vitejs/vite/blob/e81c183f8c8ccaf7774ef0d0ee125bf63dbf30b4/packages/vite/src/node/server/middlewares/base.ts#L29-L36

The problem with the existing middleware is anything below https://github.com/vitejs/vite/blob/e81c183f8c8ccaf7774ef0d0ee125bf63dbf30b4/packages/vite/src/node/server/middlewares/base.ts#L38

**Review by clydin — APPROVED** [review]

**Comment by alan-agius4** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: f39f7ee9529113f7c75d0e0e3ffa628fed9ce92f
- 21.0.x: 570ce8d3eeb280eeb6dca6ba54593c9325674741
