### PR TITLE
fix(@angular-devkit/build-angular): handle `ENOENT` and `ENOTDIR` errors when deleting outputs

### LINKED ISSUE #21202: Version 12.1 prints ENOENT no such file or directory
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 12.0.x

### Description

Just updated to 12.1 through ng update and now buildings seems to be unable to clear old files correctly. I always get errors like "ENOENT: no such file or directory" or "Error parsing bundle asset "/Volumes/Development/*/dist/aqua/main.f0babc2fd4603c54a819.js": no such file"

## 🔬 Minimal Reproduction

1. ng new
2. ng build

## 🔥 Exception or Error

<pre><code>

[error] Error: ENOENT: no such file or directory, stat '/Volumes/Development/__temp/twelve-one/dist/twelve-one'
    at Object.statSync (node:fs:1526:3)
    at __node_internal_ (node:internal/fs/utils:767:8)
    at Object.rmdirSync (node:fs:1146:15)
    at Object.deleteOutputDir (/Volumes/Development/__temp/twelve-one/node_modules/@angular-devkit/build-angular/src/utils/delete-output-dir.js:21:10)
    at initialize (/Volumes/Development/__temp/twelve-one/node_modules/@angular-devkit/build-angular/src/browser/index.js:86:17)
    at async SwitchMapSubscriber.project (/Volumes/Development/__temp/twelve-one/node_modules/@angular-devkit/build-angular/src/browser/index.js:114:17)
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.1.0
Node: 16.3.0 (Unsupported)
Package Manager: npm 7.16.0
OS: darwin x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.3.4
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by alan-agius4**
Closes #21202

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts [hunk 1]
```diff
@@ -18,5 +18,11 @@ export function deleteOutputDir(root: string, outputPath: string): void {
     throw new Error('Output path MUST not be project root directory!');
   }
 
-  rmdirSync(resolvedOutputPath, { recursive: true, maxRetries: 3 });
+  try {
+    rmdirSync(resolvedOutputPath, { recursive: true, maxRetries: 3 });
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts:22]: The `recursive` option is deprecated in Node.js v16 (which I think will cause a warning to be shown on the console).  `rmdirSync` in v16 will also throw on a nonexistent directory.
The `fs.rmSync` function is the recommended replacement which was introduced in v14.14.  I think we should probably adjust this to detect it and try `rmSync(resolvedOutputPath, { force: true, recursive: true, maxRetries: 3 });` first and then fallback to the existing function if the new one is not found.  Once v12 support is dropped, this could be cleaned up to just the new function.

**Review by clydin — CHANGES_REQUESTED** [review]

File: packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts:22]: Let’s do that.

File: packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts [hunk 2]
```diff
@@ -18,5 +18,34 @@ export function deleteOutputDir(root: string, outputPath: string): void {
     throw new Error('Output path MUST not be project root directory!');
   }
 
-  rmdirSync(resolvedOutputPath, { recursive: true, maxRetries: 3 });
+  type fsNew = typeof fs & {
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/utils/delete-output-dir.ts:21]: This type doesn't appear to be used.

**Review by clydin — APPROVED** [review]
