### PR TITLE
fix(@angular-devkit/build-angular): fix permission errors for ES5 bu…

### LINKED ISSUE #15490: Permission error on second build when nomodule polyfill is included
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
I'm not sure. This is the first time I've seen it, but I recently upgraded to Angular 8.

### Description

I reproducibly get a permission error, seen below, in a clean, brand new angular project, when browserslist specifies browsers that require nomodule polyfill.

## 🔬 Minimal Reproduction

1. `ng new test`
2. In the new project, add to browserslist: `ios_saf >= 10`
3. `ng build --prod`
4. `ng build --prod` (again)

## 🔥 Exception or Error
<pre><code>
chunk {0} runtime-es2015.24b02acc1f369d9b9f37.js (runtime) 2.83 kB [entry] [rendered]
chunk {1} main-es2015.7c221f45d48105c2ba9d.js (main) 251 kB [initial] [rendered]
chunk {2} polyfills-es2015.fd917e7c3ed57f282ee5.js (polyfills) 64.3 kB [initial] [rendered]
chunk {3} polyfills-es5-es2015.3aa54d3e5134f5b5b842.js (polyfills-es5) 223 kB [initial] [rendered]
chunk {4} styles.3ff695c00d717f2d2a11.css (styles) 0 bytes [initial] [rendered]
chunk {polyfills-nomodule-es5} polyfills-nomodule-es5.b79bfebc521ac1ea1602.js (polyfills-nomodule-es5) 372 bytes [entry] [rendered]
Date: 2019-08-30T21:28:19.886Z - Hash: c40b7c3c8a049ad41deb - Time: 12280ms
Generating ES5 bundles for differential loading...
An unhandled exception occurred: EACCES: permission denied, copyfile '/Users/karp/Documents/git/outputhashing2/node_modules/.cache/angular-build-dl/content-v2/sha512/f3/26/48b77841506560fd29c0954a8fe431f253a24b4306fd7399aaec8a09d0dcc974a357856c0b742e8e40a0ac34f406ebc3b58955f738ea327fc8e1819cd7a3' -> '/Users/karp/Documents/git/outputhashing2/dist/outputhashing2/polyfills-nomodule-es5.b79bfebc521ac1ea1602.js'
See "/private/var/folders/pf/z4z5f17x7jb0n0m44bmkhyw00000gn/T/ng-7tYGDL/angular-errors.log" for further details.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.2
Node: 10.16.0
OS: darwin x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.2
@angular/cli                      8.3.2
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.2
@schematics/update                0.803.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
Nuking `node_module` (and presumably just the cache dir within) and reinstalling fixes the issue for one build.
Sorry to put this out there on a Friday afternoon!

### PR DESCRIPTION
**Pull request by alan-agius4**
…ndles

copyFilesSync will also copy permissions which may result in permissions errors.

Closes #15490

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/browser/index.ts [hunk 1]
```diff
@@ -473,6 +473,7 @@ export function buildWebpackBrowser(
 
               for (const action of cacheActions) {
                 fs.copyFileSync(action.src, action.dest, fs.constants.COPYFILE_FICLONE);
+                fs.chmodSync(action.dest, 0o666);
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/browser/index.ts]: This is the default mode for most of NodeJs methods, such as `writeFile`

Comment (clydin) [reply packages/angular_devkit/build_angular/src/browser/index.ts]: I think we should go with `0o644`.  This appears to be the value used for the output of the first build.

Also, can you add a comment explaining that the cache writes entries as readonly so we need to correct the permissions here.  Code Ref: https://github.com/npm/cacache/blob/073fbe1a9f789ba42d9a41de7b8429c93cf61579/lib/util/move-file.js#L36

It also only does it on non-windows systems, not sure whether we should as well.
