### PR TITLE
fix(@angular/build): enhance Vitest resolution for optimal package loading

### LINKED ISSUE #31808: rc.3 vitest browser mode issue with tslib
### Command

test

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

rc.2

### Description

In rc.3 when using vitest in browser mode and importing a decorator from a third party library, `ng test` fails with: `TypeError: Cannot destructure property '__extends' of 'import_tslib.default' as it is undefined.`
This was not an issue in rc.2

### Minimal Reproduction

Minimal reproduction: https://github.com/LeonEck/test-tslib
Running `ng test` shows the described error.

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI       : 21.0.0-rc.3
Angular           : 21.0.0-rc.2
Node.js           : 24.11.1
Package Manager   : npm 11.6.2
Operating System  : darwin arm64

┌───────────────────────────┬───────────────────┬───────────────────┐
│ Package                   │ Installed Version │ Requested Version │
├───────────────────────────┼───────────────────┼───────────────────┤
│ @angular/build            │ 21.0.0-rc.3       │ ^21.0.0-rc.3      │
│ @angular/cli              │ 21.0.0-rc.3       │ ^21.0.0-rc.3      │
│ @angular/common           │ 21.0.0-rc.2       │ ^21.0.0-next.0    │
│ @angular/compiler         │ 21.0.0-rc.2       │ ^21.0.0-next.0    │
│ @angular/compiler-cli     │ 21.0.0-rc.2       │ ^21.0.0-next.0    │
│ @angular/core             │ 21.0.0-rc.2       │ ^21.0.0-next.0    │
│ @angular/forms            │ 21.0.0-rc.2       │ ^21.0.0-next.0    │
│ @angular/platform-browser │ 21.0.0-rc.2       │ ^21.0.0-next.0    │
│ @angular/router           │ 21.0.0-rc.2       │ ^21.0.0-next.0    │
│ rxjs                      │ 7.8.2             │ ~7.8.0            │
│ typescript                │ 5.9.3             │ ~5.9.2            │
│ vitest                    │ 4.0.8             │ ^4.0.8            │
└───────────────────────────┴───────────────────┴───────────────────┘
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by clydin**
Align Vitest's module resolution with the development server to ensure consistent behavior. This change configures Vitest to prioritize ESM-optimized package entry points by setting 'es2020', 'module', and 'main' as main fields and 'es2015', 'es2020', and 'module' as conditions during module resolution. This improves compatibility and performance by utilizing modern JavaScript module formats where available.

Closes #31808

### CODE REVIEW

File: packages/angular/build/src/builders/unit-test/runners/vitest/plugins.ts [hunk 1]
```diff
@@ -124,6 +124,10 @@ export async function createVitestConfigPlugin(
           noDiscovery: true,
           include: options.optimizeDepsInclude,
         },
+        resolve: {
+          mainFields: ['es2020', 'module', 'main'],
```
Comment (hybrist) [inline packages/angular/build/src/builders/unit-test/runners/vitest/plugins.ts:128]: Given that this contains some values that could change over time (e.g. es2020), can we decrease the risk of getting out of sync somehow?

Comment (clydin) [reply packages/angular/build/src/builders/unit-test/runners/vitest/plugins.ts:128]: Those are there for older APF packages.  We stopped using that in newer APF revisions.  It's just `default` now with a single code variant.

**Comment by clydin** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 9b5a452fe2fc22b7e6a9301c43be84d9074576a2
- 21.0.x: f7c4a4c1dcd575dec82cc06597e3d6620b1be729
