### PR TITLE
Replace regex with correct project name valdiation

### LINKED ISSUE #17579: Generated angular.json file does not correctly lower case the application name
# 🐞 Bug report

### Command (mark with an `x`)

- [x ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 
I'm not certain whether this is a regression. I don't recall seeing the issue. No one had reported it to me previously. But that doesn't mean it didn't exist.

### Description

 
When you create a new Angular project using `ng new` with an upper case or mixed case name, the Angular CLI correctly converts the name to lower case for the keys in the package.json file. It does *not* convert the name to lower case for the keys in the angular.json file. See the "Minimal Reproduction" for screen shots.

## 🔬 Minimal Reproduction

ng new Hello-World

Resulting package.json file correctly lower cases the project name:
image

Resulting angular.json file does *not* lower case the project name, resulting in an error (see below):
image

Notice the resulting error: 
image

## 🔥 Exception or Error
<pre><code>

</code></pre>
Property Hello-World is not allowed

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.1.3
Node: 12.16.1
OS: win32 x64

Angular: 9.1.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.3
@angular-devkit/build-angular     0.901.3
@angular-devkit/build-optimizer   0.901.3
@angular-devkit/build-webpack     0.901.3
@angular-devkit/core              9.1.3
@angular-devkit/schematics        9.1.3
@angular/cli                      9.1.3
@ngtools/webpack                  9.1.3
@schematics/angular               9.1.3
@schematics/update                0.901.3
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by Jefiozie**
If I understand the comments of @alan-agius4 on #17579 correct this PR will fix the IDE validation error that it is providing today.
I've replaced the regex with the correct one, just to make sure we are not forgetting when closing the ticket there is a second comment by @alan-agius4:

>When it comes to project directories, I am inclined towards always dasherizing the project folder name to align with other schematics where the folder name is always dasherized, that being said It's not a biggy, as long as the schema validation is fixed.

Should we make a separate issue for this or are we leaving this as is?

Let me know if I need to make changes or add additional information.

Closes #17579

### CODE REVIEW

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Thanks for this. 

Can you please update the commit message to match our guidelines in: https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#commit

Example
```
fix(@angular/cli): replace regex with correct project name validation

Closes #17579
```

**Comment by alan-agius4** [comment]
> If I understand the comments of @alan-agius4 on #17579 correct this PR will fix the IDE validation error that it is providing today.
> I've replaced the regex with the correct one, just to make sure we are not forgetting when closing the ticket there is a second comment by @alan-agius4:
> 
> > When it comes to project directories, I am inclined towards always dasherizing the project folder name to align with other schematics where the folder name is always dasherized, that being said It's not a biggy, as long as the schema validation is fixed.
> 
> Should we make a separate issue for this or are we leaving this as is?
> 
> Let me know if I need to make changes or add additional information.
> 
> Closes #17579

I think for the time being we can leave this as is.

**Comment by Jefiozie** [comment]
Hi @alan-agius4, yes I wil do this first thing tomorrow.

**Comment by Jefiozie** [comment]
Hi @alan-agius4, Í've made the changes as requested.

File: packages/schematics/angular/application/index.ts [hunk 1]
```diff
@@ -300,8 +300,8 @@ export default function (options: ApplicationOptions): Rule {
     const isRootApp = options.projectRoot !== undefined;
     const appDir = isRootApp
       ? normalize(options.projectRoot || '')
-      : join(normalize(newProjectRoot), options.name);
-    const sourceDir = `${appDir}/src/app`;
+      : join(normalize(newProjectRoot), strings.dasherize(options.name));
+    const sourceDir = `${strings.dasherize(appDir)}/src/app`;
```
Comment (alan-agius4) [inline packages/schematics/angular/application/index.ts:304]:
```suggestion
    const sourceDir = `$(appDir}/src/app`;
```

Shouldn't be needed, since it's already transformed in the above line.

File: packages/schematics/angular/application/index_spec.ts [hunk 2]
```diff
@@ -451,4 +451,20 @@ describe('Application Schematic', () => {
     expect(content).toContain('not IE 11');
     expect(content).toContain('not IE 9-10');
   });
+
+  it(`should create kebab-case project folder names with camelCase project name`, async () => {
+    const options: ApplicationOptions = { ...defaultOptions, name: 'myCool' };
+    const tree = await schematicRunner.runSchematicAsync('application', options, workspaceTree)
+      .toPromise();
+    const exists = tree.exists('/projects/my-cool/.browserslistrc');
+    expect(exists).toBeTruthy();
```
Comment (alan-agius4) [inline packages/schematics/angular/application/index_spec.ts:460]:
```suggestion
    expect(exists).toBeTrue();
```

File: packages/schematics/angular/application/index_spec.ts [hunk 3]
```diff
@@ -451,4 +451,20 @@ describe('Application Schematic', () => {
...
+  });
+
+  it(`should create kebab-case project folder names with PascalCase project name`, async () => {
+    const options: ApplicationOptions = { ...defaultOptions, name: 'MyCool' };
+    const tree = await schematicRunner.runSchematicAsync('application', options, workspaceTree)
+      .toPromise();
+    const exists = tree.exists('/projects/my-cool/.browserslistrc');
+    expect(exists).toBeTruthy();
```
Comment (alan-agius4) [inline packages/schematics/angular/application/index_spec.ts:468]:
```suggestion
    expect(exists).toBeTrue();
```

**Review by alan-agius4 — APPROVED** [review]
