### PR TITLE
fix(@schematics/angular): `findModuleFromOptions` not handling proper…

### LINKED ISSUE #13714: Newly created component not being added to submodule
# 🐞 Bug report

### Command (mark with an `x`)

```
- [X] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Not sure

#### Expected behaviour:
When a new component is generated using `ng g c someModule/newComponent`, it should be added to sub module.

#### Actual behaviour:
Newly generated component is added to root module instead of in sub module.

#### Scenario:
If i have a submodule called DeleteModule
app ===> delete ===> delete.module.ts

and if generate a component using` ng g c delete/newComponent`. the newly generated components is added to DeleteModule. However if my DeleteModule's structure is
app => FeatureModule ===> delete ===> delete.module.ts

and i try to generate new component using `ng g c FeatureModule/delete/someComponent`, thee newly generated component is added to root module instead of in sub module.

## 🔬 Minimal Reproduction
1. Create a new angular project using ng new app.
2. Create a sub module using `ng g m FeatureModule/delete`.
3. Create a component using `ng g c FeatureModule/delete/newComponent`.

## 🔥 Exception or Error
None
</code></pre>

## 🌍 Your Environment
<pre><code>
Defaults
</code></pre>

**Anything else relevant?**
None

### PR DESCRIPTION
**Pull request by alan-agius4**
…ly different casing in name

At the moment users can have various casing and separators in paths, we should not always dasherize the name when resolving modules.

As for example when providing something like:

```
/module/SubModule/feature
```

It won't be able to resolve the modules properly as `sub-module` does't exist.

This PR also updates the test for underscore as previously it was not properly testing this usercase, since the formatter was used on name and not th path.

Fixes #13714

### CODE REVIEW

File: packages/schematics/angular/utility/find-module_spec.ts [hunk 1]
```diff
@@ -111,12 +111,20 @@ describe('find-module', () => {
       expect(modPath).toEqual('/projects/my-proj/src/app.module.ts' as Path);
     });
 
-    it('should find a module if nameFormatter is provided', () => {
```
Comment (alan-agius4) [inline packages/schematics/angular/utility/find-module_spec.ts]: this test was actually not testing anything, as `nameFormatter ` was only used when `name` is provided

File: packages/schematics/angular/utility/find-module.ts [hunk 2]
```diff
@@ -25,6 +24,7 @@ export interface ModuleOptions {
   skipImport?: boolean;
   moduleExt?: string;
   routingModuleExt?: string;
+  /** @deprecated This option is no longer required and will be removed in version 9 */
```
Comment (clydin) [inline packages/schematics/angular/utility/find-module.ts]: These are all internal.  The deprecation isn’t necessary here.

Comment (alan-agius4) [reply packages/schematics/angular/utility/find-module.ts]: The thing is that this is used within google so while it’s used internally if we remove it it will break inside google.

Comment (clydin) [reply packages/schematics/angular/utility/find-module.ts]: That would actually be more of a reason to completely remove it since you would then get a compile time error instead of differing runtime behavior; which may not be initially noticed.

Comment (alexeagle) [reply packages/schematics/angular/utility/find-module.ts]: Removing it is okay too, but @kyliau should probably try a g3sync to see how difficult it will be to keep the sync going.
We haven't synced it in a while IIRC so it might already be hard to do...

Comment (alan-agius4) [reply packages/schematics/angular/utility/find-module.ts]: Removed
