### PR TITLE
fix(@angular/cli): improve list_projects MCP tool to find all workspaces in monorepos

### LINKED ISSUE #30855: Angular CLI MCP cannot detect projects in monorepo
### Command

other

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

MCP cannot detect projects in monorepo when angular.json is not in repository root and lacks option to specify project locations.

Installed using ng mcp in vscode.

When running the official Angular CLI MCP server (npx @angular/cli mcp) inside a monorepo where Angular projects are located in subfolders (e.g. /apps/abc, /apps/def), the MCP server reports: You currently have no Angular projects defined in your workspace (no projects found in your Angular configuration).

In this setup, the repository root contains only meta/tooling files (e.g. README.md, .vscode/), plus other non‑Angular apps such as backends (in apps). There is no angular.json in the root - each Angular application has its own angular.json in its respective /apps/... folder.

Currently, there is no way to tell the official MCP server where to look for Angular workspaces or angular.json files. This makes MCP unusable for many common monorepo layouts.

### Minimal Reproduction

Create folder structure like this:

```
repo-root/
  README.md
  .vscode/
    mcp.json
  apps/
    project-anga/
      angular.json ...
    project-angb/
      angular.json ...
    project-backa/
      package.json ...
```

Install mcp server as defined in `ng mcp`.

```
{
  "servers": {
    "angular-cli": {
      "type": "stdio",
      "command": "npx",
      "args": [
        "@angular/cli",
        "mcp"
      ]
    }
  },
  "inputs": []
}
```

Then ask which project are in angular application in chat.

### Exception or Error

```text

```

### Your Environment

```text
Angular CLI: 20.1.4
Node: 22.17.1
Package Manager: npm 11.5.2
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.2001.4 (cli-only)
@angular-devkit/core         20.1.4 (cli-only)
@angular-devkit/schematics   20.1.4 (cli-only)
@schematics/angular          20.1.4 (cli-only)
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by clydin**
The `list_projects` MCP tool is enhanced with better monorepo support by correctly discovering all `angular.json` files in any subdirectory.

The tool's description is also rewritten to follow best practices for LLM consumption, using structured tags like `<Purpose>`, `<Use Cases>`, and `<Operational Notes>` to provide clear and actionable guidance.

Closes #30855

### CODE REVIEW

**Review by alan-agius4 — APPROVED** [review]

File: packages/angular/cli/src/commands/mcp/tools/projects.ts [hunk 1]
```diff
@@ -6,53 +6,103 @@
  * found in the LICENSE file at https://angular.dev/license
  */
 
+import { glob } from 'node:fs/promises';
```
Comment (alan-agius4) [inline packages/angular/cli/src/commands/mcp/tools/projects.ts]: This was only introduced in version 22. We still support and test in version 20.

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
See glob comment
