### PR TITLE
 fix(@angular-devkit/build-optimizer): don't add pure comments to tslib helpers

### LINKED ISSUE #15301: @angular-devkit/build-angular removes custom library decorators from another libraries on production build
# 🐞 Bug report

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

I define  some decorators on one of my libraries  and use them a lot on other libraries.
When I build my application with --prod  Angular compiler removes using of them in generated code.

This problem occurs with **@angular-devkit/build-angular@0.802.0** and I have  no problem with **@angular-devkit/build-angular@0.801.3**

### PR DESCRIPTION
**Pull request by alan-agius4**
Closes #15301

### CODE REVIEW

File: packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts [hunk 1]
```diff
@@ -78,9 +76,15 @@ export function findTopLevelFunctions(parentNode: ts.Node): Set<ts.Node> {
         topLevelFunctions.add(node);
       } else if (ts.isCallExpression(innerNode)) {
         let expression: ts.Expression = innerNode.expression;
+
+        if (isHelperName(expression.getText())) {
```
Comment (clydin) [inline packages/angular_devkit/build_optimizer/src/transforms/prefix-functions.ts]: getText can be expensive.  Better to check for an identifier and then access it’s text property.

File: packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts [hunk 2]
```diff
@@ -41,3 +41,15 @@ export function hasPureComment(node: ts.Node): boolean {
 
   return !!leadingComment && leadingComment.some(comment => comment.text === pureFunctionComment);
 }
+
+export function isHelperName(name: string): boolean {
+  // TODO: there are more helpers than these, should we replace them all?
```
Comment (clydin) [inline packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: As a follow up, I think it would be useful to add a one time initialization that would import “tslib” and add all the exported helpers to a set and use that for checks here.  That way it wouldn’t constantly have to be synced.  Especially considering it’s new use in this PR.

Comment (alan-agius4) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: Thanks for the super fast review. I agree.

File: packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts [hunk 3]
```diff
@@ -5,9 +5,12 @@
  * Use of this source code is governed by an MIT-style license that can be
  * found in the LICENSE file at https://angular.io/license
  */
+// tslint:disable-next-line: no-implicit-dependencies
+import * as tslib from 'tslib';
```
Comment (alan-agius4) [inline packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: Technically `tslib` should be marked as a peerDep as it is require.

Any reason why it's not at the moment?

Comment (clydin) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: It definitely should be now that it is used explicitly.

File: packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts [hunk 4]
```diff
@@ -5,9 +5,12 @@
...
 import * as ts from 'typescript';
 
 const pureFunctionComment = '@__PURE__';
+const tslibHelpers = new Set<string>(Object.keys(tslib));
```
Comment (clydin) [inline packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: Will this pull in anything else besides the helpers?

Comment (alan-agius4) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: There is nothing else defined apart from the helpers. 

if it makes you feel better, when we can do a filter `Object.keys(tslib).filter(x => x.startsWith('__')`

Comment (clydin) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: Good idea.  Just in case something changes in the future.

Comment (clydin) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: Could you add a short comment to explaining the significance of `__`?

File: packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts (hunk 3 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: are you for peer or direct dep?

File: packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts (hunk 4 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: done

File: packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts (hunk 3 above)
Comment (clydin) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: I think peer dep is more correct but we would need to propagate it up through `build-angular` since it is a project level dependency.

Comment (alan-agius4) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: Wouldn't we get something like `@angular-devkit/build-angular > @angular-devkit/build-optimizer" has incorrect peer dependency "tslib".`?

Comment (clydin) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: It would need to be a peer dep on `build-angular` as well.  That way `build-angular` satisfies `build-optimizer`.

But let's go with a direct dep for now. Since it won't cause peer dep warning changes which is problematic in a patch/minor release.

Comment (alan-agius4) [reply packages/angular_devkit/build_optimizer/src/helpers/ast-utils.ts]: Done with the direct dependecy

**Comment by alan-agius4** [comment]
Didn't apply cleanly on patch. Patch version: https://github.com/angular/angular-cli/pull/15314
