### PR TITLE
fix(@angular-devkit/build-angular): only add `@angular/platform-server/init` when package is installed.

### LINKED ISSUE #24188: [Clover] Module not found: Error: Can't resolve '@angular/platform-server/init' ...
# 🐞 Bug report

#### What modules are related to this issue?

- [ ] builders
- [x] common
- [ ] express-engine

### Is this a regression?

Since I updated to Universal/Angular 15 next, the probleme appeared, it worked properly on last version of Universal/Angular 14.

### Description

I am trying to build the SSR server using Clover Engine, then I'm getting an error.

## 🔬 Minimal Reproduction

1. Clone https://github.com/Yberion/Angular-SSR-Clover-Engine
2. `npm run build:server:fastify`

## 🔥 Exception or Error

<pre><code>Error: Module not found: Error: Can't resolve '@angular/platform-server/init' in 'D:\GitHub\Angular-SSR-Clover-Engine'
</code></pre>

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 15.0.0-rc.2
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.0-rc.2
... cli, common, compiler, compiler-cli, core, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0-rc.2
@angular-devkit/build-angular   15.0.0-rc.2
@angular-devkit/core            15.0.0-rc.2
@angular-devkit/schematics      15.0.0-rc.2
@nguniversal/common             15.0.0-next.1
@schematics/angular             15.0.0-rc.2
rxjs                            7.5.7
typescript                      4.8.4
</code></pre>

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit fixes an issue where `@angular/platform-server/init` was added as an entry-point during the server build even when this was not installed.

Closes #24188

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/builders/server/index.ts [hunk 1]
```diff
@@ -173,25 +174,16 @@ async function initialize(
  * This is needed so that DI tokens can be referenced and set at runtime outside of the bundle.
  */
 function getPlatformServerExportsConfig(wco: BrowserWebpackConfigOptions): Partial<Configuration> {
-  // Add `@angular/platform-server` exports.
-  // This is needed so that DI tokens can be referenced and set at runtime outside of the bundle.
-  try {
-    // Only add `@angular/platform-server` exports when it is installed.
-    // In some cases this builder is used when `@angular/platform-server` is not installed.
-    // Example: when using `@nguniversal/common/clover` which does not need `@angular/platform-server`.
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/builders/server/index.ts:181]: nit: I think these comments are more relevant here than in the helper function.

**Review by clydin — APPROVED** [review]
