### PR TITLE
fix(@angular/ssr): enhance dynamic route matching for better performance and accuracy

### LINKED ISSUE #29452: Routes beginning with Dynamic Parameters break Angular Prerendering and SSR
### Command

build, serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Angular provides examples on how to use prerendering for parametrized routes like `post/:id`. However, in our project, we have routes with dynamic parameters at the beginning of the route path, such as `:seoAlias/:category/:offerId`.

This specific route structure causes issues in `Client`, `Server`, and `Prerender` modes, breaking other routes when serving the app in development mode or building the application.

### Minimal Reproduction

We have created a simple reproduction repository:
[https://github.com/robertsine/car-shop](https://github.com/robertsine/car-shop)

Inside the file `app.routes.server.ts` there are several route variants. By uncommenting them, you can reproduce the issue. Notably, only `offers/:slug` works well. Other server routes are breaking entire app, when serving app in dev mode or serving build.

We tried to use the `**` path as a _hack_ to prerender our parameterized routes. However, in development mode, it does not work. In build mode, it creates prerendered pages. For note, we must ensure unique parameters across the entire route configuration to avoid hitting several paths with same parameter name. However, it generates fallback content inside the index files.

### Exception or Error

```text
Error: Error(s) occurred while extracting routes:
- The '' server route does not match any routes defined in the Angular routing configuration (typically provided as a part of the 'provideRouter' call). Please make sure that the mentioned server route is present in the Angular routing configuration.
```

### Your Environment

```text
Angular CLI: 19.0.6
Node: 22.13.1
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 19.0.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.6
@angular-devkit/build-angular   19.0.6
@angular-devkit/core            19.0.6
@angular-devkit/schematics      19.0.6
@angular/cli                    19.0.6
@angular/ssr                    19.0.6
@schematics/angular             19.0.6
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
Updated route matching logic to prioritize closest matches, improving the accuracy of dynamic route resolution. Also we optimized performance by eliminating unnecessary recursive checks, reducing overhead during route matching.

Closes #29452

### CODE REVIEW

File: packages/angular/ssr/src/routes/ng-routes.ts [hunk 1]
```diff
@@ -458,6 +458,13 @@ function buildServerConfigRouteTree({ routes, appShellRoute }: ServerRoutesConfi
       continue;
     }
 
+    if (path.includes('**') && 'getPrerenderParams' in metadata) {
+      errors.push(
+        `Invalid '${path}' route configuration: 'getPrerenderParams' cannot be used with a '**' route.`,
```
Comment (dgp1130) [inline packages/angular/ssr/src/routes/ng-routes.ts:463]: Question: Is this true for a single `*` too? Should we ban that as well?

File: packages/angular/ssr/src/routes/route-tree.ts [hunk 2]
```diff
@@ -128,29 +114,28 @@ export class RouteTree<AdditionalMetadata extends Record<string, unknown> = {}>
...
 
-    for (const segment of segments) {
-      // Replace parameterized segments (e.g., :id) with a wildcard (*) for matching
-      const normalizedSegment = segment[0] === ':' ? '*' : segment;
-      let childNode = node.children.get(normalizedSegment);
+    for (let index = 0; index < segments.length; index++) {
+      let segment = segments[index];
+      if (segment[0] === ':') {
+        // Replace parameterized segments (e.g., :id) with a wildcard (*) for matching
+        segments[index] = segment = '*';
```
Comment (dgp1130) [inline packages/angular/ssr/src/routes/route-tree.ts:122]: Suggestion: Personally I find this kind of mutation hard to follow and the double assignment makes it particularly tricky to notice that `segment` is updated too.

Could we do this transform separately first? It would also allow us to drop the manual iteration with `index`.

```typescript
const segs = segments.map((segment) => segment.startsWith(':') ? '*' : segment);
for (const segment of segs) {
  // ...
}
```

(Should use a better name than `segs`, but hopefully that gets the point across.)

**Review by dgp1130 — APPROVED** [review]
It seems like there's a few small breaking changes here. I know this feature is still dev preview, so we can probably ship this and I'm happy to defer to your judgement. I just want to make sure we're thinking about the impact here and making that decision intentionally.

File: packages/angular/ssr/src/routes/ng-routes.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/angular/ssr/src/routes/ng-routes.ts:463]: Updated

**Comment by alan-agius4** [comment]
The changes were merged into the following branches: main, 19.1.x
