### PR TITLE
fix(@ngtools/webpack): add local dts file as dependencies

### LINKED ISSUE #16920: [IVY][9.0.0] Renaming a directive in a consumed library built by ng-packagr causes error in Application when in watch mode
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Description

We are building a library with ng-packagr and then consuming it in our Angular 9 application.
When I renamed one of the exported directives used by the application I get an error causing rendering to skip the rest of the page.

image

image

## 🔬 Minimal Reproduction
As usual I can pr

ovide an example but it takes time. Let me know if it's needed.

## 🔥 Exception or Error
<pre><code>
angular.js:31599 ERROR TypeError: Cannot read property 'ɵcmp' of undefined
    at getComponentDef (angular.js:29620)
    at extractDirectiveDef (angular.js:29446)
    at Array.map (<anonymous>)
    at def.directiveDefs (angular.js:29442)
    at createTView (angular.js:35363)
    at getOrCreateTComponentView (angular.js:35315)
    at addComponentLogic (angular.js:36046)
    at instantiateAllDirectives (angular.js:35890)
    at createDirectivesInstances (angular.js:35283)
    at ɵɵelementStart (angular.js:41965)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 12.14.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/http                     8.0.0-beta.10
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.5
</code></pre>

**Anything else relevant?**

### LINKED ISSUE #16921: [IVY][9.0.0] Adding additional inputs in directive built by ng-packagr is not recognized by consuming app in watch mode
# 🐞 Bug report

### Command (mark with an `x`)

- [x] build

### Description

We are building a library with ng-packagr and then consuming it in our Angular 9 application.
When I added a new input in my directive it wasn't recognized until after I stopped my build completely and started from scratch.

After the first initial build, when in watch mode, I added the input `resizeElement`
```
@Directive({
    selector: '[resizable]'
})
export class ResizableDirective implements OnInit, OnDestroy {
    @Input('resizable') containerSelector: string;
    @Input('resizeElement') resizeElementSelector: string;
    ...
}
```

After the library was rebuilt by the watcher, and then the app was rebuilt, also by a watcher, the input was not recognized by the Angular compiler.

## 🔬 Minimal Reproduction
As usual I can provide an example but it takes time. Let me know if it's needed.

## 🔥 Exception or Error
<pre><code>
 | ERROR in packages\web-app-edit\src\app\components\common\condition-editor\condition-editor.component.html:1:33 - error NG8002: Can't bind to 'resizeElement' since it isn't a known property of 'div'. |
 | 1 <div [resizable]="dialogRef.id" [resizeElement]="resizeSelector">
 |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 |
 |   packages\web-app-edit\src\app\components\common\condition-editor\condition-editor.component.ts:6:18
 |     6     templateUrl: 'condition-editor.component.html',
 |                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 |     Error occurs in the template of component ConditionEditorComponent.
 |
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.1
Node: 12.14.0
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/http                     8.0.0-beta.10
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.5
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by alan-agius4**
We now add non node_modules `.d.ts` as a dependency of the main chunk. This is important under Ivy, because NG metadata is now part of the declarations files ex:

```ts
export declare class FooComponent implements OnInit {
    constructor();
    ngOnInit(): void;
    static ɵfac: i0.ɵɵFactoryDef<FooComponent>;
    static ɵcmp: i0.ɵɵComponentDefWithMeta<FooComponent, "lib-foo", never, {}, {}, never>;
}
```

Previously such files were not being added as dependency and such files didn't get invalidated when changed.

Closes #16920 and closes #16921
Ref: TOOL-1323

### CODE REVIEW

File: packages/angular/cli/utilities/log-file.ts [hunk 1]
```diff
@@ -0,0 +1,29 @@
...
+import { normalize } from 'path';
+
+let logPath: string | undefined;
+
+/**
+ * Writes an Error to a temporary log file.
+ * If this method is called multiple times from the same process the same log file will be used.
+ * @returns The path of the generated log file.
+ */
+export function writeErrorToLogFile(error: Error): string {
```
Comment (filipesilva) [inline packages/angular/cli/utilities/log-file.ts]: This file looks like it was erroneously included because it was part of another branch.

Comment (alan-agius4) [reply packages/angular/cli/utilities/log-file.ts]: Indeed
