### PR TITLE
fix for #14467 - fix(@schematics/angular): webworker snippet should not generate to module

### LINKED ISSUE #14467: Code generated for webWorker in incorrect file
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
Not Sure

### Description

 A clear and concise description of the problem...

Create a new app with routing as Yes
run "ng g webWorker app"

webWorker code is added to app-routing.module.ts file

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

  "@angular/cli": "~8.0.0-rc.3",
"@angular/common": "~8.0.0-rc.4",
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by santoshyadav198613**
Fixes #14467

### CODE REVIEW

**Comment by alan-agius4** [comment]
@santoshyadav198613, thanks for this. Can you kindly fix the `fixes` in the commit message as well?
Thanks.

**Comment by santoshyadav198613** [comment]
Sure @alan-agius4 , will do thanks.

File: packages/schematics/angular/web-worker/index.ts [hunk 1]
```diff
@@ -140,7 +140,8 @@ function addSnippet(options: WebWorkerOptions): Rule {
 
     const siblingModules = host.getDir(options.path).subfiles
       // Find all files that start with the same name, are ts files, and aren't spec files.
-      .filter(f => f.startsWith(options.name) && f.endsWith('.ts') && !f.endsWith('spec.ts'))
+      .filter(f => f.startsWith(options.name)
```
Comment (alan-agius4) [inline packages/schematics/angular/web-worker/index.ts]: @filipesilva should web-workers should be inserted only to components?

@santoshyadav198613 - the statements here can be simplified slightly, if the above is the case.
```ts
.filter(f => f.startsWith(options.name) && f.endsWith('component.ts'))
```

Comment (filipesilva) [reply packages/schematics/angular/web-worker/index.ts]: Now that you mention it, it's very common to insert them into services as well I believe. I think we should specialcase spec files and routing files actually...

So something like this:
```
.filter(f => f.startsWith(options.name) && f.endsWith('.ts') 
  && !f.endsWith('spec.ts') && !f.endsWith('-routing.module.ts'))
```

These two are indeed special because our generators make them automatically.

Comment (santoshyadav198613) [reply packages/schematics/angular/web-worker/index.ts]: But in that case, we have interfaces, directives as well.

Comment (filipesilva) [reply packages/schematics/angular/web-worker/index.ts]: Yes, it should be ok to put a webworker in those. Specs and routing files are different because are auxiliary to the other, more important, file. And in this specific code that is problematic because we sort by filename.

Comment (santoshyadav198613) [reply packages/schematics/angular/web-worker/index.ts]: thanks a lot, will make the changes. You guys are super helpful.

Comment (santoshyadav198613) [reply packages/schematics/angular/web-worker/index.ts]: Also i think we should not consider moduel at all so changing it to
 .filter(f => f.startsWith(options.name) && f.endsWith('.ts') 
  && !f.endsWith('spec.ts') && !f.endsWith('-.module.ts')) 
would be better.

Comment (filipesilva) [reply packages/schematics/angular/web-worker/index.ts]: I think that's a fair assumption, yes. That looks good to me.

Comment (santoshyadav198613) [reply packages/schematics/angular/web-worker/index.ts]: Done with the changes.

File: packages/schematics/angular/web-worker/index.ts [hunk 2]
```diff
@@ -139,8 +139,10 @@ function addSnippet(options: WebWorkerOptions): Rule {
     }
 
     const siblingModules = host.getDir(options.path).subfiles
-      // Find all files that start with the same name, are ts files, and aren't spec files.
-      .filter(f => f.startsWith(options.name) && f.endsWith('.ts') && !f.endsWith('spec.ts'))
+      // Find all files that start with the same name, are ts files,
+      // and aren't spec or module files.
+      .filter(f => f.startsWith(options.name) && f.endsWith('.ts')
+      && !f.endsWith('spec.ts') && !f.endsWith('-.module.ts'))
```
Comment (alan-agius4) [inline packages/schematics/angular/web-worker/index.ts]: This doesn't look right the `-.module.ts` will not match any file that is generated via the CLI.

I think you meant something like
```ts
.filter(f => f.startsWith(options.name) && f.endsWith('.ts')
      && !/\.(module|spec)\.ts$/.test(f))

```

File: packages/schematics/angular/web-worker/index_spec.ts [hunk 3]
```diff
@@ -35,7 +35,7 @@ describe('Service Worker Schematic', () => {
     name: 'bar',
     inlineStyle: false,
     inlineTemplate: false,
-    routing: false,
+    routing: true,
```
Comment (alan-agius4) [inline packages/schematics/angular/web-worker/index_spec.ts]: Changing this value, will ensure that the new logic is tested.

**Comment by santoshyadav198613** [comment]
> Hi @santoshyadav198613, sorry to barge in your PR and pushing directly. But we need to get this merged ASAP for the version 8 final.
> 
> Thanks a lot for your contribution.
> 
> //cc @alexeagle, this is a go!

thanks @alan-agius4 , sorry was not feeling well, so was not able to make changes last night. But happy that I was able to find the issue.
