### PR TITLE
fix(@angular/cli): `ng e2e` and `ng lint` prompt requires to hit Enter twice to proceed on Windows

### LINKED ISSUE #26724: `ng e2e` and `ng lint` have to hit Enter twice to go on
### Command

e2e

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Please watch the video I prepared. YouTube: https://youtu.be/OMq-22_fsgI

### Minimal Reproduction

```sh
ng new demo1 --ssr=false --style=css
ng e2e
```

### Exception or Error

_No response_

### Your Environment

```text
Angular CLI: 17.0.7
Node: 18.16.0
Package Manager: npm 9.5.1
OS: win32 x64

Angular: 17.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.7
@angular-devkit/build-angular   17.0.7
@angular-devkit/core            17.0.7
@angular-devkit/schematics      17.0.7
@schematics/angular             17.0.7
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

### Anything else relevant?

`ng lint` have the same issue as well. When seeing `Would you like to proceed?`, I have to hit Enter twice to proceed.

### PR DESCRIPTION
**Pull request by alan-agius4**
This fixes an issue where prompts in nested child processes on Windows require multiple keystrokes to proceed.

Closes #26724

### CODE REVIEW

File: packages/angular/cli/src/command-builder/architect-base-command-module.ts [hunk 1]
```diff
@@ -248,14 +247,14 @@ export abstract class ArchitectBaseCommandModule<T extends object>
       const packageToInstall = await this.getMissingTargetPackageToInstall(choices);
       if (packageToInstall) {
         // Example run: `ng add @angular-eslint/schematics`.
-        const binPath = resolve(__dirname, '../../bin/ng.js');
-        const { error } = spawnSync(process.execPath, [binPath, 'add', packageToInstall], {
-          stdio: 'inherit',
+        const AddCommadModule = (await import('../commands/add/cli')).default;
```
Comment (clydin) [inline packages/angular/cli/src/command-builder/architect-base-command-module.ts:250]:
```suggestion
        const AddCommandModule = (await import('../commands/add/cli')).default;
```
