### PR TITLE
fix(@angular-devkit/build-angular): handle `FORCE_COLOR` when stdout is not instance of `WriteStream`

### LINKED ISSUE #21732: Allow forcing colors
Hi,

I run angular CLI tasks in my own scripts that internally use `concurrently`. This setup disables colors in the angular CLI issue.

It would be great to be able to force color support via an env var, like `FORCE_COLOR`.

Related to:
* https://github.com/angular/angular-cli/issues/6478
* https://github.com/open-cli-tools/concurrently/issues/238

### PR DESCRIPTION
**Pull request by alan-agius4**
In some cases, custom implementation of stdout, don't extend `WriteStream` which causes colors not to be included in the output.

Closes #21732

### CODE REVIEW

File: packages/angular/cli/utilities/color.ts [hunk 1]
```diff
@@ -6,21 +6,50 @@
...
+ export function removeColor(text: string): string {
+   // This has been created because when colors.enabled is false unstyle doesn't work
+   // see: https://github.com/doowb/ansi-colors/blob/a4794363369d7b4d1872d248fc43a12761640d8e/index.js#L38
+   return text.replace(ansiColors.ansiRegex, '');
+ }
+ 
+ // Create a separate instance to prevent unintended global changes to the color configuration
+ // Create function is not defined in the typings. See: https://github.com/doowb/ansi-colors/pull/44
+ const colors = (ansiColors as AnsiColors & { create: () => AnsiColors }).create();
+ colors.enabled = supportsColor;
```
Comment (clydin) [inline packages/angular/cli/utilities/color.ts:52]: nit: could avoid the variable and put the call here.

**Review by clydin — APPROVED** [review]
