### PR TITLE
fix(build): override publicPath for ExtractTextPlugin

### LINKED ISSUE #4035: (publicPath) Problem with CSS url path when I add publicPath(deployUrl) in angular-cli.json
Hi,

this is my directory:

```
|-src
  |-app
  |- assets
      |-svg
         |-more.svg
  |-environments
  |-index.html
  |-styles.scss
....
```

I add  ```"deployUrl": "client/dist/", ``` to my ```angular-cli.json```.

I have following CSS in the ```styles.scss```:
```
.more {
  background: url("./assets/svg/more.svg");
  float: right;
  height: 24px;
  margin-top: 12px;
  width: 24px;
}
```
After I run ```ng build``` ,  it will translate to:
```
.more {
  background: url("client/dist/more.svg");
  float: right;
  height: 24px;
  margin-top: 12px;
  width: 24px;
}
```
When I load my application, the background SVG will be loaded from wrong path:
```http://www.xxxx.com/MyApplication/client/dist/client/dist/more.svg```

The correct Path should be:
```http://www.xxxx.com/MyApplication/client/dist/more.svg```

I can do a quick fix by overriding the ```publicPath``` setting of ```ExtractTextPlugin```
```
if (stylePaths.length > 0) {
    // load global css as css files
    cssLoaders.push(...baseRules.map(({test, loaders}) => ({
      include: stylePaths, test, loaders: ExtractTextPlugin.extract({
        remove: false,
        loader: ['css-loader', ...commonLoaders, ...loaders],
        fallbackLoader: 'style-loader',
        publicPath: ''
      })
    })));
  }
```
Does anyone have the same issue or have a better fix for this?

### PR DESCRIPTION
**Pull request by changLiuUNSW**
All our CSS assets are in a flat structure in the ```dist``` folder, therefore all relative URLs are simply ```./[asset name]```
Unfortunately, if we add ```publicPath``` via ```deployUrl```,  ```ExtractTextPlugin``` picks up the ```output.publicPath``` and rewrites assets ```url``` path with ```[publicPath]/[asset name]```
fixes #4035

### CODE REVIEW

**Comment by filipesilva** [comment]
@changLiuUNSW can you add a test for this case? I want to ensure we don't break it in the future.

A good test would be new file `extract-css.ts` in https://github.com/angular/angular-cli/tree/master/tests/e2e/tests/build/styles, with a test for `ng build` and `ng build --deploy-url`, confirming your case (via `background: url("./assets/svg/more.svg");` etc).

**Comment by changLiuUNSW** [comment]
@filipesilva 
All done !

File: tests/e2e/tests/build/styles/extract-css.ts [hunk 1]
```diff
@@ -0,0 +1,31 @@
...
+    .then(() => expectFileToMatch('dist/styles.bundle.css',
+      /div\s*{\s*background:\s*url\(more.svg\);\s*}/))
+    .then(() => ng('build', '--prod'))
+    .then(() => glob.sync('dist/styles.*.bundle.css').find(file => !!file))
+    .then((stylesBundle) => expectFileToMatch(stylesBundle,
+      /div\s*{\s*background:\s*url\(more\..*svg\)\s*}/))
+    // build with deloyUrl
+    .then(() => ng('build', '--deploy-url=client/'))
+    .then(() => expectFileToMatch('dist/styles.bundle.css',
+      /div\s*{\s*background:\s*url\(more.svg\);\s*}/))
```
Comment (filipesilva) [inline tests/e2e/tests/build/styles/extract-css.ts]: Can you confirm the path here? If I get the issue correctly, this test would pass even without your fixe since it's just checks that there is an url that has `more.svg`.

File: tests/e2e/tests/build/styles/extract-css.ts [hunk 2]
```diff
@@ -0,0 +1,31 @@
...
+    `,
+    'src/assets/more.svg': stripIndents`
+      <svg width="100" height="100">
+        <circle cx="50" cy="50" r="40" stroke="green" stroke-width="4" fill="yellow" />
+      </svg>
+    `})
+    .then(() => ng('build'))
+    .then(() => expectFileToMatch('dist/styles.bundle.css',
+      /div\s*{\s*background:\s*url\(more.svg\);\s*}/))
+    .then(() => ng('build', '--prod'))
```
Comment (filipesilva) [inline tests/e2e/tests/build/styles/extract-css.ts]: No need to test the prod builds, it shouldn't change anything regarding `--extract-css`.

File: tests/e2e/tests/build/styles/extract-css.ts [hunk 3]
```diff
@@ -0,0 +1,31 @@
...
+    .then(() => glob.sync('dist/styles.*.bundle.css').find(file => !!file))
+    .then((stylesBundle) => expectFileToMatch(stylesBundle,
+      /div\s*{\s*background:\s*url\(more\..*svg\)\s*}/))
+    // build with deloyUrl
+    .then(() => ng('build', '--deploy-url=client/'))
+    .then(() => expectFileToMatch('dist/styles.bundle.css',
+      /div\s*{\s*background:\s*url\(more.svg\);\s*}/))
+    .then(() => ng('build', '--prod', '--deploy-url=client/'))
```
Comment (filipesilva) [inline tests/e2e/tests/build/styles/extract-css.ts]: No need for prod test, see above.

File: tests/e2e/tests/build/styles/extract-css.ts [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+    `})
+    .then(() => ng('build'))
+    .then(() => expectFileToMatch('dist/styles.bundle.css',
+      /div\s*{\s*background:\s*url\(more.svg\);\s*}/))
+    .then(() => ng('build', '--prod'))
+    .then(() => glob.sync('dist/styles.*.bundle.css').find(file => !!file))
+    .then((stylesBundle) => expectFileToMatch(stylesBundle,
+      /div\s*{\s*background:\s*url\(more\..*svg\)\s*}/))
+    // build with deloyUrl
+    .then(() => ng('build', '--deploy-url=client/'))
```
Comment (filipesilva) [inline tests/e2e/tests/build/styles/extract-css.ts]: Can you force `--extract-css` here just to be more explicit to the next person editing this test?

File: tests/e2e/tests/build/styles/extract-css.ts (hunk 1 above)
Comment (changLiuUNSW) [inline tests/e2e/tests/build/styles/extract-css.ts]: Without my fix, when we add ```--deploy-url=client/```, the result is:
```
div { background: url(client/more.svg); }
```
Test will fail in this case.

File: tests/e2e/tests/build/styles/extract-css.ts (hunk 2 above)
Comment (changLiuUNSW) [inline tests/e2e/tests/build/styles/extract-css.ts]: Done

File: tests/e2e/tests/build/styles/extract-css.ts (hunk 4 above)
Comment (changLiuUNSW) [inline tests/e2e/tests/build/styles/extract-css.ts]: Done

File: tests/e2e/tests/build/styles/extract-css.ts (hunk 3 above)
Comment (changLiuUNSW) [inline tests/e2e/tests/build/styles/extract-css.ts]: Done

**Comment by filipesilva** [comment]
Thanks for this fix @changLiuUNSW!

**Comment by korve** [comment]
I'm having an issue which relates to this issue I think (paths replaced). The project was initialised with a a previous version of angular-cli

Error: No errors
    at validate (node_modules/extract-text-webpack-plugin/schema/validator.js:10:9)
    at Function.ExtractTextPlugin.extract (node_modules/extract-text-webpack-plugin/index.js:188:3)
    at node_modules/angular-cli/models/webpack-build-styles.js:79:83
    at Array.map (native)
    at Object.getWebpackStylesConfig (node_modules/angular-cli/models/webpack-build-styles.js:76:43)
    at new NgCliWebpackConfig (node_modules/angular-cli/models/webpack-config.js:44:51)
    at Class.run (node_modules/angular-cli/tasks/build-webpack.js:18:22)
    at Class.buildRun (node_modules/angular-cli/commands/build.run.js:39:22)
    at Class.run (node_modules/angular-cli/commands/build.js:38:47)
    at Class.<anonymous> (node_modules/angular-cli/ember-cli/lib/models/command.js:147:17)
    at process._tickCallback (internal/process/next_tick.js:103:7)

**Comment by intellix** [comment]
@korve please see https://github.com/angular/angular-cli/issues/4264
Temporary workaround: `npm install extract-text-webpack-plugin@2.0.0-rc.0 --save-dev`

**Comment by korve** [comment]
Thank you @intellix!
