### PR TITLE
fix(@angular/build): configure Vite CORS option

### LINKED ISSUE #29549: Access-Control-Allow-Origin header missing in dev server for assets
### Command

serve

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

@angular-devkit/build-angular 19.1.4

### Description

Starting with Angular 19.1.5, when running the development server using `ng serve`, the `Access-Control-Allow-Origin` header is no longer included in responses when accessing assets. In version 19.1.4, this header was still being sent with the value '*'.

This affects cross-origin requests to static assets served by the development server.

### Minimal Reproduction

Repository for minimal reproduction:  
[[Link to Git Repository]](https://github.com/vkennke/angular-cors)

Steps to reproduce:

1. Clone repository and install dependencies:
```bash
git clone https://github.com/vkennke/angular-cors.git
cd angular-cors
npm install
```

2. Start dev server:
```bash
ng serve
```

3. Access http://localhost:4200/assets/test.txt and check response headers

Expected behavior:
Response headers include Access-Control-Allow-Origin: *

Actual behavior:
Access-Control-Allow-Origin header is missing from response

To verify this is a regression:
1. Edit package.json to set @angular-devkit/build-angular to 19.1.4:
```json
"@angular-devkit/build-angular": "19.1.4"
```
2. Repeat steps 2-3
3. Observe that the Access-Control-Allow-Origin: * header is present

### Exception or Error

```text
No error is thrown, but the missing header prevents cross-origin requests from succeeding.
```

### Your Environment

```text
Angular CLI: 19.1.5
Node: 20.18.0
Package Manager: npm 10.8.2
OS: win32 x64

Angular: 19.1.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1901.5
@angular-devkit/build-angular   19.1.5
@angular-devkit/core            19.1.5
@angular-devkit/schematics      19.1.5
@angular/cli                    19.1.5
@schematics/angular             19.1.5
rxjs                            7.8.1
typescript                      5.7.3
zone.js                         0.15.0
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
Vite's `allowedHosts` option does not enable CORS; instead, it allows the dev server to respond to requests with a matching hostname (e.g., http://example.com/main.js). It only verifies that the request’s hostname is on the allowed list. However, this does not consider the `origin` in the case of a CORS request.

This commit updates Vite's configuration to enable CORS.

Closes #29549

### CODE REVIEW

File: packages/angular/build/src/builders/dev-server/vite-server.ts [hunk 1]
```diff
@@ -841,6 +841,8 @@ export async function setupServer(
           ? (proxy ?? {})
           : proxy,
       cors: {
+        // This will include `Access-Control-Allow-Origin: http://{{Origin}}`
```
Comment (AndreKoepke) [inline packages/angular/build/src/builders/dev-server/vite-server.ts:844]: Will the header sticked then to `http://`? Or should the comment more looks like this:

```suggestion
        // This will include `Access-Control-Allow-Origin: {{Origin}}`
```

**Review by dgp1130 — APPROVED** [review]
