### PR TITLE
fix(@angular/cli); show only changed chunks on build

### LINKED ISSUE #8621: group lazy modules in console when doing ng serve
### Versions
all

### REPRO
* create more than 50 - 100 lazyload module
* run using `ng serve`
* You will have many number of lines in your console see example: https://gist.github.com/istiti/6b73e021896021048f6f1f9b372da5f9 

### Observed behavior
I think this is a very ergonomics problem to see so many output  in console which have scroll: 
And in many  IDE your console takes often 25% of the height 
image

In fact problem will come when you have an error which not break your "ng serve" and you edit many times a file , the cli rebuild many times and you have sometimes error at the begining of you console, you can't see it quickly, you need scroll the console to read it just because of numberous lines  `chunk {name.module} name.module.chunk.js () 58.7 kB  [rendered]`

You can see error here :
cliscrolltoseeerror

### Desired behavior
I think  CLI should NOT show these NOT important informations (on big project with many lazy module) because your console isn't clean and not ergonomics, not easy to use, to see if error happends.

I think these lazymodule chunk  should still be here only with `--verbose` flag. 
And if you run `ng s` just output the minimum informations maxmimum of 7 or 10 lines and maybe regroup lazymodule in one lines, something like : 

### RESULT SHOULD BE

grouping

What you think ?

### PR DESCRIPTION
**Pull request by filipesilva**
For projects with a lot of lazy modules the rebuild messages can easily fill the whole console window.

This PR shows only chunks that changed instead of showing all chunks.

Before:
```
$ ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-12-14T14:56:13.707Z
Hash: 7490b2942c48ffcf0f0f
Time: 7317ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 725 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 35 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 6.45 MB [initial] [rendered]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2017-12-14T14:56:17.054Z
Hash: dbb03cc0994e8bf69e76
Time: 310ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry]
chunk {main} main.bundle.js (main) 725 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 kB [initial]
chunk {styles} styles.bundle.js (styles) 35 kB [initial]
chunk {vendor} vendor.bundle.js (vendor) 6.45 MB [initial]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2017-12-14T14:56:20.290Z
Hash: fe53cbcd529dd2508cfc
Time: 267ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry]
chunk {main} main.bundle.js (main) 725 kB [initial]
chunk {polyfills} polyfills.bundle.js (polyfills) 577 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 35 kB [initial]
chunk {vendor} vendor.bundle.js (vendor) 6.45 MB [initial]

webpack: Compiled successfully.
```

After:
```
$ ng serve** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2018-01-03T12:22:56.414Z
Hash: 38ba8d730f1803e5322f
Time: 8548ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 723 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 576 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 43 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 6.47 MB [initial] [rendered]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2018-01-03T12:23:00.593Z • Hash: 9d8c8a72035d0d707df3 • Time: 259ms
4 unchanged chunks
chunk {main} main.bundle.js (main) 723 kB [initial] [rendered]

webpack: Compiled successfully.
webpack: Compiling...
Date: 2018-01-03T12:23:04.151Z • Hash: a95ea7bcfe80f0e4d747 • Time: 124ms
4 unchanged chunks
chunk {main} main.bundle.js (main) 723 kB [initial] [rendered]

webpack: Compiled successfully.
```

Fix #8621

### CODE REVIEW

File: packages/@angular/cli/utilities/stats.ts [hunk 1]
```diff
@@ -41,7 +39,18 @@ export function statsToString(json: any, statsConfig: any) {
         .join('');
 
       return `chunk {${y(chunk.id)}} ${g(files)}${names}${size} ${initial}${flags}`;
-    }).join('\n')}
+    }).join('\n');
+
+  const unchangedChunkNumber = json.chunks.filter((chunk: any) => !chunk.rendered).length;
```
Comment (ghetolay) [inline packages/@angular/cli/utilities/stats.ts]: `const unchangedChunkNumber = json.chunks.length - changedChunksStats.length;`

File: packages/@angular/cli/utilities/stats.ts [hunk 2]
```diff
@@ -41,7 +39,18 @@ export function statsToString(json: any, statsConfig: any) {
...
+  const unchangedChunksMessage = unchangedChunkNumber > 0
+    ? `${unchangedChunkNumber} unchanged chunks`
+    : '';
+
+  return rs(stripIndents`
+    Date: ${w(new Date().toISOString())}
+    Hash: ${w(json.hash)}
+    Time: ${w('' + json.time)}ms
+    ${changedChunksStats ? changedChunksStats + '\n' : ''}${unchangedChunksMessage}
```
Comment (ghetolay) [inline packages/@angular/cli/utilities/stats.ts]: Doesn't seem possible for `changedChunksStats` to be falsy it's always an array.

File: packages/@angular/cli/utilities/stats.ts (hunk 1 above)
Comment (ghetolay) [reply packages/@angular/cli/utilities/stats.ts]: nvm didn't see the `join`. Could still keep the resulting array and join later.

File: packages/@angular/cli/utilities/stats.ts (hunk 2 above)
Comment (istiti) [inline packages/@angular/cli/utilities/stats.ts]: Thanks to this pullrequest. @filipesilva  What you think to reorder console & get little bit more concis (because in dev mode, imo, short is better)
Before: 
image

After:
image

Comment (intellix) [reply packages/@angular/cli/utilities/stats.ts]: I think this looks really good :)

File: packages/@angular/cli/utilities/stats.ts (hunk 1 above)
Comment (filipesilva) [reply packages/@angular/cli/utilities/stats.ts]: That's a good idea, I'll do that.

File: packages/@angular/cli/utilities/stats.ts (hunk 2 above)
Comment (filipesilva) [reply packages/@angular/cli/utilities/stats.ts]: I like the shorter as well.

Comment (filipesilva) [reply packages/@angular/cli/utilities/stats.ts]: I've updated the first message to show the shorter output in the after snippet.

File: packages/@angular/cli/utilities/stats.ts [hunk 3]
```diff
@@ -41,8 +39,24 @@ export function statsToString(json: any, statsConfig: any) {
...
       return `chunk {${y(chunk.id)}} ${g(files)}${names}${size} ${initial}${flags}`;
-    }).join('\n')}
-    `);
+    });
+
+  const unchangedChunkNumber = json.chunks.length - changedChunksStats.length;
+
+  if (unchangedChunkNumber > 0) {
+    return rs(stripIndents`
+      Date: ${w(new Date().toISOString())} • Hash: ${w(json.hash)} • Time: ${w('' + json.time)}ms
```
Comment (TobiasSchulte) [inline packages/@angular/cli/utilities/stats.ts]: This output leads to two beep sounds on windows systems due to the two '•' characters, see https://blogs.msdn.microsoft.com/oldnewthing/20070104-00/?p=28513

Comment (filipesilva) [reply packages/@angular/cli/utilities/stats.ts]: Let's use a fancy character they said. What could go wrong they said.

😞

Comment (filipesilva) [reply packages/@angular/cli/utilities/stats.ts]: @TobiasSchulte does this happen on your system? I tried on mine (Windows 10, basic `cmd`) and I didn't get a beep.

Comment (TobiasSchulte) [reply packages/@angular/cli/utilities/stats.ts]: @filipesilva Yes, it happens on my machine and on the machine of a colleague. Both are Windows 7 systems, it happens in a normal cmd, but not for example in the vscode integrated terminal.

Comment (filipesilva) [reply packages/@angular/cli/utilities/stats.ts]: Would you be interested in making a PR that changes `•` to `-`?

Comment (TobiasSchulte) [reply packages/@angular/cli/utilities/stats.ts]: @filipesilva Pull request is created

Comment (tachycardian) [reply packages/@angular/cli/utilities/stats.ts]: @filipesilva  looks like a global bug in Win7 x64 atm (both Professional and Home Premium versions checked yet) - ```•``` bullet characters are causing aroung +-3 mins in recompiling process due to 'beep-loop' during any 'ng serve' operations + freezing cmd ;)

Comment (filipesilva) [reply packages/@angular/cli/utilities/stats.ts]: @TobiasSchulte we have already made that change in https://github.com/angular/angular-cli/pull/9336
