### PR TITLE
fix(generate): fix module component path if module is created in child folder

### LINKED ISSUE #3063: Invalid path when generating a module inside a sub directory
> Please provide us with the following information:
> ---------------------------------------------------------------

Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
angular-cli: 1.0.0-beta.19-3
node: 6.3.0
os: linux x64

N/A

ng g module shared/some-feature
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
installing module
  create src/app/shared/some-feature/some-feature.module.ts
installing component
Invalid path: "/home/vagrant/workspace/ss-angular-cli-starter/src/app/some-feature"" is not a valid path.

### Mention any other details that might be useful.

I have tried generating the module with different scenarios in different folder names but the issue persists.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### PR DESCRIPTION
**Pull request by Meligy**
fixes #3063

### CODE REVIEW

File: packages/angular-cli/blueprints/module/index.js [hunk 1]
```diff
@@ -58,7 +58,9 @@ module.exports = {
   },
 
   afterInstall: function (options) {
-    options.entity.name = path.join(this.dasherizedModuleName, this.dasherizedModuleName);
+    var componentPath = path.join(this.generatePath, this.dasherizedModuleName);
```
Comment (Brocco) [inline packages/angular-cli/blueprints/module/index.js]: If you're only going to have `this.dasherizedModuleName` once, then you need to turn `options.flat` to false. The default for components is that they're in their own directory. I'd suggest using `options.flat = false`. And once you make that change you will also need to update your tests.

Comment (Meligy) [inline packages/angular-cli/blueprints/module/index.js]: @Brocco the `dasherizedModuleName` is already included in `generatePath`, so it was still there twice.

However, I still changed it to use `options.flat = false;`, without using `this.dasherizedModuleName`.

The outcome is the same though. Not sure why I need to change the test.
