### PR TITLE
fix(@angular-devkit/build-angular): fixed afterOptimizeChunkAssets is deprecated in webpack 5

### LINKED ISSUE #18895: Webpack 5 warning
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

```
(node:60756) [DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:60756) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
Warning: Circular dependency detected:
src/styles.scss -> src/styles.scss
```

## 🔬 Minimal Reproduction

```
yarn global add @angular/cli@next
ng new test-webpack5 
cd test-webpack5 
add `"resolutions": { "webpack":"5.0.0-rc.0" }` in package.json
yarn install
yarn start
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-next.3
@angular-devkit/build-angular   0.1100.0-next.3
@angular-devkit/core            11.0.0-next.3
@angular-devkit/schematics      11.0.0-next.3
@schematics/angular             11.0.0-next.3
@schematics/update              0.1100.0-next.3
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by valorkin**
Closes #18895

fixes:
- 229 deprecation warnings in tests and in ng prod build
`[DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)`
- 90 test errors like `Error: .../app.component.less exceeded maximum budget. Budget 1 bytes was not met by 82 bytes with a total of 83 bytes. ' to match 'ERROR.+app.component.less'.`

### CODE REVIEW

**Comment by alan-agius4** [comment]
Can you add `Closes #18895`?

File: packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts [hunk 1]
```diff
@@ -20,16 +21,17 @@ const PLUGIN_NAME = 'AnyComponentStyleBudgetChecker';
...
   private readonly budgets: Budget[];
+
   constructor(budgets: Budget[]) {
     this.budgets = budgets.filter((budget) => budget.type === Type.AnyComponentStyle);
   }
 
   apply(compiler: Compiler) {
-    compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
-      compilation.hooks.afterOptimizeChunkAssets.tap(PLUGIN_NAME, () => {
+    compiler.hooks.compilation.tap(PLUGIN_NAME, (_compilation) => {
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:30]: Can you rename this to something else? Typically parameters suffixed with `_` signifies that the parameter is unused.

File: packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts [hunk 2]
```diff
@@ -42,30 +44,50 @@ export class AnyComponentStyleBudgetChecker {
...
-      });
+      };
+
+      if (isWebpackFiveOrHigher()) {
+        // question to @alan-agius4 :
+        // there are will be 5 PRs with very similar changes, should I add comments regarding source of info like below:
+        // webpack 5 migration "guide"
+        // https://github.com/webpack/webpack/blob/07fc554bef5930f8577f91c91a8b81791fc29746/lib/Compilation.js#L535-L539
+
+        // question to @alan-agius4 :
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:78]: I think for now, we can leave as is. In future we may want to bring this up with the Webpack team.

File: packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts [hunk 3]
```diff
@@ -42,30 +44,50 @@ export class AnyComponentStyleBudgetChecker {
...
           }
         }
-      });
+      };
+
+      if (isWebpackFiveOrHigher()) {
+        // question to @alan-agius4 :
+        // there are will be 5 PRs with very similar changes, should I add comments regarding source of info like below:
+        // webpack 5 migration "guide"
+        // https://github.com/webpack/webpack/blob/07fc554bef5930f8577f91c91a8b81791fc29746/lib/Compilation.js#L535-L539
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:76]: A comment never hurt anyone! So I am good with adding a link to the source code.

Comment (valorkin) [reply packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:76]: @alan-agius4  awesome, thanks

File: packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts (hunk 2 above)
Comment (valorkin) [reply packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:78]: @alan-agius4 should I leave a comment about `tapable` here or remove? 
I was planning to do some commits in webpack too, in order to improve typings

File: packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts [hunk 4]
```diff
@@ -7,10 +7,11 @@
  */
 
 import * as path from 'path';
-import { Compiler } from 'webpack';
+import { Compiler, compilation } from 'webpack';
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:10]: You don't need to use the instance of Compilation.

```suggestion
import { Compiler, Compilation } from 'webpack';
```

File: packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts (hunk 1 above)
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:30]:
```suggestion
    compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
```

File: packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts (hunk 4 above)
Comment (valorkin) [reply packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:10]: webpack4 doesn't have exported member `Compilation`

File: packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts (hunk 1 above)
Comment (valorkin) [reply packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:30]: `compilationInstance` would be good?

File: packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts (hunk 2 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:78]: Thinking again we can actually address this error, since it's just a linting/missing Bazel configuration. I'll look into this tomorrow.

Comment (valorkin) [reply packages/angular_devkit/build_angular/src/webpack/plugins/any-component-style-budget-checker.ts:78]: awesome, thanks

**Review by alan-agius4 — APPROVED** [review]
