### PR TITLE
fix(@angular-devkit/build-angular): several fixes to assets and files writes in browser-esbuild builder

### LINKED ISSUE #26021: browser-esbuild: An unhandled exception occurred: EPERM: operation not permitted, copyfile
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

Hi. browser-esbuild gives up with this error:

```
An unhandled exception occurred: EPERM: operation not permitted, copyfile 'C:\Users\123\WebstormProjects\123\src\manifest.json' -> 'C:\Users\123\WebstormProjects\123\dist\123'
See "C:\Users\ikpoc\AppData\Local\Temp\ng-G3vwG2\angular-errors.log" for further details.
```

Error log is the same. Tried running with admin privileges with same result.

### Minimal Reproduction

ng build

### Exception or Error

_No response_

### Your Environment

```text
Angular CLI: 17.0.0-next.8
Node: 18.18.1
Package Manager: npm 9.8.1
OS: win32 x64

Angular: 17.0.0-next.8
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker, ssr

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-next.8
@angular-devkit/build-angular   17.0.0-next.8
@angular-devkit/core            17.0.0-next.8
@angular-devkit/schematics      17.0.0-next.8
@angular/cdk                    17.0.0-next.6
@angular/material               17.0.0-next.6
@schematics/angular             16.2.5
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit ports https://github.com/angular/angular-cli/pull/26016 to the esbuilder and also fixes an issue where assets were being outputted in the wrong directory.

Closes #26021

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts [hunk 1]
```diff
@@ -74,36 +75,58 @@ function normalizeOptions(options: BrowserBuilderOptions): ApplicationBuilderOpt
...
+      await fs.copyFile(
+        asset.source,
+        path.join(outputPath, asset.destination),
+        fsConstants.COPYFILE_FICLONE,
+      );
+    });
+  }
+}
+
+const MAX_CONCURRENT_WRITES = 64;
```
Comment (zip-fa) [inline packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts:115]: Maybe give option to increase this value with `--max-concurrent-writes=100`?

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/builders/browser-esbuild/index.ts:115]: Adding an option is not something that we plan to do. Instead we opted for a sensible default.

**Review by clydin — APPROVED** [review]
