### PR TITLE
Multiple asset fixes for Vite and the application builder in watch mode

### LINKED ISSUE #26141: Vite is not reloading on asset only changes
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

esbuild is not detecting style changes when importing style file inside index.html

This issue does not happen in non esbuild builder

### Minimal Reproduction

[ng17rc1.zip](https://github.com/angular/angular-cli/files/13176576/ng17rc1.zip)

- unzip above zip file and run npm install
- check UI
- now go to `src\assets\ruf-default.css` and update color property of header element to some other color
- check if styles are reflecting on UI

### Exception or Error

_No response_

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 17.0.0-rc.1
Node: 18.18.2
Package Manager: npm 8.19.3
OS: win32 x64

Angular: 17.0.0-rc.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.1
@angular-devkit/build-angular   17.0.0-rc.1
@angular-devkit/core            17.0.0-rc.1
@angular-devkit/schematics      17.0.0-rc.1
@schematics/angular             17.0.0-rc.1
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
**fix(@angular/build): trigger browser reload on asset changes with Vite dev server**

Ensures the Vite-based development server automatically reloads the browser when asset files are modified.

Closes #26141

**fix(@angular/build): remove deleted assets from output during watch mode**

This commit ensures that assets deleted from the source are also removed from the output directory while in watch mode. Previously, deleted assets could persist in the output folder, potentially causing inconsistencies or outdated files to be served. This fix improves the accuracy of the build output by maintaining synchronization between the source and the output directory during development.

### CODE REVIEW

File: packages/angular/build/src/builders/dev-server/vite-server.ts [hunk 1]
```diff
@@ -471,15 +480,26 @@ export async function* serveWithVite(
...
+  assetFiles: Map<string, OutputAssetRecord>,
   server: ViteDevServer,
   serverOptions: NormalizedDevServerOptions,
   logger: BuilderContext['logger'],
   componentStyles: Map<string, ComponentStyleRecord>,
 ): Promise<void> {
   const updatedFiles: string[] = [];
-  let destroyAngularServerAppCalled = false;
+
+  // Invadate any updated asset
```
Comment (clydin) [inline packages/angular/build/src/builders/dev-server/vite-server.ts:491]:
```suggestion
  // Invalidate any updated asset
```

**Review by clydin — APPROVED** [review]

**Comment by alan-agius4** [comment]
The changes were merged into the following branches: main, 19.1.x
