### PR TITLE
fix(@schematics/schematics): run install step with sample schematics

### LINKED ISSUE #17425: Run npm i with the Sample Schematics Command
Running:

```
schematics schematic --name demo
```

Creates the demo, but we still need to run `npm i`manually on the project to get the deps.

### PR DESCRIPTION
**Pull request by Ayudh**
Closes #17425

### CODE REVIEW

File: packages/schematics/schematics/schematic/factory.ts [hunk 1]
```diff
@@ -8,31 +8,36 @@
...
   Rule,
+  SchematicContext,
+  Tree,
   apply,
   mergeWith,
   move,
-  partitionApplyMerge,
-  template,
-  url,
+  partitionApplyMerge, template, url,
```
Comment (alan-agius4) [inline packages/schematics/schematics/schematic/factory.ts:16]: Nit: can we keep these in a single line please? Thanks

**Review by alan-agius4 — APPROVED** [review]
LGTM just on small thing

File: packages/schematics/schematics/schematic/factory.ts (hunk 1 above)
Comment (Ayudh) [reply packages/schematics/schematics/schematic/factory.ts]: Yes. Updated.
