### PR TITLE
fix(tests): link package in e2e tests

### LINKED ISSUE #194: e2e workflow spec should use a linked angular cli
Currently the e2e tests are doing an npm install to grab the version of angular-cli to use for test execution, it should be changed to use npm link to utilize the local version of itself to test functionality.

The line in question is:
sh.exec('npm i angular-cli -g -C ' + process.cwd(), { silent: true });

### PR DESCRIPTION
**Pull request by filipesilva**
Close #194

This issue proved to be harder to fix than it initially looked like.

Running `npm link` did not seem to work, due to `npm` itself being local as per the `npm link npm` command in `.travis.yml`.

Removing `npm link npm` caused the tests to file in a [spectacular fashion](https://travis-ci.org/angular/angular-cli/builds/108998425). 

`npm4` builds fail because `ng install` tests report a missing package - `npm` itself. This seems to have been what originated the inclusion of `npm link npm` in `.travis.yml`. Also related, https://github.com/angular/angular-cli/issues/185#issuecomment-182635747.

`npm5` builds fail in a much more confusing way. 

Linking `angular-cli` shows a couple of warnings about npm packages that aren't part of `angular-cli` nor are present in npm4 builds:

```
npm WARN prefer global marked@0.3.5 should be installed with -g
npm WARN prefer global npm@2.14.10 should be installed with -g
```

There is also a weird stray error during the `ng new` test, that seems to be responsible for for `ng new` failing:

```
Error: ENOENT: no such file or directory, open '/home/travis/build/angular/angular-cli/tmp/foo/package.json'
    at Error (native)
```

The e2e build tests fail with missing core packages that should have been installed in in the initial `ng new test-project` (that seems to fail):

```
  app.ts (1, 25): Cannot find module 'angular2/platform/browser'.
  app.ts (3, 32): Cannot find module 'angular2/router'.
  app/test-project.spec.ts (1, 65): Cannot find module 'angular2/testing'.
  app/test-project.ts (1, 25): Cannot find module 'angular2/core'.
  app/test-project.ts (2, 46): Cannot find module 'angular2/router'.
```

I tried removing the acceptance tests for `ng install` and `ng uninstall` and the [resulting build](https://travis-ci.org/angular/angular-cli/builds/109000126) seems to pass every test, correctly linking the existing `angular-cli` and succeding and bulding the generated project, typings included.

This seems to indicate that either the `ng install` and `ng uninstall` acceptance tests or the commands themselves break subsequent tests.

I found two references to the instability of using the `npm` module programatically: [one on stack overflow](http://stackoverflow.com/questions/15957529/can-i-install-a-npm-package-from-javascript-running-in-node-js) and [one on ember-cli](https://github.com/ember-cli/ember-cli/blob/master/lib/utilities/npm.js#L10-L12).

This prompted me to change the `ng install` and `ng uninstall` code to use `shelljs` to run `npm install/uninstall` commands instead using npm programatically as before. That seems to have fixed the weird interactions between their acceptance tests and the e2e tests.

/cc @hansl @jkuri @Brocco

### CODE REVIEW

**Comment by Brocco** [comment]
lgtm

File: addon/ng2/tasks/lib-install.js [hunk 1]
```diff
@@ -18,50 +18,49 @@ module.exports = Task.extend({
...
-          var pkg = this.packages[0];
-          
-          if (existsSync(path.resolve(process.cwd(), 'src', 'app.ts'))) {
-            var entryPoint = path.resolve(process.cwd(), 'src', 'app.ts');
-            var packageData = this.parseFile(pkg);
-            this.importInBootstrap(entryPoint, pkg, packageData);
-          }
+    var npmCommand = 'npm install ' + this.packages.join(' ') + this.npmOptions;
+
+    return new Promise(function (resolve, reject){
```
Comment (hansl) [inline addon/ng2/tasks/lib-install.js]: This is a pattern that we will do a lot and I'd like to avoid the copy and paste. Could you move the sh.exec and promise into a helper function that would be imported everywhere?
