### PR TITLE
fix(@angular/build): support template updates that also trigger global stylesheet changes

### LINKED ISSUE #29440: Angular 19.1.3 Component HMR + TailwindCSS Problem - Not HMR but destructive refresh
### Command

serve

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When developing with HMR enabled, changing a TailwindCSS class in the template would trigger a destructive reload, not HMR. Changing styles in component TS files or commenting out / adding template chunks seems to work fine. 

https://github.com/user-attachments/assets/a6af8966-1553-4c6f-9446-7acc31620369

### Minimal Reproduction

A small (probably not minimal) reproduction: https://github.com/HymanZHAN/todo-mvc-angular

### Exception or Error

```text

```

### Your Environment

```text
> ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 19.1.3
Node: 22.11.0
Package Manager: pnpm 9.15.4
OS: linux x64

Angular: 19.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1901.3
@angular-devkit/build-angular   19.1.3
@angular-devkit/core            19.1.3
@angular-devkit/schematics      19.1.3
@angular/cli                    19.1.3
@schematics/angular             19.1.3
rxjs                            7.8.1
typescript                      5.6.3
zone.js                         0.15.0
```

### Anything else relevant?

The todo app is zoneless.

### PR DESCRIPTION
**Pull request by clydin**
In some cases a change to a component template may cause changes to other aspects of the application. Tailwind, for instance, may cause changes to the global stylesheets when class usage is changed in a template. To support hot module replacement of the component template in these cases, stylesheet changes are now analyzed and separated during the update process. This allows both a hot update of the template and the global stylesheet during the rebuild instead of the previously required full page reload.

Closes #29440

### CODE REVIEW

File: packages/angular/build/src/builders/application/build-action.ts [hunk 1]
```diff
@@ -369,6 +375,21 @@ function* emitOutputResults(
   // If there are template updates and the incremental update was background only, a component
   // update is possible.
   if (hasTemplateUpdates && incrementalResult.background) {
+    // Template changes may be accompanied by stylesheet changes and these should also be updated hot when possible.
+    if (hasCssUpdates) {
```
Comment (alan-agius4) [inline packages/angular/build/src/builders/application/build-action.ts:379]: NIT: Grouping the updated map files with this incremental update will make the debugging process less awkward.

**Comment by alan-agius4** [comment]
The changes were merged into the following branches: main, 19.1.x
