### PR TITLE
fix(@angular/ssr): ensure server-side navigation triggers a redirect

### LINKED ISSUE #31482: Server side router navigation with changes to query parameters not sending a redirect response
### Command

run

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When pushing a new navigation on server side only with:
```ts
await this.router.navigate([], {
  queryParams: {filter: 'test'},
  queryParamsHandling: 'merge', // remove to replace all query params by provided
  relativeTo: route
});
```
This does not result in a redirect response being sent to the browser, just a regular 200.

It seems like, in the [check for whether the url change](https://github.com/angular/angular-cli/blob/main/packages/angular/ssr/src/utils/ng.ts#L113), the query parameters on finalUrl and initialUrl of the lastSuccessfulNavigation object are the same, which they shouldn't!

### Minimal Reproduction

Reproduction code: https://github.com/WizzardMaker/angular-ssr-navigate-bug

Steps to reproduce in the project:
1. Navigate to e.g. ´/?filter=a´
2. See that server response is of status code 200, not any other redirect code

In short what the project does:
A route component triggers a router navigation in it's constructor like this:
```ts
if(isPlatformBrowser(inject(PLATFORM_ID))) return;

this.pendingTasks.run(async () => {
  await this.router.navigate([], {
    queryParams: {filter: 'test'},
    queryParamsHandling: 'merge', // remove to replace all query params by provided
    relativeTo: route
  })
})
```

### Exception or Error

```text

```

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    


Angular CLI: 20.3.5
Node: 24.9.0
Package Manager: npm 11.6.0
OS: darwin arm64
    

Angular: 20.3.4
... common, compiler, compiler-cli, core, forms
... platform-browser, platform-server, router

Package                      Version
------------------------------------
@angular-devkit/architect    0.2003.5
@angular-devkit/core         20.3.5
@angular-devkit/schematics   20.3.5
@angular/build               20.3.5
@angular/cli                 20.3.5
@angular/ssr                 20.3.5
@schematics/angular          20.3.5
rxjs                         7.8.2
typescript                   5.9.3
```

### Anything else relevant?

This happens only on server side rendering on a standard node server and on ng serve. I don't quite know whether this behaviour changed between versions

### PR DESCRIPTION
**Pull request by alan-agius4**
When a navigation occurs on the server-side, such as using `router.navigate`, and the final URL is different from the initial URL that was requested, the server should respond with a redirect.

Previously, the initial URL was being read from `router.lastSuccessfulNavigation.initialUrl`, which could be incorrect in scenarios involving server-side navigations, causing the comparison with the final URL to fail and preventing the redirect.

This change ensures that the initial URL requested by the browser is used for the comparison, correctly triggering a redirect when necessary.

Closes #31482

### CODE REVIEW

File: packages/angular/ssr/test/app_spec.ts [hunk 1]
```diff
@@ -26,14 +27,32 @@ describe('AngularServerApp', () => {
...
+    @Component({
+      selector: 'app-redirect',
+    })
+    class RedirectComponent {
+      constructor() {
+        const router = inject(Router);
+        const pendingTasks = inject(PendingTasks);
+
+        pendingTasks.run(() =>
+          router.navigate([], {
```
Comment (atscott) [inline packages/angular/ssr/test/app_spec.ts]: Can we maybe do this in a guard instead? As discussed, I don’t love that this causes the navigation to not complete successfully.

File: packages/angular/ssr/test/app_spec.ts [hunk 2]
```diff
@@ -26,14 +27,32 @@ describe('AngularServerApp', () => {
...
 
+    @Component({
+      selector: 'app-redirect',
+    })
+    class RedirectComponent {
+      constructor() {
+        const router = inject(Router);
+        const pendingTasks = inject(PendingTasks);
+
+        pendingTasks.run(() =>
```
Comment (atscott) [inline packages/angular/ssr/test/app_spec.ts]: Nit: you don’t need the pending task. Router navigations are already tracked internally.

File: packages/angular/ssr/test/app_spec.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/angular/ssr/test/app_spec.ts]: I tried to keep this spec case as similar to the reported issue as possible.

Comment (atscott) [reply packages/angular/ssr/test/app_spec.ts]: Yea, I get that. Can you double check that this actually does also happen (as in it doesn’t work as a redirect) for navigations in guards? By far, that’s more common so at the very least, you’d want to cover that case too. This test is good on its own, it’s just that I wish it already worked correctly with the old code and didn’t need this PR

Comment (alan-agius4) [reply packages/angular/ssr/test/app_spec.ts]: Without this change, within a guard the navigation change does not work as a redirect.

**Review by atscott — APPROVED** [review]
