### PR TITLE
fix(@angular-devkit/build-angular): styles CSS files not available in unit tests

### LINKED ISSUE #21054: Styles CSS files not available in unit tests
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Not sure.

### Description

In angular.io, we have the following `build > styles`:

```json
{
  "inject": false,
  "input": "src/styles/custom-themes/dark-theme.scss",
  "bundleName": "dark-theme"
},
{
  "inject": false,
  "input": "src/styles/custom-themes/light-theme.scss",
  "bundleName": "light-theme"
}
```

However, adding the same styles in `test > styles` (see [PR 42259][2]) does not make them available during unit tests, resulting in many warnings (which mess up the output):

```
WARN [web-server]: 404: /_karma_webpack_/light-theme.css
```

See the problem in action [on CI][3].

## 🔬 Minimal Reproduction

- Check out PR #42259.
- `cd aio && yarn && yarn test`

## 🔥 Exception or Error

```
WARN [web-server]: 404: /_karma_webpack_/light-theme.css
...
WARN [web-server]: 404: /_karma_webpack_/dark-theme.css
```

## 🌍 Your Environment

```
Angular CLI: 12.0.2
Node: 14.17.0
Package Manager: yarn 1.22.10
OS: win32 x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, material, platform-browser
... platform-browser-dynamic, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.2
@schematics/angular             12.0.2
rxjs                            6.6.7
typescript                      4.3.2
```

[1]: https://github.com/angular/angular/blob/30059173f4dc8d527912e2fc0e51288812791899/aio/angular.json#L53-L62
[2]: https://github.com/angular/angular/pull/42259/files#diff-b2293165ddd5165cbb9b68bedbee7e8693cc410a0a4e65ad6b0dfb748451cb07R164-R174
[3]: https://circleci.com/gh/angular/angular/1003683

### PR DESCRIPTION
**Pull request by alan-agius4**
With this change we force styles to be extracted in css files during unit tests.

Closes #21054

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/karma/tests/options/code-coverage_spec.ts [hunk 1]
```diff
@@ -0,0 +1,160 @@
...
+          }
+        `,
+      );
+
+      harness.useTarget('test', {
+        ...BASE_OPTIONS,
+        codeCoverage: true,
+      });
+
+      const result = await harness.execute();
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/karma/tests/options/code-coverage_spec.ts:144]: nit: unneeded `await`

**Review by clydin — APPROVED** [review]
