### PR TITLE
fix(generate): ignore duplicate component symbol in module declarations

### LINKED ISSUE #4323: ng generate adds component to module even if the generated component is identical
> Please provide us with the following information:
> ---------------------------------------------------------------

macOS Sierra

```
angular-cli: 1.0.0-beta.28.3
node: 7.2.0
os: darwin x64
@angular/common: 2.4.5
@angular/compiler: 2.4.5
@angular/core: 2.4.5
@angular/forms: 2.4.5
@angular/http: 2.4.5
@angular/platform-browser: 2.4.5
@angular/platform-browser-dynamic: 2.4.5
@angular/router: 3.4.5
@angular/compiler-cli: 2.4.5
```

Create an app with `ng new`

Follow these steps:

```
$ ng g m events
installing module
  create src/app/events/events.module.ts

$ ng g c events/list
installing component
  create src/app/events/list/list.component.css
  create src/app/events/list/list.component.html
  create src/app/events/list/list.component.spec.ts
  create src/app/events/list/list.component.ts
  update src/app/events/events.module.ts

$ ng g c events/list
installing component
  identical src/app/events/list/list.component.css
  identical src/app/events/list/list.component.html
  identical src/app/events/list/list.component.spec.ts
  identical src/app/events/list/list.component.ts
  update src/app/events/events.module.ts

$ cat src/app/events/events.module.ts
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ListComponent } from './list/list.component';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [ListComponent, ListComponent]
})
export class EventsModule { }
```

Because the last `generate` command generates all identical files I don't expect the update of the module to happen, as this will leave it with the same component being declared twice.

No failures.

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

### PR DESCRIPTION
**Pull request by delasteve**
`ng g c X` will no longer insert the component symbol in the NgModule's declaration array should it already exist.

Closes #4323

// cc @beeman, @Meligy

### CODE REVIEW

File: packages/@angular/cli/lib/ast-tools/ast-utils.ts [hunk 1]
```diff
@@ -200,10 +200,18 @@ function _addSymbolToNgModuleMetadata(ngModulePath: string, metadataField: strin
...
       }
+
+      if (Array.isArray(node)) {
+        const nodeArray = node as any as Array<ts.Node>;
+        const symbolsArray = nodeArray.map(node => node.getText());
+        if (symbolsArray.includes(symbolName)) {
+          return new NoopChange();
+        }
+      }
+
```
Comment (hansl) [inline packages/@angular/cli/lib/ast-tools/ast-utils.ts]: Merge these 2 `if`?

File: packages/@angular/cli/lib/ast-tools/ast-utils.ts [hunk 2]
```diff
@@ -254,7 +262,7 @@ function _addSymbolToNgModuleMetadata(ngModulePath: string, metadataField: strin
 * into NgModule declarations. It also imports the component.
 */
 export function addDeclarationToModule(modulePath: string, classifiedName: string,
-                                       importPath: string): Promise<Change> {
+  importPath: string): Promise<Change> {
```
Comment (hansl) [inline packages/@angular/cli/lib/ast-tools/ast-utils.ts]: Revert these.

File: packages/@angular/cli/blueprints/component/index.ts [hunk 3]
```diff
@@ -54,13 +54,13 @@ export default Blueprint.extend({
 
     let defaultPrefix = '';
     if (this.project.ngConfig &&
-        this.project.ngConfig.apps[0] &&
-        this.project.ngConfig.apps[0].prefix) {
+      this.project.ngConfig.apps[0] &&
```
Comment (hansl) [inline packages/@angular/cli/blueprints/component/index.ts]: Revert these whitespace changes.

**Comment by delasteve** [comment]
@hansl fixed :)

**Comment by filipesilva** [comment]
Seems like the changes @hansl asked for were made so marking for merge.
