### PR TITLE
fix(@angular-devkit/build-angular): identify plugin provided as string

### LINKED ISSUE #19571: After Upgrading a Workspace Containing Multiple Projects to Angular 11, Karma Refuses to Run
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 
Yes, the previous version in which this bug was not present was: 10.0

### Description

I recently upgraded a multi-project workspace from Angular 10 to 11. I ran into some issues, which were resolved using the solution provided by a member of the Angular CLI team here: https://github.com/angular/angular/issues/39953. However, even though I can now build my app and its projects, when I try to run the tests, I get the following error:

_ERROR [karma-server]: Server start failed on port 9876: TypeError: Cannot use 'in' operator to search for 'reporter:coverage' in karma-spec-reporter_

I'm not sure why this is occurring, as it does not appear any of the Karma packages were changed, and my Karma configuration files have not changed either. The tests _will_ run if I disable code coverage reports, but I need those. I've also tried removing my codeCoverageExclusions, to no effect.

## 🔬 Minimal Reproduction

I apologize that I'm unable to share the code behind this, but the scenario is:

- Workspace containing 2 library projects and a main app
- Problematic upgrade as described in https://github.com/angular/angular/issues/39953
- Running _ng test_ or _ng test --project=(project)_ fails with the error mentioned above
- Running _ng test_ with _--code-coverage=false_, or _codeCoverage=false_ in _angular.json_ works as expected, no error
- I do not have this problem on a smaller, simpler app which just contains the main app in the workspace

## 🔥 Exception or Error
<pre><code>
ERROR [karma-server]: Server start failed on port 9876: TypeError: Cannot use 'in' operator to search for 'reporter:coverage' in karma-spec-reporter

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.0.3
Node: 12.14.1
OS: win32 x64

Angular: 11.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.3
@angular-devkit/build-angular   0.1100.3
@angular-devkit/core            11.0.3
@angular-devkit/schematics      11.0.3
@angular/cdk                    8.2.3
@angular/http                   7.2.16
@schematics/angular             11.0.3
@schematics/update              0.1100.3
ng-packagr                      11.0.3
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**
A zip file containing my angular.json, and the karma.conf.js for my main app (but this has not changed), is attached.
[KarmaNoLikey.zip](https://github.com/angular/angular/files/5661311/KarmaNoLikey.zip)

### PR DESCRIPTION
**Pull request by kyliau**
Karma plugins could be provided either a string or object, but our detection    
logic for code coverage plugin only covers the string case.                     
                                                                                
Fix #19571

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts [hunk 1]
```diff
@@ -334,6 +334,22 @@ function fallbackMiddleware() {
...
 
+/**
+ * Returns a function that returns true if the plugin identifier matches the
+ * `moduleId` or `pluginName`. A plugin identifier can be either a string or
+ * an object according to https://karma-runner.github.io/5.2/config/plugins.html
+ * @param moduleId name of the node module (e.g. karma-coverage)
+ * @param pluginName name of the karma plugin (e.g. reporter:coverage)
+ */
+function isPlugin(moduleId: string, pluginName: string) {
+  return function(plugin: string|{}) {
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/karma.ts:345]: Nit: I think adding explicit return type is a better practice.

```suggestion
  return (plugin: string|{}): boolean  => {
```

**Review by clydin — APPROVED** [review]

**Review by alan-agius4 — APPROVED** [review]
