### PR TITLE
fix(@angular-devkit/build-angular): emit error when a script is not found.

### LINKED ISSUE #16659: ng serve hanging on "92% additional asset processing scripts-webpack-plugin"
# 🐞 bug report

### Affected Package

Problem trying to run `ng serve` with `Angular: 9.0.0-rc.7` (presumably webpack under the hood).

### Is this a regression?

Not sure. Similar complaints have been made in the past, but no clear solution is obvious. Isn't this just a matter of copying over scripts from the specified file path to the web-app's output dir?!

### Description

I'm trying to add scripts for [lightgallery.js](https://sachinchoolur.github.io/lightgallery.js/docs/) to my angular app. After running `npm i -S lightgallery.js` I have the following in both `test` and `build` `architects` in `angular.json`:
```
            "scripts": [
              "./node_modules/lightgallery.js/dist/js/lightgallery.min.js",
              "./node_modules/lightgallery.js/dist/js/lg-thumbnail.min.js",
              "./node_modules/lightgallery.js/dist/js/lg-fullscreen.min.js"
            ]
```

## 🔬 Minimal Reproduction

Checkout this branch https://github.com/MagnusBrzenk/skymont/tree/001-basic and try `npm i` followed by `ng serve`.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.7
Node: 10.16.3
OS: darwin x64

Angular: 9.0.0-rc.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.7
@angular-devkit/build-angular     0.900.0-rc.7
@angular-devkit/build-optimizer   0.900.0-rc.7
@angular-devkit/build-webpack     0.900.0-rc.7
@angular-devkit/core              9.0.0-rc.7
@angular-devkit/schematics        9.0.0-rc.7
@angular/cdk                      8.2.3
@angular/material                 8.2.3
@angular/pwa                      0.803.21
@ngtools/webpack                  9.0.0-rc.7
@schematics/angular               9.0.0-rc.7
@schematics/update                0.900.0-rc.7
rxjs                              6.5.4
typescript                        3.6.4
webpack                           4.41.2

</code></pre>

### PR DESCRIPTION
**Pull request by alan-agius4**
While we currently invoke the `callback` with the error in https://github.com/angular/angular-cli/blob/d4f1ff82c5d994aca68c39ff31f5d8b22e694b87/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/scripts-webpack-plugin.ts#L163 this is not bubbled up to the main webpack compilation due to the usage of `thisCompilation`.

Closes #16659

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts [hunk 1]
```diff
@@ -214,23 +215,28 @@ export function getCommonConfig(wco: WebpackConfigOptions): Configuration {
     buildOptions.scripts,
     'scripts',
   ).reduce((prev: { bundleName: string; paths: string[]; inject: boolean }[], curr) => {
-    const bundleName = curr.bundleName;
-    const resolvedPath = path.resolve(root, curr.input);
+    const { bundleName, inject, input } = curr;
+    const resolvedPath = path.resolve(root, input);
+
+    if (!existsSync(resolvedPath)) {
+      throw new Error(`Script file ${input} doesn't exist.`);
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts]:
```suggestion
      throw new Error(`Script file ${input} does not exist.`);
```
nit: avoid contractions

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts]: Done.

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts]: Done
