### PR TITLE
bug: provider not being added to the app component

### LINKED ISSUE #629: getting errors when i generate a route
i generated a route using using 
ng generate route ROUTE

if i open the app i get lots of errors like this 

browser_adapter.js:77 Error: DI Exception
    at NoProviderError.BaseException [as constructor] (exceptions.js:17)
    at NoProviderError.AbstractProviderError [as constructor] (reflective_exceptions.js:39)
    at new NoProviderError (reflective_exceptions.js:75)
    at ReflectiveInjector_._throwOrNull (reflective_injector.js:776)
    at ReflectiveInjector_._getByKeyDefault (reflective_injector.js:804)
    at ReflectiveInjector_._getByKey (reflective_injector.js:767)
    at ReflectiveInjector_.get (reflective_injector.js:576)
    at ElementInjector.get (element_injector.js:23)
    at DebugAppView._View_DemocracyAppComponent0.createInternal (DemocracyAppComponent.template.js:24)
    at DebugAppView.AppView.create (view.js:66)

### LINKED ISSUE #631: Adding a route fails
Version: angular-cli@0.0.39

    ng g route home --default

Running the app gives the following error:

    The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
    Error: Typescript found the following errors:
    /Users/nbhati/projects/angular2-seed-cli/tmp/broccoli_type_script_compiler-input_base_path-jPwD2Y7Q.tmp/0/src/app/angular2-seed-cli.component.ts (13, 45): Argument of type '{ path: string; component: typeof HomeComponent; useAsDefault: boolean; }[]' is not assignable to parameter of type 'RouteMetadata[]'.
    Type '{ path: string; component: typeof HomeComponent; useAsDefault: boolean; }' is not assignable to type 'RouteMetadata'.

### PR DESCRIPTION
**Pull request by Brocco**
Fixes #629
Fixes #631

### CODE REVIEW

File: addon/ng2/blueprints/route/index.js [hunk 1]
```diff
@@ -214,7 +214,11 @@ module.exports = {
     }
 
     let isAppComponent = false;
-    if (parentFile == path.join(this.dynamicPath.dir, this.project.name() + '.component.ts')) {
+    let appComponentFile = 
+      path.join(this.project.root, 
+        this.dynamicPath.dir, 
+        this.project.name() + '.component.ts');
+    if (parentFile == appComponentFile) {
```
Comment (rokburgar) [inline addon/ng2/blueprints/route/index.js]: Why not just do `let isAppComponent  = parentFile === appComponentFile`?
