### PR TITLE
fix(@ngtools/webpack): rebuilding project with errors reports cannot …

### LINKED ISSUE #14644: Rebuilding project with errors reports cannot find .ts files
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
Yes

7.x

### Description

With a project that has build errors (after updating to V8), with `ng serve` running, correcting one error and saving the file causes the project to rebuild, but report that it cannot find the main.ts files:

```
ERROR in ./src/main.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/john/Dev/Javascript/Angular/FRC-TimeTracker/src/main.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/john/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:834:23)
    at /Users/john/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
ERROR in ./src/polyfills.ts
Module build failed (from ./node_modules/@ngtools/webpack/src/index.js):
Error: /Users/john/Dev/Javascript/Angular/FRC-TimeTracker/src/polyfills.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (/Users/john/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:834:23)
    at /Users/john/Dev/Javascript/Angular/FRC-TimeTracker/node_modules/@ngtools/webpack/src/loader.js:41:31
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
ℹ ｢wdm｣: Failed to compile.
    
```

After the first `ng serve`other than the build errors (below), the above errors do not happen.

My build errors
```
   ERROR in src/app/apparel/add-apparel/add-apparel.component.ts(25,4): error TS2554: Expected 2 arguments, but got 1.
    src/app/events/add-edit-event.component.ts(23,4): error TS2554: Expected 2 arguments, but got 1.
    src/app/message/edit-message/edit-message.component.ts(25,4): error TS2554: Expected 2 arguments, but got 1.
    src/app/message/message-list/message-list.component.ts(18,4): error TS2554: Expected 2 arguments, but got 1.
    src/app/reports/student-hours-report.component.ts(21,4): error TS2554: Expected 2 arguments, but got 1.
    src/app/shared/alert-message/alert-message.component.ts(9,4): error TS2554: Expected 2 arguments, but got 1.
    src/app/shared/image-upload/image-upload-service.service.ts(2,22): error TS2307: Cannot find module '@angular/http'.
    src/app/student/student-list/student-list.component.ts(21,4): error TS2554: Expected 2 arguments, but got 1.
```

## 🔥 Exception or Error
Shown above.

## 🌍 Your Environment
<pre><code>
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.1
Node: 12.3.1
OS: darwin x64
Angular: 8.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

### PR DESCRIPTION
**Pull request by alan-agius4**
When the first build in JIT has an error we are not emitting files. This ends up causing an issue because subsequent builds only trigger partial emits of files and only emits the full set of files if the number of files changed is greater than 20.

This logic adds the behavior that we only enter the 'only 20 files' part when the previous build was successful.

Fixes #14644

### CODE REVIEW

File: packages/ngtools/webpack/src/angular_compiler_plugin.ts [hunk 1]
```diff
@@ -1195,14 +1196,15 @@ export class AngularCompilerPlugin {
           'AngularCompilerPlugin._emit.ts', diagMode));
 
         if (!hasErrors(allDiagnostics)) {
-          if (this._firstRun || changedTsFiles.size > 20) {
+          if (this._firstRun || changedTsFiles.size > 20 || !this._hadFullJitEmit) {
```
Comment (filipesilva) [inline packages/ngtools/webpack/src/angular_compiler_plugin.ts]: I think the correct approach is to never enter the "only 20 files" branch if the last build wasn't successful. We can use `this._emitSkipped` to know this.

Comment (alan-agius4) [reply packages/ngtools/webpack/src/angular_compiler_plugin.ts]: You are right :)

File: packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts [hunk 2]
```diff
@@ -205,6 +202,47 @@ describe('Browser Builder rebuilds', () => {
...
+            logs = [];
+            // Fix the static analysis error.
+            host.writeMultipleFiles({ 'src/app/app.component.ts': `
+              ${origContent}
+              console.errorr('error');
+            `});
+            break;
+
+          case 2:
+            // The third build should have everything fixed..
```
Comment (filipesilva) [inline packages/angular_devkit/build_angular/test/browser/rebuild_spec_large.ts]: Nit: `third`->`second`
