### PR TITLE
fix(serve): fallback to config.app[0].index

### LINKED ISSUE #3748: rename index.html will lead that the app is not available
IMHO, the index file for the app is configurable,  and a file named such as `main.html` can be used if the value for `index` in `angular-cli.json` is given.
however, rename index.html file will lead that the app is not available after I upgrade the angular-cli to beta.24.  (while working well in beta.18)

> --------------------------------------------------------------

```
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "main.html",
      "main": "main.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "mobile": false,
      "styles": [
        "styles.css"
      ],
      "scripts": [],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ]
```

> ---------------------------------------------------------------

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #3748

### CODE REVIEW

File: packages/angular-cli/tasks/serve-webpack.ts [hunk 1]
```diff
@@ -84,12 +86,10 @@ export default Task.extend({
     }
 
     const webpackDevServerConfiguration: IWebpackDevServerConfigurationOptions = {
-      contentBase: path.resolve(
-        this.project.root,
-        `./${CliConfig.fromProject().config.apps[0].root}`
-      ),
+      contentBase: path.resolve(this.project.root, `./${appConfig.root}`),
```
Comment (hansl) [inline packages/angular-cli/tasks/serve-webpack.ts]: `path.join(...)`

Comment (filipesilva) [inline packages/angular-cli/tasks/serve-webpack.ts]: Fixed

**Comment by filipesilva** [comment]
Merging as nit was incorporated.
