### PR TITLE
test: add a minimal standalone component application E2E test

### LINKED ISSUE #23044: Standalone components end-to-end test
With standalone components coming soon, we should set up an e2e test in the CLI project which builds and tests a "Hello, World!" application built entirely with standalone components and related APIs. This will help protect against future regressions.

### PR DESCRIPTION
**Pull request by clydin**
A new E2E test has been added that updates a newly generated application to use a standalone component that
is bootstrapped with the newly introduced `bootstrapApplication` API. This test is intended to check that
the minimal functionality for a standalone-based application functions with the Angular CLI. More expansive
tests will be added as standalone features and capabilities are introduced within the Angular CLI.

Closes #23044

### CODE REVIEW

**Review by pkozlowski-opensource — APPROVED** [review]
Not familiar with the CLI testing infrastructure but the scenario / test itself LGTM

File: tests/legacy-cli/e2e/tests/basic/standalone.ts [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+const STANDALONE_MAIN_CONTENT = `
+import { Component } from '@angular/core';
+import { CommonModule } from '@angular/common';
+import { bootstrapApplication } from '@angular/platform-browser';
+
+@Component({
+  selector: 'app-root',
+  standalone: true,
+  template: \`
+    <ng-template [ngIf]="isVisible">
```
Comment (dgp1130) [inline tests/legacy-cli/e2e/tests/basic/standalone.ts:30]: Nit: I assume we're using `ng-template` here to validate that the `CommonModule` import worked, would be good to leave a comment stating that explicitly, otherwise it feels like an unnecessary implementation detail.

File: tests/legacy-cli/e2e/tests/basic/standalone.ts [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+ * Copyright Google LLC All Rights Reserved.
+ *
+ * Use of this source code is governed by an MIT-style license that can be
+ * found in the LICENSE file at https://angular.io/license
+ */
+
+/**
+ * @fileoverview Tests the minimal conversion of a newly generated application
+ * to use a single standalone component.
+ */
```
Comment (dgp1130) [inline tests/legacy-cli/e2e/tests/basic/standalone.ts:12]: Nit: Is it possible to merge the `@license` and `@fileoverview` comments?

File: tests/legacy-cli/e2e/tests/basic/standalone.ts [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+
+export default async function () {
+  // Update to a standalone application
+  await writeFile('src/main.ts', STANDALONE_MAIN_CONTENT);
+
+  // Execute a production build
+  await ng('build');
+
+  // Perform the default E2E tests
+  await ng('e2e', 'test-project');
```
Comment (dgp1130) [inline tests/legacy-cli/e2e/tests/basic/standalone.ts:54]: We should also consider adding a unit test for standalone and verifying that that works, but we can follow up with and expand this test later, so not a blocking issue for this PR.

**Review by dgp1130 — APPROVED** [review]

**Review by dgp1130 — APPROVED** [review]
