### PR TITLE
fix(@angular/cli): don't display prompts twice

### LINKED ISSUE #19027: ng generate guard prompts twice
# 🐞 Bug report

### Command (mark with an `x`)
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?
Yes

### Description
Using angular CLI to generate a guard prompts twice for 
`? Which interfaces would you like to implement? CanActivate`
`? Which interfaces would you like to implement? CanActivate`

## 🔬 Minimal Reproduction
- `> npx @angular/cli@11.0.0-next.6 new admin-console --strict true --routing true --style css`
- `> cd admin-console`
- `> yarn ng generate guard guards/oauth/auth-oauth`
guard_twcie

## 🔥 Exception or Error
No exception

## 🌍 Your Environment
<pre><code>
$ ng version
Angular CLI: 11.0.0-next.6
Node: 14.13.1
OS: darwin x64

Angular: 11.0.0-next.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-next.6
@angular-devkit/build-angular   0.1100.0-next.6
@angular-devkit/core            11.0.0-next.6
@angular-devkit/schematics      11.0.0-next.6
@angular/cli                    11.0.0-next.6
@schematics/angular             11.0.0-next.6
@schematics/update              0.1100.0-next.6
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by alan-agius4**
Closes #19027

### CODE REVIEW

File: packages/angular/cli/models/schematic-command.ts [hunk 1]
```diff
@@ -78,6 +78,8 @@ export abstract class SchematicCommand<
   protected collectionName = this.defaultCollectionName;
   protected schematicName?: string;
 
+  private XDeprecatedProviderEnabled = true;
```
Comment (clydin) [inline packages/angular/cli/models/schematic-command.ts:81]: This looks unused now.

**Review by clydin — APPROVED** [review]

File: packages/angular/cli/models/schematic-command.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/angular/cli/models/schematic-command.ts:81]: 😓 oops
