### PR TITLE
fix(@angular-devkit/build-angular): error when both `baseUrl` and `devServerTarget` are used in protractor

### LINKED ISSUE #13611: --base-url has no effect
# 🐞 Bug report

The option `--base-url` has no effect. 

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [x] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 6.x.x

### Description

 
The option `--base-url` has no effect on the `e2e`-command. Also the `baseUrl`-entry in the `protractor.conf.js` has no effect.

## 🔬 Minimal Reproduction

Create new project via `ng new demo` and there modify the `e2e`-script or the `protractor.conf.js` as described. It has no affect. The app is always started at `http://localhost:4200` and the browser also opens this url. 
I have to run the tests in a no-serve scenario on a different url.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>

macos
@angular/cli@7.3.0 
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by alan-agius4**
fix(@angular-devkit/build-angular): error when both `baseUrl` and `devServerTarget` are used in protractor

Users cannot use both baseUrl and devServerTarget, and the later superseeds the baseUrl.

Fixes #13611

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/protractor/index.ts [hunk 1]
```diff
@@ -81,7 +85,7 @@ export class ProtractorBuilder implements Builder<ProtractorBuilderOptions> {
         }
 
         // Compute baseUrl from devServerOptions.
-        if (options.devServerTarget && builderConfig.options.publicHost) {
+        if (builderConfig.options.publicHost) {
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/protractor/index.ts]: This method is never called when `options.devServerTarget` is falsy

https://github.com/angular/angular-cli/blob/8c441d3f76d61d45076cfc2ef3fbcbf818422a14/packages/angular_devkit/build_angular/src/protractor/index.ts#L55

File: packages/angular_devkit/build_angular/src/protractor/index.ts [hunk 2]
```diff
@@ -44,7 +44,11 @@ export class ProtractorBuilder implements Builder<ProtractorBuilderOptions> {
     const options = builderConfig.options;
     const root = this.context.workspace.root;
     const projectRoot = resolve(root, builderConfig.root);
-    // const projectSystemRoot = getSystemPath(projectRoot);
+
+    // ensure that either one of this option is used
+    if (options.devServerTarget && options.baseUrl) {
+      throw new Error(`The 'baseUrl' option cannot be used with 'devServerTarget'.`);
```
Comment (filipesilva) [inline packages/angular_devkit/build_angular/src/protractor/index.ts]: I think it makes sense to error out since we use the devServerTarget to compute baseUrl. But we should be explicit here. Something like:

```
The 'baseUrl' option cannot be used with 'devServerTarget'.
When present, 'devServerTarget' will be used to automatically setup 'baseUrl' for Protractor.
```

Comment (clydin) [reply packages/angular_devkit/build_angular/src/protractor/index.ts]: I would actually expect it to override what's in the dev server target.  Otherwise, the baseUrl setting seems unnecessary as the overwhelming usage would be with a dev server target.

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/protractor/index.ts]: What if host or port are also provided?

Comment (clydin) [reply packages/angular_devkit/build_angular/src/protractor/index.ts]: The same.  Who knows how the developer has the environment setup. Or how they want protractor to connect to the application.

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/protractor/index.ts]: I mean, if host and or port are provided with baseUrl which one should override which?

Comment (clydin) [reply packages/angular_devkit/build_angular/src/protractor/index.ts]: Well, that's really a different question.  But I suppose it raises the additional question of why there are two ways to do the same thing?

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/protractor/index.ts]: I’ll put this up for discussion.

**Comment by alan-agius4** [comment]
@filipesilva, PR updated following the team meeting

I left the error message, as it's best to error out rather than have undefined behaviour, for the time being until this option is removed.
