### PR TITLE
fix(@angular/build): prevent build failures with remote CSS imports when Tailwind is configured

### LINKED ISSUE #28113: esbuild: Using Tailwind breaks stylesheet processing for CSS @imports with URLs ending in .css
### Command

build

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

_No response_

### Description

When Tailwind is configured in a project (maybe just PostCSS), any `@import url()` statement with a URL ending in `.css` (such as `@import url(https://fonts.googleapis.com/earlyaccess/notokufiarabic.css);` causes the build to fail, as the url is deemed a local file by the language filters passed to [`StyleSheetPluginFactory.create()`](https://github.com/angular/angular-cli/blob/048df34ccb7d4ef67b5877e126c74c0db65b879c/packages/angular/build/src/tools/esbuild/stylesheets/bundle-options.ts#L59-L61). The `create` method seems to register an esbuild `onLoad` handler that will [read the path as a local file](https://github.com/angular/angular-cli/blob/048df34ccb7d4ef67b5877e126c74c0db65b879c/packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts#L167-L170)

Any URLs ending in `.less`, `.scss` or `.sass` are also affected.

In our case we can't easily remove `.css` from the imported URL, as it's defined by an imported third party CSS file.

### Minimal Reproduction

1. Create a new project with `ng new`
2. Install Tailwind by following the [Tailwind + Angular installation guide](https://tailwindcss.com/docs/guides/angular)
3. Add the following to `src/styles.css`: `@import url(https://fonts.googleapis.com/earlyaccess/notokufiarabic.css);`
4. Run `npm run build`
5. The build fails, as the URL is attemped to be read as a local file

When no Tailwind config file is present, the build runs fine:
1. Remove `tailwind.config.js` and the `@tailwind` lines from the CSS file, while keeping the `@import url()`
2. Run `npm run build`
3. The build succeeds

### Exception or Error

```text
ENOENT: no such file or directory, open 'https://fonts.googleapis.com/earlyaccess/notokufiarabic.css' [plugin angular-css]
```

### Your Environment

```text
Angular CLI: 18.1.2
Node: 20.14.0
Package Manager: npm 10.7.0
OS: darwin arm64

Angular: 18.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1801.2
@angular-devkit/build-angular   18.1.2
@angular-devkit/core            18.1.2
@angular-devkit/schematics      18.1.2
@schematics/angular             18.1.2
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.8
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
This addresses a bug where `@import url()` statements with remote CSS files (ending in .css) caused build errors when Tailwind was present. The issue arised from incorrect handling of remote URLs by the stylesheet plugin, which treated them as local files. This fix ensures proper handling of remote CSS imports.

Closes #28113

### CODE REVIEW

File: packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts [hunk 1]
```diff
@@ -165,7 +165,7 @@ export class StylesheetPluginFactory {
 
         // Add a load callback to support files from disk
         build.onLoad(
-          { filter: language.fileFilter },
+          { filter: language.fileFilter, namespace: 'file' },
```
Comment (alan-agius4) [inline packages/angular/build/src/tools/esbuild/stylesheets/stylesheet-plugin-factory.ts:168]: This is not required, but I think it's worth having.

**Review by clydin — APPROVED** [review]

**Comment by alan-agius4** [comment]
The changes were merged into the following branches: main, 18.1.x
