### PR TITLE
fix(@angular-devkit/build-optimizer): increase safety of code removal

### LINKED ISSUE #14033: [@angular-devkit/build-optimizer] causes runtime errors in Monaco Editor
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

The bug is not present in `0.8.9`, but is present in `0.9.0-beta.0`.

### Description

Using `0.9.0-beta.0` (or later) versions of `@angular-devkit/build-optimizer` leads to the following runtime exceptions from `monaco-editor`:

Screen Shot 2019-03-30 at 11 28 33 AM

## 🔬 Minimal Reproduction

https://github.com/petermikitsh/buildoptimizer-error

```
git clone https://github.com/petermikitsh/buildoptimizer-error
cd buildoptimizer-error
npm install
npm start
```

## 🔥 Exception or Error
<pre><code>errors.js:22 Uncaught Error: Cannot read property 'createKey' of undefined

TypeError: Cannot read property 'createKey' of undefined
    at RawContextKey.bindTo (contextkey.js:439)
    at new MessageController (messageController.js:34)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at withAllStandaloneServices (standaloneEditor.js:97)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'createKey' of undefined

TypeError: Cannot read property 'createKey' of undefined
    at RawContextKey.bindTo (contextkey.js:439)
    at new CodeActionModel (codeActionModel.js:168)
    at new QuickFixController (codeActionCommands.js:148)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'createKey' of undefined

TypeError: Cannot read property 'createKey' of undefined
    at RawContextKey.bindTo (contextkey.js:439)
    at FindController.CommonFindController [as constructor] (findController.js:79)
    at new FindController (findController.js:322)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'createKey' of undefined

TypeError: Cannot read property 'createKey' of undefined
    at RawContextKey.bindTo (contextkey.js:439)
    at new MarkerController (gotoError.js:297)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at withAllStandaloneServices (standaloneEditor.js:97)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'getState' of null

TypeError: Cannot read property 'getState' of null
    at new SelectionHighlighter (multicursor.js:780)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at withAllStandaloneServices (standaloneEditor.js:97)
    at Object.create (standaloneEditor.js:109)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'createInstance' of undefined

TypeError: Cannot read property 'createInstance' of undefined
    at new ParameterHintsController (parameterHints.js:28)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at withAllStandaloneServices (standaloneEditor.js:97)
    at Object.create (standaloneEditor.js:109)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'createKey' of undefined

TypeError: Cannot read property 'createKey' of undefined
    at RawContextKey.bindTo (contextkey.js:439)
    at new SnippetController2 (snippetController2.js:31)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at withAllStandaloneServices (standaloneEditor.js:97)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'createInstance' of undefined

TypeError: Cannot read property 'createInstance' of undefined
    at new SuggestController (suggestController.js:164)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at withAllStandaloneServices (standaloneEditor.js:97)
    at Object.create (standaloneEditor.js:109)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'createInstance' of undefined

TypeError: Cannot read property 'createInstance' of undefined
    at new AccessibilityHelpController (accessibilityHelp.js:55)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at withAllStandaloneServices (standaloneEditor.js:97)
    at Object.create (standaloneEditor.js:109)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'createKey' of undefined

TypeError: Cannot read property 'createKey' of undefined
    at RawContextKey.bindTo (contextkey.js:439)
    at StandaloneReferencesController.ReferencesController (referencesController.js:131)
    at new StandaloneReferencesController (standaloneReferenceSearch.js:26)
    at create (types.js:152)
    at InstantiationService._createInstance (instantiationService.js:126)
    at InstantiationService.createInstance (instantiationService.js:93)
    at StandaloneEditor.CodeEditorWidget [as constructor] (codeEditorWidget.js:209)
    at StandaloneEditor.StandaloneCodeEditor [as constructor] (standaloneCodeEditor.js:72)
    at new StandaloneEditor (standaloneCodeEditor.js:160)
    at eval (standaloneEditor.js:110)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
CodeEditorWidget @ codeEditorWidget.js:213
StandaloneCodeEditor @ standaloneCodeEditor.js:72
StandaloneEditor @ standaloneCodeEditor.js:160
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'getValue' of undefined

TypeError: Cannot read property 'getValue' of undefined
    at ColorDetector.isEnabled (colorDetector.js:73)
    at eval (colorDetector.js:44)
    at Emitter.fire (event.js:535)
    at new StandaloneEditor (standaloneCodeEditor.js:179)
    at eval (standaloneEditor.js:110)
    at withAllStandaloneServices (standaloneEditor.js:97)
    at Object.create (standaloneEditor.js:109)
    at eval (index.js:6)
    at Object../index.js (main.js:208)
    at __webpack_require__ (main.js:64)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
Emitter.fire @ event.js:542
StandaloneEditor @ standaloneCodeEditor.js:179
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'createKey' of undefined

TypeError: Cannot read property 'createKey' of undefined
    at RawContextKey.bindTo (contextkey.js:439)
    at new WordHighlighter (wordHighlighter.js:159)
    at createWordHighlighterIfPossible (wordHighlighter.js:411)
    at eval (wordHighlighter.js:419)
    at Emitter.fire (event.js:535)
    at new StandaloneEditor (standaloneCodeEditor.js:179)
    at eval (standaloneEditor.js:110)
    at withAllStandaloneServices (standaloneEditor.js:97)
    at Object.create (standaloneEditor.js:109)
    at eval (index.js:6)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
Emitter.fire @ event.js:542
StandaloneEditor @ standaloneCodeEditor.js:179
(anonymous) @ standaloneEditor.js:110
withAllStandaloneServices @ standaloneEditor.js:97
create @ standaloneEditor.js:109
(anonymous) @ index.js:6
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
errors.js:22 Uncaught Error: Cannot read property 'getValue' of undefined

TypeError: Cannot read property 'getValue' of undefined
    at ColorDetector.isEnabled (colorDetector.js:73)
    at eval (colorDetector.js:51)
    at Emitter.fire (event.js:535)
    at eval (codeEditorWidget.js:171)
    at Emitter.fire (event.js:535)
    at Configuration.CommonEditorConfiguration._recomputeOptions (commonEditorConfig.js:100)
    at Configuration._onReferenceDomElementSizeChanged (configuration.js:247)
    at ElementSizeObserver.eval [as changeCallback] (configuration.js:222)
    at ElementSizeObserver.measureReferenceDomElement (elementSizeObserver.js:61)
    at ElementSizeObserver.observe (elementSizeObserver.js:42)
    at eval (errors.js:22)
(anonymous) @ errors.js:22
setTimeout (async)
ErrorHandler.unexpectedErrorHandler @ errors.js:20
ErrorHandler.onUnexpectedError @ errors.js:34
onUnexpectedError @ errors.js:48
Emitter.fire @ event.js:542
(anonymous) @ codeEditorWidget.js:171
Emitter.fire @ event.js:535
CommonEditorConfiguration._recomputeOptions @ commonEditorConfig.js:100
Configuration._onReferenceDomElementSizeChanged @ configuration.js:247
(anonymous) @ configuration.js:222
ElementSizeObserver.measureReferenceDomElement @ elementSizeObserver.js:61
ElementSizeObserver.observe @ elementSizeObserver.js:42
Configuration.observeReferenceElement @ configuration.js:253
CodeEditorWidget.layout @ codeEditorWidget.js:850
(anonymous) @ index.js:12
./index.js @ main.js:208
__webpack_require__ @ main.js:64
(anonymous) @ client:2
0 @ main.js:7989
__webpack_require__ @ main.js:64
(anonymous) @ main.js:196
(anonymous) @ main.js:199
</code></pre>

## 🌍 Your Environment
<pre><code>Angular CLI: 7.3.6
Node: 10.15.0
OS: darwin x64
Angular: undefined
... 

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.6 (cli-only)
@angular-devkit/build-optimizer   0.9.0-beta.0
@angular-devkit/core              7.3.6 (cli-only)
@angular-devkit/schematics        7.3.6 (cli-only)
@schematics/angular               7.3.6 (cli-only)
@schematics/update                0.13.6 (cli-only)
typescript                        3.0.3
webpack                           4.29.6
</code></pre>

**Anything else relevant?**

### LINKED ISSUE #18621: @angular-devkit/build-optimizer strips non-Angular decorators
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

I understood from the description of the build-optimizer plugin, that non-Angular decorators should _not_ be stripped.
https://www.npmjs.com/package/@angular-devkit/build-optimizer

However, I can see that decorated properties inside the constructor are removed, which prevents my team from using build-optimizer as part of the `ng build` command (we use inversifyjs to manage our dependencies outside of the Angular module).

Inside `scrub-file.ts`, the `isDecorateAssignmentExpression` method seems to be responsible for the decision to strip this metadata.

## 🔬 Minimal Reproduction
https://github.com/kevindrecruit/angular-build-optimizer-issue

## 🔥 Exception or Error
Using the minimum reproduction git repository, we can see the following error (_which is specific to _inversifyjs__):
```
ERROR Error: Missing required @inject or @multiInject annotation in: argument 0 in class e.
```
The point is that the `@inject()` has been removed from the constructor where it is still needed.

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.7
Node: 12.18.3
OS: linux x64

Angular: 10.0.12
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.7
@angular-devkit/build-angular     0.1000.7
@angular-devkit/build-optimizer   0.1000.7
@angular-devkit/build-webpack     0.1000.7
@angular-devkit/core              10.0.7
@angular-devkit/schematics        10.0.7
@angular/cli                      10.0.7
@ngtools/webpack                  10.0.7
@schematics/angular               10.0.7
@schematics/update                0.1000.7
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by clydin**
This change lowers the potential for code to be errantly removed by the prefix functions and scrub file transformers.  Only known safe modules are used with the prefix functions transformer as it can easily remove required module level side effects (as opposed to global level side effects) such as `__decorate` calls.
The scrub file transformer will now keep parameter metadata if non-Angular decorators are present. This allows libraries that use that information to continue to function.

Closes #14033
Closes #18621

### CODE REVIEW

File: packages/angular_devkit/build_optimizer/src/index.ts [hunk 1]
```diff
@@ -5,6 +5,9 @@
  * Use of this source code is governed by an MIT-style license that can be
  * found in the LICENSE file at https://angular.io/license
  */
+import type * as ts from 'typescript';
```
Comment (alan-agius4) [inline packages/angular_devkit/build_optimizer/src/index.ts:8]: Any benefit of using `import type` here considering also that TypeScript is a direct dependency of this package? I was under the impression that `import type` was mainly intended to be used when experiencing issues with some edge cases with Babel and transpile module.

File: packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts [hunk 2]
```diff
@@ -94,39 +92,34 @@ export function buildOptimizer(options: BuildOptimizerOptions): TransformJavascr
...
   let typeCheck = false;
-  if (options.isSideEffectFree || originalFilePath && isKnownSideEffectFree(originalFilePath)) {
+  if (hasSafeSideEffects) {
+    // Angular modules have known safe side effects
     getTransforms.push(
       // getPrefixFunctionsTransformer is rather dangerous, apply only to known pure es5 modules.
       // It will mark both `require()` calls and `console.log(stuff)` as pure.
       // We only apply it to modules known to be side effect free, since we know they are safe.
-      // getPrefixFunctionsTransformer needs to be before getFoldFileTransformer.
       getPrefixFunctionsTransformer,
```
Comment (alan-agius4) [inline packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts:111]: Do we know for which cases the prefix function transformer is needed in Angular?

**Review by alan-agius4 — APPROVED** [review]
2 questions mainly.

And from the code changes, I am confident that this change also fixes https://github.com/angular/angular-cli/issues/18621

File: packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts (hunk 2 above)
Comment (clydin) [reply packages/angular_devkit/build_optimizer/src/build-optimizer/build-optimizer.ts:111]: View Engine factory files need it and were already included in the safe side effect check.
Additionally, there are a variety call/new expressions in `@angular/core` involving the following:
```
[
  "ComponentFactoryResolver$1",
  "InjectionToken",
  "KeyRegistry",
  "Optional",
  "ObservableStrategy",
  "PromiseStrategy",
  "ReflectionCapabilities",
  "Reflector",
  "Version",
  "core_merge",
  "getClosureSafeProperty",
  "makeDecorator",
  "makeParamDecorator",
  "makePropDecorator",
  "tagSet",
  "tokenKey",
]
```

File: packages/angular_devkit/build_optimizer/src/index.ts (hunk 1 above)
Comment (clydin) [reply packages/angular_devkit/build_optimizer/src/index.ts]: not particularly.  It does prevent accident value usage but not really needed here.
