### PR TITLE
fix(@angular-devkit/build-angular): automatically purge stale build cache entries

### LINKED ISSUE #22323: Angular cache dir (.angular) grows and grows
When building our product with Angular 13 the .angular/cache is now generated.
At a first build thats around 500MB but it will not take long and it is grown to 9GB is that normal?

What is exactly cached there and how is it reused?

### PR DESCRIPTION
**Pull request by alan-agius4**
With every build-angular release, previously created cache entries get stale and are no longer used. This causes the cache to keep growing as older files are not purged.

With this change we automatically purge entries that have been created with older version of build-angular and can no longer be used with the current installed version.

Closes #22323

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/builders/server/index.ts [hunk 1]
```diff
@@ -55,6 +56,8 @@ export function execute(
   // Check Angular version.
   assertCompatibleAngularVersion(root);
 
+  void purgeStaleBuildCache(context);
```
Comment (dgp1130) [inline packages/angular_devkit/build_angular/src/builders/server/index.ts:59]: Is the `void` in order to suppress an unused `Promise` result? Is there perhaps an ignore comment we could use that would make this more clear? I can't say I've ever seen the `void` operator used by a human, so this was quite confusing at first glance.

Outside the style perspective, ignoring a `Promise` always makes me a bit uncomfortable since it's basically racing the entire program and errors don't propagate in a useful way. I get that we don't want to block a user's build on this, but I'm wondering if we should `await` it at the very end so we know it completed successfully without negatively impacting the DX. I assume purging the stale cache is probably quicker than a typical build and only happens when updating the CLI. Otherwise, I'm ok with ignoring the result, just trying to think if there's a way to avoid that pattern without hurting users.

File: packages/angular_devkit/build_angular/src/utils/purge-cache.ts [hunk 2]
```diff
@@ -0,0 +1,58 @@
...
+      ) => Promise<void>;
+    };
+
+    try {
+      if (rm) {
+        await rm(entryPath, { force: true, recursive: true, maxRetries: 3 });
+      } else {
+        await rmdir(entryPath, { recursive: true, maxRetries: 3 });
+      }
+    } catch {}
```
Comment (dgp1130) [inline packages/angular_devkit/build_angular/src/utils/purge-cache.ts:56]: I feel like I just saw this snippet in another PR, is this a common pattern in the CLI? Would it be worth factoring this out to something reusable?

Comment (dgp1130) [inline packages/angular_devkit/build_angular/src/utils/purge-cache.ts:56]: Should we log or output the error somewhere? I'm concerned this might silently fail and we'll never know about it.

File: packages/angular_devkit/build_angular/src/utils/purge-cache.ts [hunk 3]
```diff
@@ -0,0 +1,58 @@
...
+  const metadata = await context.getProjectMetadata(projectName);
+  const { basePath, path, enabled } = normalizeCacheOptions(metadata, context.workspaceRoot);
+
+  if (!enabled || !existsSync(basePath)) {
+    return;
+  }
+
+  const entries = await fsPromises.readdir(basePath);
+
+  for (const entry of entries) {
```
Comment (dgp1130) [inline packages/angular_devkit/build_angular/src/utils/purge-cache.ts:30]: Would it be work parallelizing all the deletes instead of running them sequentially?

**Review by dgp1130 — APPROVED** [review]

File: packages/angular_devkit/build_angular/src/builders/server/index.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/builders/server/index.ts:59]: I think in this case I’d favor to await the the promise

File: packages/angular_devkit/build_angular/src/utils/purge-cache.ts (hunk 2 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/utils/purge-cache.ts:56]: Yeah, I can do that once both PRs are merged.

File: packages/angular_devkit/build_angular/src/utils/purge-cache.ts (hunk 3 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/utils/purge-cache.ts:30]: That should work too.

File: packages/angular_devkit/build_angular/src/utils/purge-cache.ts (hunk 2 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/utils/purge-cache.ts:56]: Maybe a log message, since we don’t want this to be fatal.

File: packages/angular_devkit/build_angular/src/builders/server/index.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/builders/server/index.ts:59]: Actually all these methods are not `async`

File: packages/angular_devkit/build_angular/src/utils/purge-cache.ts (hunk 2 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/utils/purge-cache.ts:56]: Actually the other PR is using the sync version.

Comment (dgp1130) [reply packages/angular_devkit/build_angular/src/utils/purge-cache.ts:56]: Up to you whether it's worth merging them, just something I noticed looking through it.

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/utils/purge-cache.ts]: One thing to take into consideration here, is that there might be the case that 2 processes try to delete the same path at the same time which would cause an error. 

I think at this point, I prefer not to add an error log.

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/utils/purge-cache.ts]: PS: I added an E2E to cover the purging of stale cache.
