### PR TITLE
fix(@angular-devkit/build-angular): fixed Module.issuer is deprecated in webpack 5 for commonjs warn plugin

### LINKED ISSUE #18895: Webpack 5 warning
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

No

### Description

```
(node:60756) [DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:60756) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
Warning: Circular dependency detected:
src/styles.scss -> src/styles.scss
```

## 🔬 Minimal Reproduction

```
yarn global add @angular/cli@next
ng new test-webpack5 
cd test-webpack5 
add `"resolutions": { "webpack":"5.0.0-rc.0" }` in package.json
yarn install
yarn start
```

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍 Your Environment
<pre><code>Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-next.3
@angular-devkit/build-angular   0.1100.0-next.3
@angular-devkit/core            11.0.0-next.3
@angular-devkit/schematics      11.0.0-next.3
@schematics/angular             11.0.0-next.3
@schematics/update              0.1100.0-next.3
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by valorkin**
Closes #18895

Should fix all or part of
225 warnings `[DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API`

### CODE REVIEW

**Review by clydin — APPROVED** [review]

File: packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts [hunk 1]
```diff
@@ -46,7 +46,9 @@ export class CommonJsUsageWarnPlugin {
   apply(compiler: Compiler) {
     compiler.hooks.compilation.tap('CommonJsUsageWarnPlugin', compilation => {
       compilation.hooks.finishModules.tap('CommonJsUsageWarnPlugin', modules => {
-        for (const {dependencies, rawRequest, issuer} of modules as unknown as WebpackModule[]) {
+        for (const module of modules as unknown as WebpackModule[]) {
+          const {dependencies, rawRequest} = module;
+          const issuer = getIssuer(compilation, module);
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts:51]: This should probably be moved, in scope of where it is needed. Ie: down above L74
We are only interested in the issuer when the dep is commonjs

Comment (valorkin) [reply packages/angular_devkit/build_angular/src/webpack/plugins/common-js-usage-warn-plugin.ts]: done

**Review by alan-agius4 — APPROVED** [review]

**Comment by valorkin** [comment]
thanks :)
