### PR TITLE
test(@angular/build): add test with 'vitest' import in browser mode

### LINKED ISSUE #31745: `unit-test` builder causes the following error: `The entry point "vitest" cannot be marked as external`
### Command

test

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

https://github.com/angular/angular-build-builds/commit/50039a7e51a7a657bd346c96c2693e944d421dda

### Description

This build introduces the bug: https://github.com/angular/angular-build-builds/commit/425fabbbd2c332d8d49338894d7ed15222eb41d7

It seems to be related to this refactoring: https://github.com/angular/angular-cli/commit/4cf1aa32cb4ba601c23f4e953fb1a0125aecae19

### Minimal Reproduction

Tests won't start in browser mode and cause the provided error.

Might be a false positive given I am using the builds.

### Exception or Error

```text
Vitest caught 1 unhandled error during the test run.
This might cause false positive tests. Resolve unhandled errors to make sure your tests are not affected.

⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Unhandled Error ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
{
  detail: undefined,
  id: '',
  location: null,
  notes: [],
  pluginName: '',
  text: 'The entry point "vitest" cannot be marked as external',
  type: 'Unhandled Error',
  stacks: []
}
```

### Your Environment

```text
Angular CLI       : 21.1.0-next.0+sha-21a486b
Angular           : 21.0.0-rc.1
Node.js           : 24.8.0
Package Manager   : pnpm 10.20.0
Operating System  : darwin arm64

┌───────────────────────────┬───────────────────────────┬──────────────────────────────────────────────────────────────────────────────┐
│ Package                   │ Installed Version         │ Requested Version                                                            │
├───────────────────────────┼───────────────────────────┼──────────────────────────────────────────────────────────────────────────────┤
│ @angular/build            │ 21.1.0-next.0+sha-377780a │ github:angular/angular-build-builds#425fabbbd2c332d8d49338894d7ed15222eb41d7 │
│ @angular/cli              │ 21.1.0-next.0+sha-21a486b │ workspace:*                                                                  │
│ @angular/common           │ 21.0.0-rc.1               │ 21.0.0-rc.1                                                                  │
│ @angular/compiler         │ 21.0.0-rc.1               │ 21.0.0-rc.1                                                                  │
│ @angular/compiler-cli     │ 21.0.0-rc.1               │ 21.0.0-rc.1                                                                  │
│ @angular/core             │ 21.0.0-rc.1               │ 21.0.0-rc.1                                                                  │
│ @angular/forms            │ 21.0.0-rc.1               │ 21.0.0-rc.1                                                                  │
│ @angular/platform-browser │ 21.0.0-rc.1               │ 21.0.0-rc.1                                                                  │
│ @angular/router           │ 21.0.0-rc.1               │ 21.0.0-rc.1                                                                  │
│ rxjs                      │ 7.8.2                     │ ^7.8.1                                                                       │
│ typescript                │ 5.9.3                     │ ~5.9.2                                                                       │
│ vitest                    │ 4.0.8                     │ 4.0.8
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by yjaaidi**
This fixes the following error:
  'The entry point "vitest" cannot be marked as external'

by excluding vitest from the discovered dependencies handed to optimizeDeps.include

Closes #31745

## PR Checklist

Please check to confirm your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/angular/angular-cli/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [X] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: #31745

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

### CODE REVIEW

File: packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts [hunk 1]
```diff
@@ -231,7 +231,9 @@ export class VitestExecutor implements TestExecutor {
             coverage,
             projectName,
             projectSourceRoot: this.options.projectSourceRoot,
-            optimizeDepsInclude: this.externalMetadata.explicitBrowser,
+            optimizeDepsInclude: this.externalMetadata.explicitBrowser.filter(
```
Comment (yjaaidi) [inline packages/angular/build/src/builders/unit-test/runners/vitest/executor.ts]: Should I add a comment here?

I think that ideally, we should filter out all entrypoints from `explicitBrowser` but I can't imagine any valid scenario other then the `vitest` package import.

File: tests/legacy-cli/e2e/tests/vitest/browser-no-globals.ts [hunk 2]
```diff
@@ -0,0 +1,37 @@
...
+import { applyVitestBuilder } from '../../utils/vitest';
+import { ng, silentNpm, exec } from '../../utils/process';
+import { writeFile } from '../../utils/fs';
+import { updateJsonFile } from '../../utils/project';
+
+/**
+ * Allow `vitest` import in browser mode.
+ * @see https://github.com/angular/angular-cli/issues/31745
+ */
+export default async function (): Promise<void> {
```
Comment (yjaaidi) [inline tests/legacy-cli/e2e/tests/vitest/browser-no-globals.ts:11]: Given we really need to run in browser mode to reproduce the bug, I had to install the packages so I went with an e2e.

Any narrower test would be over-specifying and not provide enough confidence.

File: tests/legacy-cli/e2e/tests/vitest/browser-no-globals.ts [hunk 3]
```diff
@@ -0,0 +1,37 @@
+import assert from 'node:assert/strict';
```
Comment (yjaaidi) [inline tests/legacy-cli/e2e/tests/vitest/browser-no-globals.ts:1]: Should I rename the test to something more explicit? Or should we let the next person writing a browser mode test do that 😊.

**Comment by yjaaidi** [comment]
I'm AFK, I guess that I just have to explicitly choose headless.
I'll do this later

File: tests/legacy-cli/e2e/tests/vitest/browser.ts [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+  await applyVitestBuilder();
+
+  await silentNpm('install', '@vitest/browser-playwright', 'playwright', '--save-dev');
+  await exec('npx', 'playwright', 'install', 'chromium');
+
+  await updateJsonFile('angular.json', (json) => {
+    const projects = Object.values(json['projects']);
+    const project = projects[0]! as any;
+    project['architect']['test']['options']['browsers'] = ['ChromiumHeadless'];
+  });
```
Comment (clydin) [inline tests/legacy-cli/e2e/tests/vitest/browser.ts]: nit: you can pass this on the command line to avoid the file manipulation here.

File: tests/legacy-cli/e2e/tests/vitest/browser-no-globals.ts (hunk 3 above)
Comment (clydin) [reply tests/legacy-cli/e2e/tests/vitest/browser-no-globals.ts:1]: Maybe `browser-no-globals`?

File: tests/legacy-cli/e2e/tests/vitest/browser.ts [hunk 5]
```diff
@@ -0,0 +1,37 @@
...
+import { updateJsonFile } from '../../utils/project';
+
+/**
+ * Allow `vitest` import in browser mode.
+ * @see https://github.com/angular/angular-cli/issues/31745
+ */
+export default async function (): Promise<void> {
+  await applyVitestBuilder();
+
+  await silentNpm('install', '@vitest/browser-playwright', 'playwright', '--save-dev');
```
Comment (clydin) [inline tests/legacy-cli/e2e/tests/vitest/browser.ts]:
```suggestion
  await installPackage('playwright@1');
  await installPackage('@vitest/browser-playwright@4');
```
Allows for testing across package manager matrix.

File: tests/legacy-cli/e2e/tests/vitest/browser.ts [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+  await exec('npx', 'playwright', 'install', 'chromium');
```
Comment (clydin) [inline tests/legacy-cli/e2e/tests/vitest/browser.ts]:
```suggestion
  await exec('npx', 'playwright', 'install', 'chromium', '--only-shell');
```
Reduces the download size to the headless version only

**Comment by yjaaidi** [comment]
> This was fixed via #31781 as now only implicit external packages are included of which `vitest` is not.
> 
> The root cause is that Vitest is making a variety changes to the `optimizeDeps` option internally for browser mode. One of which was adding `vitest` to `entries` which then caused an issue if `vitest` was also added to `includes`. Oddly, it also appears to add it to `excludes` which one may assume would take priority over an `includes` element.
> 
> An additional test case would still be useful though.

Ah perfect! I saw the PR later and I was about to give it a try to see if it fixes it.
Oh! I remember the `excludes` gotcha. I remember scratching my head recently on it 😅

File: tests/legacy-cli/e2e/tests/vitest/browser.ts (hunk 6 above)
Comment (yjaaidi) [reply tests/legacy-cli/e2e/tests/vitest/browser.ts]: Ah indeed! Nice

File: tests/legacy-cli/e2e/tests/vitest/browser.ts (hunk 4 above)
Comment (yjaaidi) [reply tests/legacy-cli/e2e/tests/vitest/browser.ts]: 😅 Indeed!

Comment (yjaaidi) [reply tests/legacy-cli/e2e/tests/vitest/browser.ts]: ✅ done

File: tests/legacy-cli/e2e/tests/vitest/browser.ts (hunk 5 above)
Comment (yjaaidi) [reply tests/legacy-cli/e2e/tests/vitest/browser.ts]: ✅ done

File: tests/legacy-cli/e2e/tests/vitest/browser.ts (hunk 6 above)
Comment (yjaaidi) [reply tests/legacy-cli/e2e/tests/vitest/browser.ts]: ✅ done

**Review by clydin — APPROVED** [review]

**Comment by hybrist** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 720603223f2e9d1487ce54dac903fe8954bda3a5
- 21.0.x: 8d63d59d198e576b2aa6de8ad682a412f67239e5
