### PR TITLE
Several fixes for differential loading bundle downleveling

### LINKED ISSUE #15425: Outputted chunks size is wrong
Output of `ng build --prod --namedChunks`
```
chunk {0} runtime-es2015.d414a7cb17017f37a5ee.js (runtime) 4.98 kB [entry] [rendered]
chunk {1} default~admin-admin-module-ngfactory~repository-repository-module-ngfactory-es2015.85eafd65fa45db8856df.js (default~admin-admin-module-ngfactory~repository-repository-module-ngfactory) 96.2 kB  [rendered]
chunk {2} default~entity-entity-module-ngfactory~search-search-module-ngfactory-es2015.154872f75466bfdf5320.js (default~entity-entity-module-ngfactory~search-search-module-ngfactory) 18.5 kB  [rendered]
chunk {3} default~repository-repository-module-ngfactory~search-search-module-ngfactory-es2015.6d5b04bc87aee3acd6e7.js (default~repository-repository-module-ngfactory~search-search-module-ngfactory) 18 kB  [rendered]
chunk {4} admin-admin-module-ngfactory-es2015.26e76867581d4b49ca18.js (admin-admin-module-ngfactory) 10.6 kB  [rendered]
chunk {5} core-entry-entry-module-ngfactory-es2015.391b5c7a3674a84c2808.js (core-entry-entry-module-ngfactory) 55.6 kB  [rendered]
chunk {6} diagrams-diagrams-module-ngfactory-es2015.fd535f2bb03fe17af1f1.js (diagrams-diagrams-module-ngfactory) 842 kB  [rendered]
chunk {7} documents-documents-module-ngfactory-es2015.4fee80dd02d299b1c46d.js (documents-documents-module-ngfactory) 2.07 kB  [rendered]
chunk {8} entity-entity-module-ngfactory-es2015.ddf22ee7857de5b049d2.js (entity-entity-module-ngfactory) 329 kB  [rendered]
chunk {9} home-home-module-ngfactory-es2015.e9d46bd4acbfe2b31d59.js (home-home-module-ngfactory) 2.06 kB  [rendered]
chunk {10} main-es2015.c7e8565f7f95810e93f1.js (main) 1.14 MB [initial] [rendered]
chunk {11} polyfills-es2015.41afa03f65b227fbc537.js (polyfills) 63.7 kB [initial] [rendered]
chunk {12} polyfills-es5-es2015.8cc7f429fa8e32ea3084.js (polyfills-es5) 214 kB [initial] [rendered]
chunk {13} repository-repository-module-ngfactory-es2015.b3593c072639dbcac23c.js (repository-repository-module-ngfactory) 300 kB  [rendered]
chunk {14} search-search-module-ngfactory-es2015.f221003cfb5b114711df.js (search-search-module-ngfactory) 38.5 kB  [rendered]
chunk {15} styles.ccc5e00034cc0b0aad81.css (styles) 459 kB [initial] [rendered]
Date: 2019-08-23T09:16:24.504Z - Hash: 8a2767478a56fd245505 - Time: 58057ms

WARNING in budgets, maximum exceeded for initial. Budget 1.46 MB was exceeded by 413 kB.
Generating ES5 bundles for differential loading...
ES5 bundle generation complete.
```

Real sizes using `webpack-bundle-analyzer`
Screenshot_20190823_111850

------
```
Angular CLI: 8.3.0
Node: 11.10.0
OS: linux x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/cdk                      8.1.3
@angular/cli                      8.3.0
@ngtools/webpack                  8.3.0
@nguniversal/express-engine       8.1.1
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
```

This does not happen with CLI `8.2.2` and Devkit `0.802`.

### LINKED ISSUE #15468: Subresource Integrity for lazy modules is broken when DL is enabled
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [X] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, this is caused by the downleveling process.

## 🔬 Minimal Reproduction
```
ng new lazy-loading-dl --routing
cd lazy-loading-dl
ng g m foo --module app.module --route foo
```
Add the below in `app.component.html`
```
<a [routerLink]="['/foo']" >
  link to foo
</a>
```
```
ng build --prod --subresourceIntegrity
http-server dist/lazy-loading-dl
```

Open browser and click on the link

## 🔥 Exception or Error
<pre><code>
127.0.0.1/:1 Failed to find a valid digest in the 'integrity' attribute for resource 'http://127.0.0.1:8080/5-es2015.0914cd2e5d35cddfa66f.js' with computed SHA-256 integrity '9yuul7bmARNSj/M5wygxgYjfklmwN0bTD+8YGHdn5/I='. The resource has been blocked.
main-es2015.8ce6a89e85cdffc26eb1.js:1 ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk 5 failed.
(error: http://127.0.0.1:8080/5-es2015.0914cd2e5d35cddfa66f.js)
ChunkLoadError: Loading chunk 5 failed.
(error: http://127.0.0.1:8080/5-es2015.0914cd2e5d35cddfa66f.js)
    at Function.u.e (runtime-es2015.6b58afc9912521e9b6e5.js:1)
    at w (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at Rn.loadModuleFactory (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at Rn.load (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at c.project (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at c._tryNext (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at c._next (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at c.next (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at e._subscribe (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at e._trySubscribe (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at P (polyfills-es2015.fd917e7c3ed57f282ee5.js:1)
    at P (polyfills-es2015.fd917e7c3ed57f282ee5.js:1)
    at polyfills-es2015.fd917e7c3ed57f282ee5.js:1
    at a.invokeTask (polyfills-es2015.fd917e7c3ed57f282ee5.js:1)
    at Object.onInvokeTask (main-es2015.8ce6a89e85cdffc26eb1.js:1)
    at a.invokeTask (polyfills-es2015.fd917e7c3ed57f282ee5.js:1)
    at s.runTask (polyfills-es2015.fd917e7c3ed57f282ee5.js:1)
    at _ (polyfills-es2015.fd917e7c3ed57f282ee5.js:1)
    at c.invokeTask [as invoke] (polyfills-es2015.fd917e7c3ed57f282ee5.js:1)
    at y (polyfills-es2015.fd917e7c3ed57f282ee5.js:1)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.0
Node: 10.10.0
OS: win32 x64
Angular: 8.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.0
@angular-devkit/build-angular     0.803.0
@angular-devkit/build-optimizer   0.803.0
@angular-devkit/build-webpack     0.803.0
@angular-devkit/core              8.3.0
@angular-devkit/schematics        8.3.0
@angular/cli                      8.3.0
@ngtools/webpack                  8.3.0
@schematics/angular               8.3.0
@schematics/update                0.803.0
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

### LINKED ISSUE #15625: older (es5) browsers not fully supported when using workspace scripts
# 🐞 Bug report

### Command
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

Yes, the previous version I'm aware this was still working was 8.0. 

### Description
Since I upgraded the cli to 8.3.3 my applications do not provide support for older browsers such as IE11. 

## 🔬 Minimal Reproduction
1. Create a new project.
```
npx -p @angular/cli@8.3.3 ng new es5-support
```
2. Change the browsers list file to consider IE 9-11 (remove `not` as suggested in the comments):
```
> 0.5%
last 2 versions
Firefox ESR
not dead
IE 9-11
```
3. Create a custom script that uses, for example, Promises:
```
const myPromise = new Promise(function(resolve) {
  setTimeout(function(){
    resolve('Promise resolved');
  }, 500);
});

myPromise.then(console.log);
```
4. Add this script to the build target (angular.json):
```
... 
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/es5-support",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": false,
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": [
              "my-script.js"
            ]
          },
... 
```
5. Build the application:
```
ng build --prod
```
6. Deploy and run the application on IE11. 

Here is a repo that reproduces the error: https://github.com/cladera/ng-cli-es5-support

## 🔥 Exception or Error
<pre><code>
SCRIPT5009: 'Promise' is undefined
File: scripts.31a5e5bdf3ecf1f1be1c.js, Line: 1, Column: 1
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.3.4
Node: 12.3.1
OS: darwin x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cli                      8.3.4
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
If I run the build with the environment flag `NG_BUILD_DIFFERENTIAL_FULL` set to `1` it runs a build that does work on IE 11. 

Anyway, one may wonder why do I need to add a script to my application that may break it whatsoever. Well, in an ideal world, all the libraries I need would be full UMD/cmjs compatible and I may just import them as a normal vendor dependency. But sadly, that's not my case. I need to add some scripts as "global" because I'm forced to do it. My point is, this worked fine few minor versions ago and now it doesn't which in my opinion is a breaking change.

### PR DESCRIPTION
**Pull request by clydin**
This corrects SRI value injection into the runtime bundle as well as accurately displaying file sizes following a differential loading build.

Fixes #15468
Fixes #15425
Fixes #15625

### CODE REVIEW

File: tests/legacy-cli/e2e/tests/misc/support-safari-10.1.ts [hunk 1]
```diff
@@ -43,16 +43,16 @@ export default async function () {
     `);
   } else {
     await expectFileToMatch('dist/test-project/index.html', oneLineTrim`
+      <script src="runtime-es2015.js" type="module"></script>
```
Comment (alan-agius4) [inline tests/legacy-cli/e2e/tests/misc/support-safari-10.1.ts]: This doesn't seem right to be included prior to the `nomodule` polyfill, as this will cause both runtime to be executed on older versions on Safari 10.1

Comment (alan-agius4) [reply tests/legacy-cli/e2e/tests/misc/support-safari-10.1.ts]: I don't know why `test-browsers` is not failing :(

Comment (clydin) [reply tests/legacy-cli/e2e/tests/misc/support-safari-10.1.ts]: Good call. Done.

Safari 10.1 can parse and execute both runtime chunks so the second one replaces the first.  This would fail if SRI was enabled.

**Comment by lppedd** [comment]
@clydin hi! could this be backported to 8.3.*?

**Comment by clydin** [comment]
It will be in the next patch release which will be released this week.

**Comment by lppedd** [comment]
@clydin thank you, awesome!

**Comment by lppedd** [comment]
@clydin Updated. I've noticed the bundles are "mixed", and only after generating the ES5 ones chunks are displayed. I still receive the budget warning (don't understand if ES5 or ES2015). Is this wanted?

**Comment by paul-davis-sp** [comment]
@clydin We are having the same issue as @lppedd. The bundle sizes have decreased on disk after upgrading to Angular 8, but the budget is still complaining. 

The size of our main-es2015 bundle is 1.3M, but the budget fails: 
`ERROR in budgets, maximum exceeded for main. Budget 1.33 MB was exceeded by 309 kB.`

**Comment by william-chen-iress** [comment]
We tested this in ng cli 8.3.8

we still have SRI error for lazy load module. 

The steps to reproduce is in #15468

File: packages/angular_devkit/build_webpack/src/utils.ts [hunk 2]
```diff
@@ -20,19 +21,11 @@ export interface EmittedFiles {
...
-      files.push({ name, file, extension: path.extname(file), initial: true });
-    }
-  }
-
   // adds all chunks to the list of emitted files such as lazy loaded modules
-  for (const chunk of Object.values(compilation.chunks)) {
+  for (const chunk of compilation.chunks as webpack.compilation.Chunk[]) {
     for (const file of chunk.files as string[]) {
       files.push({
+        id: chunk.id.toString(),
```
Comment (sjoulbak) [inline packages/angular_devkit/build_webpack/src/utils.ts]: @clydin This will fail when the chunk id is `null`, since the id definition in [Chunk class](https://github.com/webpack/webpack/blob/master/lib/Chunk.js#L111-L112) tells us that it can also be `null`.

Comment (clydin) [reply packages/angular_devkit/build_webpack/src/utils.ts]: The types are incorrect there.  It can actually be a string or a number.  At successful completion of the build an id is also required to properly construct the runtime from within Webpack.  Also of note, the name field which from the link says it is always a string, can in fact be null.

**Comment by clydin** [comment]
Additional fixes/improvements are being backported to 8.3, this will resolve the remaining SRI issues.  There are unfortunately still some situations where the bundle budgets can trigger errantly.  These are in the process of being corrected.
