### PR TITLE
fix(@angular/cli): honor builder schema additional properties option

### LINKED ISSUE #14354: additionalProperties at the builder level are allowed
# 🐞 Bug report

### Command (mark with an `x`)
All Architect commands

### Is this a regression?

No, I do not believe this ever worked.

### Description

If a builder schema can say it supports `additionalProperties`. However, when running the builder with an additional property, the following error appears:
```
Unknown option: '--additional'
Unknown option: 'property'
```

## 🔬 Minimal Reproduction
https://github.com/FrozenPandaz/angular-bugs/tree/additional-properties
`ng run v8app:print --additional property`

## 🔥 Exception or Error
<pre><code>
Unknown option: '--additional'
Unknown option: 'property'

</code></pre>

## 🌍 Your Environment
<pre><code>
jason@pop-os:~/projects/temp/v8app$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.0.0-rc.2
Node: 10.15.3
OS: linux x64
Angular: 8.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-rc.2
@angular-devkit/build-angular     0.800.0-rc.2
@angular-devkit/build-optimizer   0.800.0-rc.2
@angular-devkit/build-webpack     0.800.0-rc.2
@angular-devkit/core              8.0.0-rc.2
@angular-devkit/schematics        8.0.0-rc.2
@ngtools/webpack                  8.0.0-rc.2
@schematics/angular               8.0.0-rc.2
@schematics/update                0.800.0-rc.2
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Anything else relevant?**
This is important for passing arguments into child processes.

Workarounds for this are ugly:

Workaround #1:
`ng run v8app:print --args="--additional property"` Where args is a string input.

No, should not matter.

### PR DESCRIPTION
**Pull request by clydin**
Fixes #14354

### CODE REVIEW

File: tests/legacy-cli/e2e/tests/commands/additional-properties.ts [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+import { updateJsonFile } from '../../utils/project';
+
+export default async function() {
+  await createDir('example-builder');
+  await writeMultipleFiles({
+    'example-builder/package.json': '{ "builders": "./builders.json" }',
+    'example-builder/schema.json': '{ "$schema": "http://json-schema.org/draft-07/schema", "type": "object", "additionalProperties": true }',
+    'example-builder/builders.json': '{ "$schema": "@angular-devkit/architect/src/builders-schema.json", "builders": { "example": { "implementation": "./example", "schema": "./schema.json" } } }',
+    'example-builder/example.js': 'module.exports.default = require("@angular-devkit/architect").createBuilder((options) => { console.log(options); return { success: true }; });',
+  });
```
Comment (filipesilva) [inline tests/legacy-cli/e2e/tests/commands/additional-properties.ts]: Nice.
