### PR TITLE
fix(@angular/cli): check for CI environment variable in tty helper

### LINKED ISSUE #14563: The analytics prompt shouldn't run in CI environments
# 🐞 Bug report

### Command (mark with an `x`)

```
npm install
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
v7 and below

### Description

When upgrading to v8 the analytics prompt breaks CI as it hangs infinitely waiting for the user to choose to enable it or not

## 🔬 Minimal Reproduction

Run npm install on a v8 cli project on CI. For example: https://travis-ci.org/mattlewis92/angular-calendar/builds/538499347

Attempting to disable analytics on the project then fails as the config it adds to angular.json is invalid
```
ng analytics project off
```

Screenshot 2019-05-29 at 09 57 39

## 🔥 Exception or Error
Screenshot 2019-05-29 at 09 53 42

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.0.0
Node: 12.1.0
OS: darwin x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0
@angular-devkit/build-angular      0.800.0
@angular-devkit/build-ng-packagr   0.800.0
@angular-devkit/build-optimizer    0.800.0
@angular-devkit/build-webpack      0.800.0
@angular-devkit/core               8.0.0
@angular-devkit/schematics         8.0.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0
@schematics/angular                8.0.0
@schematics/update                 0.800.0
ng-packagr                         5.2.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**

The `is-ci` package could be used to disable that prompt on CI envs: https://www.npmjs.com/package/is-ci

The `analytics` config needs to be added to the schema so it can be disabled at the project level

The workaround for now is to add this to travis.yml
```
before_install: npx @angular/cli analytics off
```

### PR DESCRIPTION
**Pull request by clydin**
Covers common CI platforms.

Fixes #14563

### CODE REVIEW

File: packages/angular/cli/utilities/tty.ts [hunk 1]
```diff
@@ -11,5 +11,5 @@ export function isTTY(): boolean {
     return !(force === '0' || force.toUpperCase() === 'FALSE');
   }
 
-  return !!process.stdout.isTTY && !!process.stdin.isTTY;
+  return !!process.stdout.isTTY && !!process.stdin.isTTY && !('CI' in process.env);
```
Comment (gkalpak) [inline packages/angular/cli/utilities/tty.ts]: I wonder how common it is for people to set `CI=false`/`CI=0` on their non-CI envs 😆

**Comment by alexeagle** [comment]
In case it's useful, we use https://github.com/mattn/go-isatty in the `ts_devserver`
