### PR TITLE
fix(@angular/cli): add environment file to compilerHost

### LINKED ISSUE #4375: prod environment file not use when I build with --aot flag
when I buil with this command : ng build --target=production --environment=prod --aot

The environment file used is not the environment.prod.ts file but the environment.ts 

The problem is just when I put the --aot flag

### PR DESCRIPTION
**Pull request by hansl**
Fixes #4375

### CODE REVIEW

File: packages/@angular/cli/models/webpack-configs/typescript.ts [hunk 1]
```diff
@@ -9,6 +10,28 @@ const webpackLoader: string = g['angularCliIsLocal']
   : '@ngtools/webpack';
 
 
+function _createAotPlugin(wco: WebpackConfigOptions, options: any) {
+  const { appConfig, projectRoot, buildOptions } = wco;
+
+  // Read the environment, and set it in the compiler host.
+  const appRoot = path.resolve(projectRoot, wco.appConfig.root);
```
Comment (Brocco) [inline packages/@angular/cli/models/webpack-configs/typescript.ts]: Shouldn't `wco.appConfig.root` be `appConfig.root` since it was already destructured from wco? (same on the next 2 lines too)

Comment (hansl) [inline packages/@angular/cli/models/webpack-configs/typescript.ts]: yes. done.
