### PR TITLE
fix(@angular-devkit/build-angular): ensure proper display of build logs in the presence of warnings or errors

### LINKED ISSUE #27233: Missing build duration display after ng build in Angular v17.1.0
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

17.0.0

### Description

In Angular version 17.0.0, the ng build command used to display the duration of the build process in the console after the packaging was completed. However, starting from version 17.1.0, this helpful feature seems to be missing. As a result, developers are no longer provided with the build duration information, making it difficult to assess the performance and optimization of the build process. It is important to address this bug and restore the display of build duration in the console after executing ng build.

### Minimal Reproduction

no

### Exception or Error

```text
no
```

### Your Environment

```text
Angular CLI: 17.1.0
Node: 18.17.0
Package Manager: yarn 1.22.19
OS: win32 x64

Angular: 17.2.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1702.0
@angular-devkit/build-angular   17.1.0
@angular-devkit/core            17.1.0
@angular-devkit/schematics      17.1.0
@angular/cdk                    17.1.0
@angular/cli                    17.1.0
@schematics/angular             17.1.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

### Anything else relevant?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
Previously, a race condition could occur due to the spinner, resulting in the deletion of the last printed log when warnings or errors were present. With this update, we ensure that logs are printed after the spinner has stopped.

Fixes #27233

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/builders/application/index.ts [hunk 1]
```diff
@@ -7,9 +7,15 @@
...
 import { BuilderContext, BuilderOutput, createBuilder } from '@angular-devkit/architect';
-import type { Plugin } from 'esbuild';
+import { type Plugin, formatMessages } from 'esbuild';
+import { join } from 'node:path';
+import { pathToFileURL } from 'node:url';
 import { BuildOutputFile, BuildOutputFileType } from '../../tools/esbuild/bundler-context';
-import { logMessages } from '../../tools/esbuild/utils';
+import { ExecutionResult } from '../../tools/esbuild/bundler-execution-result';
+import {
+  createJsonBuildManifest as createJsonBuildManifest,
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/builders/application/index.ts:16]:
```suggestion
  createJsonBuildManifest,
```

**Review by clydin — APPROVED** [review]
