### PR TITLE
fix(@angular/ssr): support '*' in allowedHosts and warn about security risks

### LINKED ISSUE #32729: (@angular/ssr): strict host header validation breaks multi-tenant apps
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

Yes

### Is this a regression?
- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was
`@angular/ssr` `21.0.x` (regression observed after upgrading to `21.1.x`)

### Description
After upgrading to 21.1.x  which includes strict SSR host/forwarded-header validation, multi-tenant SSR apps started failing for valid tenant domains. This is something that was being validated upstream so far, so no need to validate on the Angular level.

This is noted here - https://angular.dev/best-practices/security#preventing-server-side-request-forgery-ssrf

Since this change, requests that used to SSR-render now fail and only do CSR:

This is a regression for apps that cannot predict all tenant hosts via `allowedHosts`. 

### Proposed solution
Allow a wildcard for `allowedHosts` or bypass the SSRF check altogether. 

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit adds support for '\*' in allowedHosts for SSR, allowing any host to be validated. It also adds a security warning when '\*' is used to inform users of the potential risks of allowing all host headers.

Additionally, it enables '\*' for the Vite dev server when 'allowedHosts' is set to 'true'.

Closes #32729

### CODE REVIEW

File: packages/angular/ssr/src/app-engine.ts [hunk 1]
```diff
@@ -88,7 +87,21 @@ export class AngularAppEngine {
...
+  }
+
+  private getAllowedHosts(options: AngularAppEngineOptions | undefined): ReadonlySet<string> {
+    const allowedHosts = new Set([...(options?.allowedHosts ?? []), ...this.manifest.allowedHosts]);
+
+    if (allowedHosts.has('*')) {
+      // eslint-disable-next-line no-console
+      console.warn(
+        'Allowing all hosts via "*" is a security risk. This configuration should only be used when ' +
+          'validation for "Host" and "X-Forwarded-Host" headers is performed in another layer.',
```
Comment (dgp1130) [inline packages/angular/ssr/src/app-engine.ts]: Consider: Can we expand on "another layer"? That feels vague enough that some devs might not understand what it means. Maybe say something about the production serving environment or cloud middleware / CDN / gateway handling this?

Also, should we include a link to some documentation in adev to 1) make clear that this is an Angular error, 2) draw a direct reference to the `allowedHosts` property, and 3) expand on the broader context of the problem this is catching (ie. why we have `allowedHosts` in the first place, what we mean by "hosts", etc.)?

File: packages/angular/ssr/src/utils/validation.ts [hunk 2]
```diff
@@ -224,7 +224,7 @@ function verifyHostAllowed(
  * @returns `true` if the hostname is allowed, `false` otherwise.
  */
 function isHostAllowed(hostname: string, allowedHosts: ReadonlySet<string>): boolean {
```
Comment (dgp1130) [inline packages/angular/ssr/src/utils/validation.ts:226]: Question: Do we care about the case of `allowedHosts = new Set(['*', 'example.test'])`? Should we warn / error for extra hosts which will no-op or is it fine to just silently ignore this case?

**Review by dgp1130 — APPROVED** [review]

File: packages/angular/ssr/src/app-engine.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/angular/ssr/src/app-engine.ts]: Added

File: packages/angular/ssr/src/utils/validation.ts (hunk 2 above)
Comment (alan-agius4) [reply packages/angular/ssr/src/utils/validation.ts:226]: I think it's fine to ignore this case and just warn about `*`

**Comment by alan-agius4** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 3b99ee140db82c8ddae3f6e48f9fc38eca204a53
- 21.2.x: 628c586728748e1c367fa7e363299eb79b1566ca
