### PR TITLE
fix(@angular-devkit/build-angular): correctly extract messages when using cached build

### LINKED ISSUE #22264: Empty i18n messages if .angular dir exists
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [x] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

In the previous angular versions there was no that  directory.

### Description

I have created a simple repo that demonstrates the issue. When you first run `ng extract-i18n` everything is fine, but once the `.angular` directory is created it stops working as expected - the generated file is empty.

## 🔬 Minimal Reproduction
https://github.com/destus90/i18n-issue

## 🔥 Exception or Error

<pre><code>

</code></pre>

## 🌍 Your Environment

<pre><code>
Angular CLI: 13.0.3
Node: 16.10.0
Package Manager: npm 7.24.0
OS: win32 x64

Angular: 13.0.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@angular/cli                    13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4

</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by alan-agius4**
Extracted messages are not part of Webpack pipeline and hence they cannot be retrieved from cache. Therefore, we need to mark the extraction loader as non cacheable.

Closes #22264

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/builders/extract-i18n/ivy-extract-loader.ts [hunk 1]
```diff
@@ -21,6 +21,11 @@ export default function localizeExtractLoader(
   content: string,
   map: LoaderSourceMap,
 ) {
+  // This loader is not cacheable due to message extraction works.
```
Comment (dgp1130) [inline packages/angular_devkit/build_angular/src/builders/extract-i18n/ivy-extract-loader.ts:24]: Nit: "due to *how* message extraction works"

File: packages/angular_devkit/build_angular/src/builders/extract-i18n/ivy-extract-loader.ts [hunk 2]
```diff
@@ -21,6 +21,11 @@ export default function localizeExtractLoader(
...
+  // Extracted messages are not part of webpack pipeline and hence they cannot be retrieved from cache.
+  // TODO: We should investigate in the future on making this deterministic and more cacheable.
```
Comment (dgp1130) [inline packages/angular_devkit/build_angular/src/builders/extract-i18n/ivy-extract-loader.ts:26]: Should we file an issue or project about this? I'm always hesitant about `TODO`'s in the code which tend to be forgotten about. Issues are more easily triaged, assignable, and actionable IMHO.

**Review by dgp1130 — APPROVED** [review]

File: packages/angular_devkit/build_angular/src/builders/extract-i18n/ivy-extract-loader.ts (hunk 2 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/builders/extract-i18n/ivy-extract-loader.ts:26]: Agreeded
