### PR TITLE
fix(@angular/build): ensure correct URL joining for prerender routes

### LINKED ISSUE #31877: Prerendering via "routesFile" with i18n no longer prerenders index.html, produces infinite "Redirecting" loop (since @angular/ssr 20.3.7)
### Command

build

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

20.3.6

### Description

Using `angular.json` `"prerender": { "routesFile": "...", "discoverRoutes": false }`, in combination with `"i18n": { ... }` and `"localize"`, no longer prerenders locale/index.html properly.

### Minimal Reproduction

Follow the following minimal reproduction steps:
1. `ng new test-prerender-i18n --style=scss --ssr --zoneless --ai-config=none`
2. `cd test-prerender-i18n`
3. `ng add @angular/localize`
4. `echo "/" > prerender-routes.txt`
5. Edit `app.routes.ts`, use the following content:
   ```typescript
   import { Routes } from '@angular/router';
   import { App } from './app';

   export const routes: Routes = [
     { path: '', component: App }
   ];
   ```
6. Edit `angular.json`:
   - Under `"projects" > "test-prerender-i18n"`, add:
     ```json
       "i18n": {
         "sourceLocale": "en"
       },
     ```
   - Under `"configurations" > "production"`, add
     ```json
              "prerender": {
                "routesFile": "prerender-routes.txt",
                "discoverRoutes": false
              },
              "localize": ["en"],
     ```
   - Remove `"outputMode": "server",` (doesn't work with prerender)
7. Run `ng build`
8. Try the build: `npx serve dist/test-prerender-i18n/browser/`
   then open Chrome http://localhost:3000/en => infinite redirect loop
9. `cat dist/test-prerender-i18n/browser/en/index.html`
   You will see the following HTML with infinite Redirecting loop, instead of actual prerendered content:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Redirecting</title>
    <meta http-equiv="refresh" content="0; url=/en">
  </head>
  <body>
    <pre>Redirecting to <a href="/en">/en</a></pre>
  </body>
</html>
```

### Exception or Error

```text
Redirecting
```

### Your Environment

```text
Angular CLI: 20.3.11
Node: 22.16.0
Package Manager: npm 11.6.2
OS: linux x64
```

### Anything else relevant?

- The issue affects the root route only ("/") i.e., the homepage.
  Other routes (such as /blog) seem to get prerendered just fine.
- Can reproduce only with `"discoverRoutes": false`

### Regression 20.3.6 -> 20.3.7
- Try version `20.3.6` of `@angular/ssr` => Prerendering works.
  `npm i @angular/ssr@20.3.6 && ng build && cat dist/test-prerender-i18n/browser/en/index.html`
- Try version `20.3.7` of `@angular/ssr` => Redirecting...
  `npm i @angular/ssr@20.3.7 && ng build && cat dist/test-prerender-i18n/browser/en/index.html`

### Culprit
- https://github.com/angular/angular-cli/releases/tag/20.3.7 → Might be caused by https://github.com/angular/angular-cli/commit/5db6d64870c7ce0b883722a07c828946b7d2217d
- Also related: https://github.com/angular/angular-cli/issues/31618
  (A different issue also since `20.3.7` about missing `index.html` in some cases; no mention of i18n.)
- Note: The issue also reproduces with the upcoming version `21.0.0`:
  `ng update @angular/core@next @angular/cli@next`
  `ng build && cat dist/test-prerender-i18n/browser/en/index.html` => Same issue.

### PR DESCRIPTION
**Pull request by alan-agius4**
This commit addresses an issue where prerendering with i18n and a `routesFile` could lead to infinite redirect loops or failure to prerender `index.html`.

The previous `urlJoin` utility was replaced with more robust URL manipulation functions (`joinUrlParts`, `addTrailingSlash`, `stripLeadingSlash`) to ensure that paths are correctly constructed, especially when dealing with base hrefs and locale subpaths. This ensures that routes from the `routesFile` are correctly joined with the base href, preventing malformed URLs that cause the redirection issues.

Closes #31877

### CODE REVIEW

File: packages/angular/build/src/utils/url.ts [hunk 1]
```diff
@@ -6,11 +6,117 @@
...
+    if (part === '') {
+      // Skip any empty parts
+      continue;
+    }
+
+    let normalizedPart = part;
+    if (part[0] === '/') {
+      normalizedPart = normalizedPart.slice(1);
+    }
+    if (part[part.length - 1] === '/') {
```
Comment (hybrist) [inline packages/angular/build/src/utils/url.ts:110]: Do we get to use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/at here since it's been widely available since March 2022?

**Review by hybrist — APPROVED** [review]
Is this code subtle enough that it warrants a few test cases?

File: packages/angular/build/src/utils/url.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/angular/build/src/utils/url.ts:110]: This is copied from the SSR package. I will do a followup to change the `.at(-1)`.

**Comment by alan-agius4** [comment]
This PR was merged into the repository. The changes were merged into the following branches:

- main: 0fe572ed7121953300bec373ac2261c8da6f89a4
- 21.0.x: 54d542738e23c275ac6827f19da92213c405f9e2
