### PR TITLE
fix(init): set skip-bower to true

### LINKED ISSUE #309: No bower.json present
Let me know if you need the full log running ng init with `--verbose`

Using `ng new app` doesn't throw any error, although no bower.json is created either.

OSX 10.11.3 
npm@3.8.1
node@v5.7.1

```
$ ng init
installing ng2
  create .clang-format
  create config/environment.js
  create e2e/app.e2e.ts
  create e2e/app.po.ts
  create e2e/tsconfig.json
  create e2e/typings.d.ts
  create angular-cli-build.js
  create .gitignore
  create karma-test-shim.js
  create karma.conf.js
  create package.json
  create protractor.conf.js
  create src/app/backend.html
  create src/app/backend.spec.ts
  create src/app/backend.ts
  create src/app.ts
  create src/favicon.ico
  create src/index.html
  create src/tsconfig.json
  create src/typings.d.ts
  create tslint.json
  create typings.json

├── es6-shim (ambient)
├── angular-protractor (ambient dev)
├── jasmine (ambient dev)
└── selenium-webdriver (ambient dev)

Installed packages for tooling via npm.
No bower.json present
Error: No bower.json present
    at createError (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/util/createError.js:4:15)
    at /usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/core/Project.js:49:19
    at /usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:1229:26
    at _fulfilled (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:796:13)
    at /usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:556:49
    at runSingle (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:137:13)
    at flush (/usr/local/lib/node_modules/angular-cli/node_modules/bower/lib/node_modules/q/q.js:125:13)
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
```

### PR DESCRIPTION
**Pull request by filipesilva**
Fix #309

### CODE REVIEW

File: addon/ng2/commands/init.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ module.exports = Command.extend({
     { name: 'verbose',    type: Boolean, default: false, aliases: ['v'] },
     { name: 'blueprint',  type: String,                  aliases: ['b'] },
     { name: 'skip-npm',   type: Boolean, default: false, aliases: ['sn'] },
-    { name: 'skip-bower', type: Boolean, default: false, aliases: ['sb'] },
+    { name: 'skip-bower', type: Boolean, default: true, aliases: ['sb'] },
```
Comment (jkuri) [inline addon/ng2/commands/init.js]: minor: can you fix the alignement?

**Comment by jkuri** [comment]
Otherwise I just tested this and it works. LGTM

File: addon/ng2/commands/init.js (hunk 1 above)
Comment (filipesilva) [inline addon/ng2/commands/init.js]: Right you are, fixed!
