### PR TITLE
Ivy i18n Localization Improvements

### LINKED ISSUE #15896: i18n IVY - Next.12 LocaleID not set
# 🐞 bug report

### Description

Setting locale in angular.json is ignored by the compiler. 
No matter the locale, injecting the localeID token gives "en-US" .

## 🔬 Minimal Reproduction

Set locale in angular.json
```
              "i18nFile": "src/locale/messages.sv.xlf",
              "i18nFormat": "xlf",
              "i18nLocale": "sv",
              "baseHref": "/sv/"
```

Serve the app, inject localeID token and print it out, gives "en-US"

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-next.12
Node: 12.2.0
OS: darwin x64
Angular: 9.0.0-next.12
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-next.12
@angular-devkit/build-angular      0.900.0-next.12
@angular-devkit/build-optimizer    0.900.0-next.12
@angular-devkit/build-webpack      0.900.0-next.12
@angular-devkit/core               9.0.0-next.12
@angular-devkit/schematics         9.0.0-next.12
@angular/cdk                       9.0.0-next.0
@angular/material                  9.0.0-next.0
@angular/material-moment-adapter   9.0.0-next.0
@angular/pwa                       0.900.0-next.12
@ngtools/webpack                   9.0.0-next.12
@schematics/angular                9.0.0-next.12
@schematics/update                 0.900.0-next.12
rxjs                               7.0.0-alpha.0
typescript                         3.6.4

</code></pre>

### PR DESCRIPTION
**Pull request by clydin**
* Parallel processing
* Source map support
* Deprecated option usage (`i18nFile`/`i18nLocale`)
* Localization of non-differential loading builds

Fixes #15896

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/browser/index.ts [hunk 1]
```diff
@@ -701,6 +760,70 @@ function generateIndex(
...
+    );
+  } catch (err) {
+    context.logger.error('Localized bundle generation failed: ' + err.message);
+
+    return false;
+  } finally {
+    executor.stop();
+  }
+
+  context.logger.info(`Localized bundle generation ${hasErrors ? 'failed' : 'complete'}.`);
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/browser/index.ts]: Nit: when failed, we should use `.error`
