### PR TITLE
fix(@angular/build): resolve "Controller is already closed" error in Karma

### LINKED ISSUE #30506: ERR_INVALID_STATE.TypeError('Controller is already closed') when executing unit tests in default created project for Angular 20
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I have updated one of my apps to angular 20 from angular 19.
Now I see that unit tests using karma works but at the end of the execution I see the next error:
node:internal/webstreams/readablestream:1077
      throw new ERR_INVALID_STATE.TypeError('Controller is already closed');
      ^

TypeError [ERR_INVALID_STATE]: Invalid state: Controller is already closed
    at ReadableStreamDefaultController.enqueue (node:internal/webstreams/readablestream:1077:13)

I also have updated angular-cli tool and I created a new project from scratch to know if maybe the issue is related with my project. But I have seen that same error appears. Also, I included Stryker in the default created project and this doesn't work (but Stryker is other problem).

Default created project package.json:
{
  "name": "ang-20-test",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^20.0.0",
    "@angular/compiler": "^20.0.0",
    "@angular/core": "^20.0.0",
    "@angular/forms": "^20.0.0",
    "@angular/platform-browser": "^20.0.0",
    "@angular/router": "^20.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.15.0"
  },
  "devDependencies": {
    "@angular/build": "^20.0.1",
    "@angular/cli": "^20.0.1",
    "@angular/compiler-cli": "^20.0.0",
    "@stryker-mutator/core": "^9.0.1",
    "@stryker-mutator/karma-runner": "^9.0.1",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.7.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.8.2"
  }
}

I created the project using node 20.19.2. Tested on Macbook Pro 2018 (intel arc)

### Please provide a link to a minimal reproduction of the bug

_No response_

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
This issue stems from the `Some of your tests did a full page reload` error, which occurs because `karmaOptions.client.clearContext` is set to `true` when `singleRun` is `false`, even though Karma is running in watch mode. Previously, the `watch` flag was configured inconsistently across multiple locations, leading to misalignment.

Closes #30506

### CODE REVIEW

**Comment by alan-agius4** [comment]
@jkrems, there are a lot of changes in this PR as it is on top of https://github.com/angular/angular-cli/pull/30646

File: packages/angular/build/src/builders/karma/application_builder.ts [hunk 1]
```diff
@@ -336,13 +337,9 @@ async function getProjectSourceRoot(context: BuilderContext): Promise<string> {
...
 
-function normalizePolyfills(polyfills: string | string[] | undefined): [string[], string[]] {
-  if (typeof polyfills === 'string') {
-    polyfills = [polyfills];
-  } else if (!polyfills) {
-    polyfills = [];
-  }
-
+function normalizePolyfills(
+  polyfills: string[] | undefined = [],
```
Comment (hybrist) [inline packages/angular/build/src/builders/karma/application_builder.ts]: nit: Is this the same as `polyfills: string[] = []`?

File: packages/angular/build/src/builders/karma/application_builder.ts [hunk 2]
```diff
@@ -718,3 +707,83 @@ function getInstrumentationExcludedPaths(root: string, excludedPaths: string[]):
...
+    ? {}
+    : getBuiltInKarmaConfig(context.workspaceRoot, projectName);
+
+  karmaOptions.singleRun = singleRun;
+
+  // Workaround https://github.com/angular/angular-cli/issues/28271, by clearing context by default
+  // for single run executions. Not clearing context for multi-run (watched) builds allows the
+  // Jasmine Spec Runner to be visible in the browser after test execution.
+  karmaOptions.client ??= {};
+  karmaOptions.client.clearContext ??= singleRun ?? false; // `singleRun` defaults to `false` per Karma docs.
```
Comment (hybrist) [inline packages/angular/build/src/builders/karma/application_builder.ts]: Does `?? false` ever apply? `singleRun` is a `const` that's assigned a boolean (`!expr`). I don't think the default value in Karma matters since we hard override it in 726?

File: packages/angular/build/src/builders/karma/schema.json [hunk 3]
```diff
@@ -229,7 +229,8 @@
     },
     "watch": {
       "type": "boolean",
-      "description": "Run build when files change."
+      "description": "Re-run tests when source files change.",
```
Comment (hybrist) [inline packages/angular/build/src/builders/karma/schema.json:232]: Double-checking: Was it ever a thing that the karma builder would default to non-watching outside of TTY?

File: packages/angular/build/src/builders/unit-test/schema.json [hunk 4]
```diff
@@ -44,7 +44,7 @@
     },
     "watch": {
       "type": "boolean",
-      "description": "Run build when files change."
+      "description": "Re-run tests when source files change. Defaults to `false` in TTY environments and `true` otherwise."
```
Comment (hybrist) [inline packages/angular/build/src/builders/unit-test/schema.json]: Is the default flipped here? I assume we _do_ watch in TTY environments and _don't_ outside of them? (Ref https://nodejs.org/api/tty.html#tty)

**Review by jkrems — APPROVED** [review]

File: packages/angular/build/src/builders/karma/schema.json (hunk 3 above)
Comment (alan-agius4) [reply packages/angular/build/src/builders/karma/schema.json:232]: No.

File: packages/angular/build/src/builders/unit-test/schema.json (hunk 4 above)
Comment (alan-agius4) [reply packages/angular/build/src/builders/unit-test/schema.json]: I meant false in non-TTY.

File: packages/angular/build/src/builders/karma/application_builder.ts (hunk 2 above)
Comment (alan-agius4) [reply packages/angular/build/src/builders/karma/application_builder.ts]: Good catch

**Comment by alan-agius4** [comment]
The changes were merged into the following branches: main, 20.1.x
