### PR TITLE
fix(@angular-devkit/build-angular): generate different content hashes for scripts which are changed during the optimization phase

### LINKED ISSUE #22906: Output files' filename for scripts hashes are incorrect
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Yes, the previous version in which this bug was not present was: Angular 11 (per original bug report, I did not test this)

### Description

Reopening #22602 
If I understand correctly, per https://github.com/angular/angular-cli/blob/master/CHANGELOG.md#1322-2022-02-02, this should be fixed in 13.2.2 and higher (since the main PR [#22612] associated with [ff54b49e7](https://github.com/angular/angular-cli/commit/ff54b49e7097cda2eb835bc8c9674f71fcc91c3c) closed #22602 ) . However, I see the issue in 13.2.2, 13.3.0, and 14.0.0-next.6.

## 🔬 Minimal Reproduction

(copied from original bug, except for updated clone link to a fork with 13.3.0)
1. Clone https://github.com/JoshuaEN/angular-filename-hashing-bug-reproduction
1. Run `npm ci` to install dependencies.
1. Run `ng build --configuration=production` (with the default es2017 target in tsconfig.json).
1. Observe the contents of the output `dist/angular-filename-hashing-bug-reproduction/scripts.{revhash_1}.js` file to be `try{console.log()}catch(c){}`.
1. Change the `compilerOptions.target` to `es2019` (or `es2020` or `es2021`) from `es2017` in tsconfig.json.
1. Run `ng build --configuration=production`.
1. Observe the contents of the output `dist/angular-filename-hashing-bug-reproduction/scripts.{revhash_2}.js` file to be `try{console.log()}catch{}` (different from the output from step 4).
1. Observe that revhash_1 equals revhash_2.

## 🌍 Your Environment

<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.0
Node: 16.14.2
Package Manager: npm 8.5.0
OS: win32 x64

Angular: 13.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.0
@angular-devkit/build-angular   13.3.0
@angular-devkit/core            13.3.0
@angular-devkit/schematics      13.3.0
@schematics/angular             13.3.0
rxjs                            7.4.0
typescript                      4.5.5
</code></pre>

### PR DESCRIPTION
**Pull request by martinfrancois**
Instead of generating the content hash based on the content of scripts BEFORE the optimization phase,
the content hash is generated AFTER the optimization phase.

Prevents caching issues where browsers block execution of scripts due to the integrity hash not matching
with the cached script in case of a script being optimized differently than in a previous build,
where it would previously result in the same content hash.

Fixes #22906

Test case is based on the reproduction example as specified in #22906 (thanks!).

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts [hunk 1]
```diff
@@ -149,19 +154,36 @@ export class ScriptsWebpackPlugin {
...
+        const output = { filename: this.options.filename, source: combinedSource };
         this._insertOutput(compilation, output);
         this._cachedOutput = output;
         addDependencies(compilation, scripts);
       });
+      compilation.hooks.processAssets.tapPromise(
+        {
+          name: PLUGIN_NAME,
+          stage: compiler.webpack.Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE_HASH,
+          additionalAssets: true,
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts:167]:
```suggestion
-          additionalAssets: true,
```

There is no need for this. We don't need to go over all the assets since we should only amend the assets that this plugin handled.

File: packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts [hunk 2]
```diff
@@ -149,19 +154,36 @@ export class ScriptsWebpackPlugin {
...
+        },
+        async (compilationAssets) => {
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts:169]:
```suggestion
        async () => {
```

File: packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts [hunk 3]
```diff
@@ -149,19 +154,36 @@ export class ScriptsWebpackPlugin {
...
+          for (const assetName in compilationAssets) {
+            if (Object.prototype.hasOwnProperty.call(compilationAssets, assetName)) {
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/scripts-webpack-plugin.ts:171]: We should only modify the asset that this plugin is handling.

```suggestion
           const assetName = this.options.filename;
```

File: tests/legacy-cli/e2e/tests/build/output-hashing.ts [hunk 4]
```diff
@@ -36,4 +41,40 @@ export default async function () {
   await expectFileToMatch('dist/test-project/index.html', /main\.[0-9a-f]{16}\.js/);
   await expectFileToMatch('dist/test-project/index.html', /styles\.[0-9a-f]{16}\.(css|js)/);
   await verifyMedia(/styles\.[0-9a-f]{16}\.(css|js)/, /image\.png/);
+
```
Comment (alan-agius4) [inline tests/legacy-cli/e2e/tests/build/output-hashing.ts:44]: Can you extract this into a separate test please?

Maybe 
```
scripts-output-hashing.ts
```

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Thanks for your contibution.

Couple of small changes.

File: tests/legacy-cli/e2e/tests/build/scripts-output-hashing.ts [hunk 5]
```diff
@@ -0,0 +1,45 @@
+import { expectFileMatchToExist, expectFileToMatch, writeMultipleFiles } from '../../utils/fs';
+import { ng } from '../../utils/process';
+import { updateJsonFile, updateTsConfig } from '../../utils/project';
+
+async function getScriptsFilename(): Promise<string> {
```
Comment (alan-agius4) [inline tests/legacy-cli/e2e/tests/build/scripts-output-hashing.ts:5]:
```suggestion
function getScriptsFilename(): Promise<string> {
```

**Review by alan-agius4 — APPROVED** [review]
LGTM. one small NIT

Thanks for this.

File: tests/legacy-cli/e2e/tests/build/scripts-output-hashing.ts [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+  return await expectFileMatchToExist('dist/test-project/', /external-module\.[0-9a-f]{16}\.js/);
```
[the remark this answers is not in the document]
Comment (martinfrancois) [reply tests/legacy-cli/e2e/tests/build/scripts-output-hashing.ts:6]: Well spotted, missed that one, thanks! :)

**Comment by martinfrancois** [comment]
@alan-agius4 You're welcome, thanks as well for the quick handling! Addressed your nit now and pushed it.

**Review by alan-agius4 — APPROVED** [review]

**Comment by alan-agius4** [comment]
@martinfrancois, it looks like https://github.com/angular/angular-cli/blob/68358f0c370dbe436d0b43eddb73f2489133b4f6/packages/angular_devkit/build_angular/src/builders/browser/specs/scripts-array_spec.ts#L78-L101 is failing. 

Let me know if you need any help with this.

**Comment by alan-agius4** [comment]
It looks like the sourcemaps are not renamed. In this case there is also another problem.

This also highlights a bigger problem. Since the sourcemaps are being renamed afterwards the sourcemaps comment would point to an invalid sourcemap file.

**Comment by martinfrancois** [comment]
@alan-agius4 I'm not using an M1 Mac, just an Intel one, that's the strange part about it... Is there a way to restrict the tests to only test `scripts-array_spec.ts` or the package it is in, without running the whole test suite?

**Comment by martinfrancois** [comment]
@alan-agius4 Tests are passing now! 🎉

**Comment by olegomon** [comment]
@martinfrancois thanks for the fix. @alan-agius4 thanks for your quick response on this issue.
