### PR TITLE
fix(@angular/cli): Move update check to inProject command logic

### LINKED ISSUE #10145: Error: An old project has been detected, which needs to be updated to Angular CLI 6.
### Versions
```
6.0.0-rc.0
macOS High Sierra
```

### Repro steps
* yarn global add @angular/cli@next
* mkdir newemptyfolder
* cd newemptyfolder
* ng new ng6

### Observed behavior
Creates project but spits out the errors below. and then creates the old project structure.

```
(node:14722) UnhandledPromiseRejectionWarning: Error: An old project has been detected, which needs to be updated to Angular CLI 6.

Please run the following commands to update this project.

  ng update @angular/cli --migrate-only --from=1.7.1
  npm i
    at WorkspaceLoader._assertUpdatedWorkspace (/Users/leon/.config/yarn/global/node_modules/@angular/cli/models/workspace-loader.js:73:19)
    at WorkspaceLoader._getProjectWorkspaceFilePath (/Users/leon/.config/yarn/global/node_modules/@angular/cli/models/workspace-loader.js:29:14)
    at WorkspaceLoader.loadWorkspace (/Users/leon/.config/yarn/global/node_modules/@angular/cli/models/workspace-loader.js:25:21)
    at NewCommand._loadWorkspace (/Users/leon/.config/yarn/global/node_modules/@angular/cli/models/schematic-command.js:255:29)
    at NewCommand.<anonymous> (/Users/leon/.config/yarn/global/node_modules/@angular/cli/models/schematic-command.js:53:18)
    at Generator.next (<anonymous>)
    at /Users/leon/.config/yarn/global/node_modules/@angular/cli/models/schematic-command.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/leon/.config/yarn/global/node_modules/@angular/cli/models/schematic-command.js:3:12)
    at NewCommand.initialize (/Users/leon/.config/yarn/global/node_modules/@angular/cli/models/schematic-command.js:52:16)
(node:14722) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14722) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN deprecated rxjs@6.0.0-smoosh.2: This version is deprecated. Please use the latest version of rxjs.

CREATE ng6/README.md (1025 bytes)
CREATE ng6/angular.json (3806 bytes)
CREATE ng6/package.json (1399 bytes)
CREATE ng6/tsconfig.json (384 bytes)
CREATE ng6/tslint.json (2819 bytes)
CREATE ng6/.editorconfig (245 bytes)
CREATE ng6/.gitignore (503 bytes)
CREATE ng6/src/environments/environment.prod.ts (51 bytes)
CREATE ng6/src/environments/environment.ts (743 bytes)
CREATE ng6/src/favicon.ico (5430 bytes)
CREATE ng6/src/index.html (290 bytes)
CREATE ng6/src/main.ts (370 bytes)
CREATE ng6/src/polyfills.ts (3114 bytes)
CREATE ng6/src/test.ts (642 bytes)
CREATE ng6/src/assets/.gitkeep (0 bytes)
CREATE ng6/src/styles.scss (80 bytes)
CREATE ng6/src/browserslist (51 bytes)
CREATE ng6/src/karma.conf.js (1011 bytes)
CREATE ng6/src/tsconfig.app.json (194 bytes)
CREATE ng6/src/tsconfig.spec.json (282 bytes)
CREATE ng6/src/app/app-routing.module.ts (245 bytes)
CREATE ng6/src/app/app.module.ts (393 bytes)
CREATE ng6/src/app/app.component.scss (0 bytes)
CREATE ng6/src/app/app.component.html (1173 bytes)
CREATE ng6/src/app/app.component.spec.ts (1103 bytes)
CREATE ng6/src/app/app.component.ts (208 bytes)
CREATE ng6/e2e/protractor.conf.js (752 bytes)
CREATE ng6/e2e/src/app.e2e-spec.ts (299 bytes)
CREATE ng6/e2e/src/app.po.ts (208 bytes)
CREATE ng6/e2e/tsconfig.e2e.json (213 bytes)
```

### Desired behavior
Should create new v.6 project structure and not complain about the empty folder being an old project.

### Mention any other details that might be useful (optional)
I tried removing all globally installed yarn packages, as to mitigate if any of them where braking cli, but still same problem.
The ng new command was run from a totally empty newly created folder, so it can't be anything to do with that.

### PR DESCRIPTION
**Pull request by Brocco**
fixes #10145

### CODE REVIEW

File: packages/@angular/cli/models/command-runner.ts [hunk 1]
```diff
@@ -220,6 +222,29 @@ function verifyWorkspace(command: Command, executionScope: CommandScope, root: s
...
+      normalize('.angular-cli.json'),
+      normalize('angular-cli.json'),
+    ];
+    const oldConfigFilePath = (root && findUp(oldConfigFileNames, root))
+      || findUp(oldConfigFileNames, process.cwd())
+      || findUp(oldConfigFileNames, __dirname);
+
+    // If an old configuration file is found, throw an exception.
+    if (oldConfigFilePath) {
+      throw new Error(stripIndent`
```
Comment (hansl) [inline packages/@angular/cli/models/command-runner.ts]: We shouldn't be using errors for this. Either log or throw `SilentError`.

File: packages/@angular/cli/models/command-runner.ts [hunk 2]
```diff
@@ -7,8 +7,10 @@ import {
   ArgumentStrategy
 } from '../models/command';
 import { oneLine } from 'common-tags';
-import { logging } from '@angular-devkit/core';
+import { logging, normalize } from '@angular-devkit/core';
 import { camelize } from '@angular-devkit/core/src/utils/strings';
+import { findUp } from '../utilities/find-up';
+import { stripIndent } from 'common-tags';
```
Comment (hansl) [inline packages/@angular/cli/models/command-runner.ts]: We're not using `common-tags` anymore. Use the tags from devkit core please.
