### PR TITLE
fix(webpack): remove usage of __dirname from the config.

### LINKED ISSUE #3419: Correctly resolve WebPack loaders within npm linked modules
### OS?
OSX Sierra

### Versions.
angular-cli: 1.0.0-beta.18
node: 6.9.1
os: darwin x64

### Repro steps.
Install NPM linked package that uses a WebPack loader. Loader cannot be resolved.

### The log given by the failure.
`Module not found: Error: Can't resolve 'style' in '...'`

### Mention any other details that might be useful.
Merge #2291 was incomplete, in that it does not fully address the issue raised in #1875. It fixes _module_ resolution, but not _loader_ resolution. The following needs to be added to the object returned from `getWebpackCommonConfig()` in `webpack-build-common.ts` in order to match current module resolution strategy:
```
resolveLoader: {
  modules: [path.resolve(projectRoot, 'node_modules')]
}
```

Also, I would submit a pull request, but the the corporate overhead of getting a CLA in place are prohibitive.

### PR DESCRIPTION
**Pull request by hansl**
Fixes #3419

### CODE REVIEW

File: packages/angular-cli/models/webpack-build-common.ts [hunk 1]
```diff
@@ -58,9 +58,12 @@ export function getWebpackCommonConfig(
     devtool: sourcemap ? 'source-map' : false,
     resolve: {
       extensions: ['.ts', '.js'],
-      modules: [nodeModules]
+      modules: [nodeModules],
```
Comment (grizzm0) [inline packages/angular-cli/models/webpack-build-common.ts]: The rest of the project does not include trailing commas.

Comment (grizzm0) [inline packages/angular-cli/models/webpack-build-common.ts]: The rest of the project does not include trailing comma.
