### PR TITLE
fix(@ngtools/webpack): remove message handler on main process 

### LINKED ISSUE #9071: Using @ngtools/webpack will kill the process when running in a child process
### Versions
```
ng version

    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.6.3
Node: 8.2.1
OS: win32 x64
Angular: 5.1.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.6.3
@angular-devkit/build-optimizer: 0.0.36
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.42
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.3
@schematics/angular: 0.1.11
@schematics/schematics: 0.0.11
typescript: 2.4.2
webpack: 3.10.0
```

### Repro steps

Run this script:

```javascript
const childProcess = require('child_process');
const isChildProcess = 'isChildProcess'
if (process.argv.indexOf(isChildProcess) >= 0) {
  require('@ngtools/webpack/src/type_checker');
  process.on('message', message => {
    console.log('received message!' + message);
    process.exit(0);
  });
  process.send('Child process alive');
} else {
  const child = childProcess.fork(__filename, [isChildProcess], { silent: false, execArgv: [] });
  child.on('message', message => {
    console.log('Received: ' + message);
    child.send('test message');
    child.removeAllListeners('message');
  });
}
```
While this is not a great example, it does illustrate the issue. If you host @ngtools/webpack in a child process you are basically not allowed to send any message without the process crashing. This is because of this line of code: https://github.com/angular/angular-cli/blob/f776d3cf7982b64734c57fe4407434e9f4ec09f7/packages/%40ngtools/webpack/src/type_checker.ts#L79

### Observed behavior

The process crashes: 

```
          throw new Error(`TypeChecker: Unexpected message received: ${message}.`);
            ^

Error: TypeChecker: Unexpected message received: test message.
    at process.on (C:\z\github\nicojs\angular-stryker-example\node_modules\@ngtools\webpack\src\type_checker.js:67:19)
    at emitTwo **(events.js:130:20)**
```

### Desired behavior
The process not crashing. Even better would be that requiring the file would not have *any* side effects. So no listening on `process.on('message', ...)`. 

### Mention any other details that might be useful (optional)

We are working on integration of angular cli projects in Stryker, the mutation testing framework. We are currently implementing a monkey patch around this problem (removing the listener for angular), but it would be nice if we can remove it in the future.

We're happy to do a PR if you can specify how you want it to be fixed. Why is that file listening to IPC messages?

### PR DESCRIPTION
**Pull request by nicojs**
Move the listening to messages from the type_checker.ts to a seperate
type_checker_worker.ts file. Only start listening to messages when a
magic 'auto start' argument is present in in the argument list,
preventing undesired eaves dropping on other processes.

Fixes #9071

### CODE REVIEW

File: packages/@ngtools/webpack/src/type_checker_worker.ts [hunk 1]
```diff
@@ -1,86 +1,70 @@
...
 import chalk from 'chalk';
-
-import { WebpackCompilerHost } from './compiler_host';
-import { time, timeEnd } from './benchmark';
-import { CancellationToken, gatherDiagnostics } from './gather_diagnostics';
+import * as ts from 'typescript';
+import * as process from 'process';
+import { WebpackCompilerHost } from '@ngtools/webpackcompiler_host';
+import { time, timeEnd } from '@ngtools/webpackbenchmark';
+import { CancellationToken, gatherDiagnostics } from '@ngtools/webpackgather_diagnostics';
```
Comment (filipesilva) [inline packages/@ngtools/webpack/src/type_checker_worker.ts]: I think something went wrong while renaming these imports. They should still be relative.

Comment (nicojs) [reply packages/@ngtools/webpack/src/type_checker_worker.ts]: Thanks! Should be fixed in a moment.

File: packages/@ngtools/webpack/src/type_checker_messages.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
+// @ignoreDep typescript
```
Comment (filipesilva) [inline packages/@ngtools/webpack/src/type_checker_messages.ts]: Can you move the `TypeChecker` class here (along with most things really), rename this file `type_checker.ts`, while leaving `type_checker_worker.ts` with only the messaging parsing code please?

It's likely enough that the type checker class might be needed individually from the worker in the future.

Comment (nicojs) [reply packages/@ngtools/webpack/src/type_checker_messages.ts]: Ah, good idea. Will do sir!

**Comment by nicojs** [comment]
@filipesilva I've updated the code based on your remarks. Do you want me to rebase my code? Or are you using squash merges?

**Comment by filipesilva** [comment]
There's no need to squash as long as all the commit messages are good. We rebase merge usually. You forgot to remove `chalk` which is causing a TS compilation error:
> packages/@ngtools/webpack/src/type_checker_worker.ts(2,8): error TS6133: 'chalk' is declared but never used.

Other than that everything looks good. Great job!

**Comment by filipesilva** [comment]
Odd error on rebuilds now:
```
 Error: Cannot find module '/tmp/angular-cli-e2e-11808-4734-rka7jz.n7emqjjor/test-project/9d93e901-158a-4cf9-ba1b-2f0582ffcfeb'
        at Function.Module._resolveFilename (module.js:469:15)
        at Function.Module._load (module.js:417:25)
...

WARNING in AngularCompilerPlugin: Forked Type Checker exited unexpectedly. Falling back to typechecking on main thread.
```

I think it's because you didn't update the type checker work filename in https://github.com/nicojs/angular-cli/blob/f830a8d00737216e438968ec142d58dda5c2cca2/packages/%40ngtools/webpack/src/angular_compiler_plugin.ts#L467-L469

At this point I would ask you to squash though, as some of these commits are fixing problems in the PR itself.

**Comment by nicojs** [comment]
Sorry about that. I was confused because I renamed it once too often. I've fixed it now and did a rebase. Build is running...

**Comment by filipesilva** [comment]
It seems to be failing in the same way now... at this point I don't know what's going wrong. Does it not fail on rebuilds locally on your machine?

Also @clydin brought up that the commit name kinda sounds like the CLI is collecting data on the main thread. I might rename the commit to something like `fix(@ngtools/webpack): remove message handler on main process` so that it is not misunderstood.

**Comment by nicojs** [comment]
@filipesilva I've updated the name of the commit, its indeed a better name. I was trying to keep it under 70 characters, but that is not needed?

I can't run `npm t` on my local (windows) machine:

```
$ npm t

> @angular/cli@1.6.3 test C:\z\github\angular\angular-cli
> npm-run-all -c test:packages test:cli test:deps test:licenses test:messages
> @angular/cli@1.6.3 test:packages C:\z\github\angular\angular-cli
> node scripts/run-packages-spec.js

Started
..............FFF.............

... A LOT OF LINES
 Expected $.statements[1].end = 1942 to equal 2026.
    Expected $.statements[1].expression.pos = 1939 to equal 2023.
    Expected $.statements[1].expression.end = 1941 to equal 2025.
    Expected $.endOfFileToken.pos = 1942 to equal 2026.
    Expected $.endOfFileToken.end = 1943 to equal 2028.
...

50 specs, 3 failures
Finished in 4.702 seconds
```

This is why i just pushed it and let the build server verify.

**Comment by filipesilva** [comment]
I pulled the PR down on my machine and tested it locally. I think I know what's going wrong. You add `AUTO_START_ARG` but that's not a flag. So when `fork` gets that option, it tries to load that file. 

```
// same as
node 9d93e901-158a-4cf9-ba1b-2f0582ffcfeb
```

That's why the error is
```
Error: Cannot find module '/tmp/angular-cli-e2e-11808-4734-rka7jz.n7emqjjor/test-project/9d93e901-158a-4cf9-ba1b-2f0582ffcfeb
```

Is `AUTO_START_ARG` needed now that there's a separate file though?

**Comment by nicojs** [comment]
Thanks for pointing that out to me. Sorry for the inconvenience. I've moved it to the arguments parameter and pushed it again.

> Is AUTO_START_ARG needed now that there's a separate file though?

Not strictly no, it's there as a second barrier of defense.

Any ideas on why i cannot run the tests locally?

**Comment by filipesilva** [comment]
The reason you can't run unit tests locally might be something related to Windows. I'm on windows myself but rarely run the unit tests.

They don't test this functionality though. To run a e2e tests checking rebuilds you can do the following:

```
node tests/run_e2e.js tests/e2e/tests/build/rebuild-types.ts
```

**Comment by nicojs** [comment]
Thanks for your help! I could run the tests locally now and they succeeded. I'm hopeful this one will pass.

**Comment by filipesilva** [comment]
LGTM and all green. Thanks for taking the time to put this fix together!
