### PR TITLE
fix(@angular/cli): use correct schematic defaults considering workspace

### LINKED ISSUE #14986: "module" schematic does not respect style setting for "component"
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

No, because this is about a newly introduced feature.

### Description

When generating a new module with lazy loading by
```
ng g m admin --route admin --module app
```

it will also generate a component within the new module.
However, **the style for this component is always `css`**, even if we have this setting in our `angular.json`:

```
"schematics": {
  "@schematics/angular:component": {
    "style": "scss"
  }
},
```

## 🔬 Minimal Reproduction

```
ng new my-app --style=scss --routing
ng g m admin --route admin --module app
```

Newly generated `AdminComponent` will have a `admin.component.css` instead of `scss`.

## 🌍 Your Environment
<pre><code>
Angular CLI: 8.1.0
Node: 10.15.1
OS: darwin x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.801.0
@angular-devkit/core         8.1.0
@angular-devkit/schematics   8.1.0
@schematics/angular          8.1.0
@schematics/update           0.801.0
rxjs                         6.4.0

</code></pre>

### PR DESCRIPTION
**Pull request by mgechev**
Fix #14986

This PR includes some refactoring to simplify the interaction of the `NodeWorkflow` and the `BaseWorkflow` with the registry.

We were registering redundant `addPostTransform`s. Some of them in the constructor of the `BaseWorkflow`, which did not allow us to intercept `addUndefinedDefaults`.

Additionally, we were setting the `validateOptionsWithSchema` transform multiple times unnecessarily.

An issue left to fix is support for the `--project` option in schematic commands. Currently, `getProjectName` does not know about this option, since `createWorkflow` does not know how to parse the command line arguments. The parsing logic is implemented partially by the concrete implementation of the `SchematicCommand` template method.

### CODE REVIEW

File: packages/angular/cli/models/schematic-command.ts [hunk 1]
```diff
@@ -17,10 +17,12 @@ import {
 } from '@angular-devkit/core';
 import { NodeJsSyncHost } from '@angular-devkit/core/node';
 import { DryRunEvent, UnsuccessfulWorkflowExecution, workflow } from '@angular-devkit/schematics';
+import { standardFormats } from '@angular-devkit/schematics/src/formats';
```
Comment (alan-agius4) [inline packages/angular/cli/models/schematic-command.ts]: Why the deep import?

File: packages/angular_devkit/schematics/BUILD [hunk 2]
```diff
@@ -13,13 +13,36 @@ load("@build_bazel_rules_nodejs//:defs.bzl", "npm_package")
 
 licenses(["notice"])  # MIT License
 
+# @angular-devkit/schematics/src/formats
```
Comment (alan-agius4) [inline packages/angular_devkit/schematics/BUILD]: Why is this needed? `standardFormats` is already available as part of the public API of `@angular-devkit/schematics` in the `formats` namespace

You can you it like;
```ts
import { formats } from '@angular-devkit/schematics';
formats.standardFormats
```

File: packages/angular_devkit/schematics_cli/bin/schematics.ts [hunk 3]
```diff
@@ -25,9 +24,11 @@ import {
   SchematicEngine,
   UnsuccessfulWorkflowExecution,
 } from '@angular-devkit/schematics';
-import { NodeModulesEngineHost, NodeWorkflow } from '@angular-devkit/schematics/tools';
+import { standardFormats } from '@angular-devkit/schematics/src/formats';
```
Comment (alan-agius4) [inline packages/angular_devkit/schematics_cli/bin/schematics.ts]: same

File: packages/angular/cli/models/schematic-command.ts (hunk 1 above)
Comment (mgechev) [reply packages/angular/cli/models/schematic-command.ts]: Ups, good catch. Didn't see it's already exported from `@angular-devkit/schematics`.

File: packages/angular_devkit/schematics_cli/bin/schematics.ts [hunk 4]
```diff
@@ -7,7 +7,6 @@
  * found in the LICENSE file at https://angular.io/license
  */
 
-import 'symbol-observable';
```
Comment (clydin) [inline packages/angular_devkit/schematics_cli/bin/schematics.ts]: This needs to stay at the top.

File: packages/angular_devkit/schematics/tools/workflow/node-workflow_spec.ts [hunk 5]
```diff
@@ -14,7 +15,7 @@ import * as path from 'path';
 describe('NodeWorkflow', () => {
   // TODO: this test seems to either not work on windows or on linux.
   xit('works', done => {
-    const workflow = new NodeWorkflow(new NodeJsSyncHost(), { dryRun: true });
+    const workflow = new NodeWorkflow(new NodeJsSyncHost(), { dryRun: true, registry: new schema.CoreSchemaRegistry() });
```
Comment (clydin) [inline packages/angular_devkit/schematics/tools/workflow/node-workflow_spec.ts]: This test is disabled and appears broken.  The base workflow appears to create a default registry if not provided as well so I'd probably leave this one as is.

File: packages/angular_devkit/schematics/tools/workflow/node-workflow.ts [hunk 6]
```diff
@@ -24,7 +23,8 @@ export class NodeWorkflow extends workflow.BaseWorkflow {
       force?: boolean;
       dryRun?: boolean;
       root?: Path,
-      packageManager?: string;
+      packageManager?: string,
```
Comment (clydin) [inline packages/angular_devkit/schematics/tools/workflow/node-workflow.ts]: These should use semicolons instead of commas since it is a type definition.

File: packages/angular_devkit/schematics/tools/workflow/node-workflow_spec.ts [hunk 7]
```diff
@@ -6,6 +6,7 @@
  * found in the LICENSE file at https://angular.io/license
  */
 // tslint:disable:no-implicit-dependencies
+import { schema } from '@angular-devkit/core';
```
Comment (clydin) [inline packages/angular_devkit/schematics/tools/workflow/node-workflow_spec.ts]: nit: unused import?
