### PR TITLE
fix(@angular/cli): pass arguments to all targets

### LINKED ISSUE #10657: ng lint with format flag errors
### Versions
```
Angular CLI: 6.0.0
Node: 9.11.1
OS: win32 x64
Angular: 6.0.0
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.0
@angular-devkit/schematics        0.6.0
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.0
@schematics/update                0.6.0
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0
```

### Repro steps
1. Create new application via angular-cli.
1. Run `ng lint` with format flag.
```bash
ng new my-test
cd my-test
ng lint --format checkstyle
```

I can edit _angular.json_ to add `"format":"checkstyle"` option to "my-test" and "my-test-e2e" projects. Then `ng lint` will run successfully and console will contain checkstyle output for each project.

### Observed behavior
```
Architect commands with multiple targets cannot specify overrides.'lint' would be run on the following projects: my-test,my-test-e2e
Error: Architect commands with multiple targets cannot specify overrides.'lint' would be run on the following projects: my-test,my-test-e2e
    at LintCommand.validate (C:\repos\my-test\node_modules\@angular\cli\models\architect-command.js:91:23)
    at C:\repos\my-test\node_modules\@angular\cli\models\command-runner.js:274:39
    at Generator.next (<anonymous>)
    at C:\repos\my-test\node_modules\@angular\cli\models\command-runner.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\repos\my-test\node_modules\@angular\cli\models\command-runner.js:3:12)
    at validateAndRunCommand (C:\repos\my-test\node_modules\@angular\cli\models\command-runner.js:273:12)
    at Object.<anonymous> (C:\repos\my-test\node_modules\@angular\cli\models\command-runner.js:100:26)
    at Generator.next (<anonymous>)
    at fulfilled (C:\repos\my-test\node_modules\@angular\cli\models\command-runner.js:4:58)
```

When using format option in _angular.json_, I get 2 checkstyle outputs (one for each project).
```
ng lint
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"></checkstyle>
<?xml version="1.0" encoding="utf-8"?><checkstyle version="4.3"></checkstyle>
```

### Desired behavior
* I would like to be able to pass in `format` param via command line so that it can be used via CI and local builds. 
* Default output is prose in console.
* Aggregate all linting errors preferred but can work around. (This was previous behavior).
   * Aggregate lint output for all projects so that I can pipe to file
   * For checkstyle it has all errors in one xml output instead of 2

### Mention any other details that might be useful (optional)
We use Jenkins CI and use checkstyle reporter to file for CI builds only, but would like to retain prose console output for local builds. We cannot do that when format is set in _angular.json_.

This is similar to #10422 but reporter was using multiple libraries. This issue is visible in a basic application.

### PR DESCRIPTION
**Pull request by mnahkies**
When running a command with args against multiple targets, all targets should be given the args. As parseArguments was mutating the passed args array this wasn't the case. 

Fix by making a shallow clone of the array. This was especially noticeable when using the `ng lint --fix` command on a newly generated project, as files in the app target would be fixed, but e2e target would be only be linted (with no fix).

Possibly closes #10657, #10656, #11005

### CODE REVIEW

**Comment by imcotton** [comment]
ping @clydin

**Comment by mnahkies** [comment]
@clydin this is a fair comment - I'll have a look at this tonight

File: packages/angular/cli/models/parser.ts [hunk 1]
```diff
@@ -259,6 +259,8 @@ export function parseFreeFormArguments(args: string[]): Arguments {
  * @returns An object that contains a property per option.
  */
 export function parseArguments(args: string[], options: Option[] | null): Arguments {
+  args = args.slice();
```
Comment (imcotton) [inline packages/angular/cli/models/parser.ts]:
```suggestion
export function parseArguments(originArgs: string[], options: Option[] | null): Arguments {
  const args = [ ...originArgs ];
```
Something like this?

Comment (imcotton) [reply packages/angular/cli/models/parser.ts]: I'm a little bit of confused, wouldn't the below tweaks guarantees the `args` been local from the beginning? (already renamed the param form `args` to `originArgs`)

```diff
- export function parseArguments(args: string[], options: Option[] | null): Arguments {
+ export function parseArguments(originArgs: string[], options: Option[] | null): Arguments {
+  const args = [ ...originArgs ];
```

Or you meant the local variable should being `ReadonlyArray` type?

Comment (clydin) [reply packages/angular/cli/models/parser.ts]: It would still be mutating and creating numerous copies that don't need to be created.  Don't mutate the input argument and there's no need to make copies at all.

**Comment by mnahkies** [comment]
@clydin and now I remember why I didn't do this in the first place, not quite the simple fix I had hoped! The file is well covered by unit tests though, so I'm pretty confident that the behaviour has not been changed (aside from stopping the mutation)

**Comment by mnahkies** [comment]
Hi @clydin any chance you could review this soon? Cheers

File: packages/angular/cli/models/parser.ts [hunk 2]
```diff
@@ -270,30 +284,73 @@ export function parseArguments(args: string[], options: Option[] | null): Argume
   const ignored: string[] = [];
   const errors: string[] = [];
 
-  for (let arg = args.shift(); arg !== undefined; arg = args.shift()) {
+  for (let i = 0; i < args.length; i++) {
```
Comment (clydin) [inline packages/angular/cli/models/parser.ts]: Instead of using 'i' which is already used below, use something similar to `argIndex`.   Eliminates the need to change the other loop to use `j`.

File: packages/angular/cli/models/parser.ts [hunk 3]
```diff
@@ -109,19 +109,29 @@ function _getOptionFromName(name: string, options: Option[]): Option | undefined
...
+function _assignOption({
+  arg,
+  nextArg,
+  options,
+  parsedOptions,
+  leftovers,
+  ignored,
+  errors,
+}: {
   arg: string,
```
Comment (clydin) [inline packages/angular/cli/models/parser.ts]: change the first argument from being the actual argument to the index of the argument.  You can then access the current argument and next argument by using the existing `args` array.

Also, have it return the new index.  This would eliminate the extra conditionals present in the calling function.

Comment (mnahkies) [reply packages/angular/cli/models/parser.ts]: I don't think this is possible, as the value for "arg" is computed rather than from the array for one of the function calls (I'll leave a comment pointing out the call in question)

File: packages/angular/cli/models/parser.ts [hunk 4]
```diff
@@ -270,30 +284,73 @@ export function parseArguments(args: string[], options: Option[] | null): Argume
...
+        const flag = arg[j];
         // If the next character is an '=', treat it as a long flag.
-        if (arg[i + 1] == '=') {
-          const f = '--' + flag + arg.slice(i + 1);
-          _assignOption(f, args, options, parsedOptions, positionals, leftovers, ignored, errors);
+        if (arg[j + 1] == '=') {
+          const f = '--' + flag + arg.slice(j + 1);
+
+          const consumedNextArg = _assignOption({
+            arg: f,
```
Comment (mnahkies) [inline packages/angular/cli/models/parser.ts]: For this usage of _assignOption we pass in a computed value rather than a value from the args array

**Comment by mnahkies** [comment]
Rebased on current master

**Comment by alan-agius4** [comment]
This would also fix https://github.com/angular/angular-cli/issues/13111
