### PR TITLE
fix(@angular-devkit/build-angular): disable output hashing when running dev-server

### LINKED ISSUE #10411: ng serve --prod Cannot use [chunkhash] or [contenthash]
### Versions
```
Angular CLI: 6.0.0-rc.5
Node: 8.9.1
OS: win32 x64
Angular: 6.0.0-rc.5
... animations, cli, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.5.7
@angular-devkit/build-angular     0.5.7
@angular-devkit/build-optimizer   0.5.7
@angular-devkit/core              0.5.7
@angular-devkit/schematics        0.5.7
@ngtools/json-schema              1.2.0
@ngtools/webpack                  6.0.0-rc.5
@schematics/angular               0.5.7
@schematics/update                0.5.7
rxjs                              6.0.0-uncanny-rc.7
typescript                        2.7.2
webpack                           4.5.0
```

### Repro steps

* Set "hmr": true under serve options
* ng serve --prod

### Observed behavior
```
****************************************************************************************

Date: 2018-04-20T11:18:32.210Z
Hash: 479da56e19191460642b
Time: 25039ms
chunk {0} admin-admin-module-ngfactory.2293166986b2fdeaaf9e.js (admin-admin-module-ngfactory) 811 bytes  [rendered]
chunk {1}  (runtime) [entry] [rendered]
chunk {2} styles.34c57ab7888ec1573f9c.css (styles) 0 bytes [initial] [rendered]
chunk {3} polyfills.fbe8aa029ddbd67561f0.js (polyfills) 59.4 kB [initial] [rendered]
chunk {4} main.272e4975a98129fc0e4c.js (main) 382 kB [initial] [rendered]

ERROR in chunk runtime [entry]
[name].[chunkhash:20].js
Cannot use [chunkhash] or [contenthash] for chunk in '[name].[chunkhash:20].js' (use [hash] instead)
```

### Desired behavior
No error

### PR DESCRIPTION
**Pull request by alan-agius4**
Using output hashing with the dev-server can cause memory leaks because the dev server does not know when to clean up the old files.

See: https://github.com/webpack/webpack-dev-server/issues/377#issuecomment-241258405

Closes #10411

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/dev-server/index.ts [hunk 1]
```diff
@@ -120,11 +120,15 @@ export function serveWebpackBrowser(
     // In dev server we should not have budgets because of extra libs such as socks-js
     overrides.budgets = undefined;
 
+    // Disable output hashing for dev build as this can cause memory leaks
+    // See: https://github.com/webpack/webpack-dev-server/issues/377#issuecomment-241258405
+    overrides.outputHashing = OutputHashing.None;
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/dev-server/index.ts:125]: Can a warning be added if this is disabled so that users know that it is happening?

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/dev-server/index.ts:125]: Yeah I was actually going to do, but didn’t because bundle budgets is being overridden without warning.

Although I think for this case it would be better to issue one.

**Review by clydin — APPROVED** [review]
