### PR TITLE
fix(@angular-devkit/build-angular): fixed ignoring of karma plugins config

### LINKED ISSUE #19993: Angular v11 ignores karma plugin config `karma-*` and throws error
# 🐞 Bug report

### Command (mark with an `x`)

- [x] new
- [ ] build
- [ ] serve
- [x] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 `karma-coverage` was made required in angular 11 and strict checking of `karma-coverage` was also introduced in v11. So, no it is not a regression

### Description

According to https://karma-runner.github.io/6.1/config/configuration-file.html 

> List of plugins to load. A plugin can be a string (in which case it will be required by Karma) or an inlined plugin - Object. By default, Karma loads all sibling NPM modules which have a name starting with karma-*.

I have added `karma-coverage`  in `package.json` and installed it 
and added `karma-*` to the plugins config in `karma.conf.js` 
Angular cli ignores the installed package as it seems `karma-*` config is ignored while validating `karma-coverage` is installed
It works when in plugins configuration one of these is added
`'karma-coverage'` or `require('karma-coverage')`

## 🔬 Minimal Reproduction
1. Add `karma-coverage` in `package.json` and install it (`npm install`)
```
"karma-coverage": "^2.0.3",
```
2. Add `'karma-*'` in `karma.conf.js` . Example:
```
plugins: [
      'karma-*',
      require('@angular-devkit/build-angular/plugins/karma'),
    ]
```
3. Run tests `ng test`

## 🔥 Exception or Error
<pre><code>

 ERROR [karma-server]: Server start failed on port 9876: Error: karma-coverage must be installed in order to run code coverage.

</code></pre>

## 🌍 Your Environment
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.1
Node: 12.16.1
OS: linux x64

Angular: 11.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router, upgrade
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            10.1.7
@angular-devkit/schematics      11.0.7
@angular/cdk                    9.2.4
@schematics/angular             11.0.7
@schematics/update              0.1101.1
ng-packagr                      10.1.2
rxjs                            6.6.3
typescript                      4.1.3

</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by iftee-hussain**
In angular 11 Previously `karma-coverage` was validated only when in karma plugins config one of these was added
``'karma-coverage'` or `require('karma-coverage')`

This change will allow cli to validate `karma-coverage` plugin if in `karma.conf.js` `'karma-*'` is used. Example:
```
plugins: [
      ...
      'karma-*',
      require('@angular-devkit/build-angular/plugins/karma'),
      ...
    ]
```

Fixes #19993

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts [hunk 1]
```diff
@@ -336,6 +339,13 @@ function fallbackMiddleware() {
 function isPlugin(moduleId: string, pluginName: string) {
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts:339]: Since we know the module name/plugin that we are looking for. We can optimize and simplify this a bit.

```ts
function isPlugin(moduleId: string, pluginName: string) {
  return (plugin: string|{}): boolean => {
    if (typeof plugin === 'string') {
      if (!plugin.includes('*')) {
        return plugin === moduleId;
      }

      const regexp = new RegExp(`^${plugin.replace('*', '.*')}`);
      if (regexp.test(moduleId)) {
        try {
          require.resolve(moduleId);

          return true;
        } catch {}
      }

      return false;
    }

    return pluginName in plugin;
  }
}

```

**Review by alan-agius4 — CHANGES_REQUESTED** [review]
Thanks for your contribution. 

See below.

File: packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts (hunk 1 above)
Comment (iftee-hussain) [reply packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts:336]: Thanks for the suggestion. Fixed in 7434f5d

Comment (iftee-hussain) [reply packages/angular_devkit/build_angular/src/webpack/plugins/karma/karma.ts:336]: Thanks for the suggestion. Fixed in 7434f5d

**Review by alan-agius4 — APPROVED** [review]
Thanks once again for your contribution. LGTM

**Comment by iftee-hussain** [comment]
> Thanks once again for your contribution. LGTM

Glad to contribute :smiley:
