### PR TITLE
fix(@schematics/angular): handle newline after `@` of a decorator

### LINKED ISSUE #14490: Cannot read property 'kind' of undefined for ng add @nguniversal/express-engine
# 🐞 Bug report

### Command (mark with an `x`)
```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [x] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

Exactly: `ng add @nguniversal/express-engine --clientProject my-theme`

### Is this a regression?

Not tested, but looks like this bug was always here.

### Description

If you have the following state of NgModule decorator:

```
@
NgModule
```
then it's ok for typescript, it's ok for `ng build`, but  `ng add @nguniversal/express-engine --clientProject my-theme` fails with `Cannot read property 'kind' of undefined` error.

## 🔬 Minimal Reproduction

Just specify NgModule at next line of @ and run `ng add @nguniversal/express-engine --clientProject XXX`.

## 🔥 Exception or Error
<pre><code>
An error occured:
Cannot read property 'kind' of undefined
TypeError: Cannot read property 'kind' of undefined
    at Object.findNode (E:\my-theme\node_modules\@schematics\angular\utility\ast-utils.js:125:14)
    at findBrowserModuleImport (E:\my-theme\node_modules\@schematics\angular\universal\index.js:63:43)
    at E:\my-theme\node_modules\@schematics\angular\universal\index.js:140:37
    at MergeMapSubscriber.input.pipe.operators_1.mergeMap.inputTree [as project] (E:\my-theme\node_modules\@angular-devkit\schematics\src\rules\call.js:74:24)
    at MergeMapSubscriber._tryNext (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:69:27)
    at MergeMapSubscriber._next (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:67:18)
    at MergeMapSubscriber.notifyNext (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:92:26)
    at InnerSubscriber._next (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:67:18)
    at E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at MergeMapSubscriber._innerSub (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:82:29)
    at MergeMapSubscriber._tryNext (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:76:14)
    at MergeMapSubscriber._next (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\operators\mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (E:\my-theme\node_modules\@angular-devkit\schematics\node_modules\rxjs\internal\Subscriber.js:67:18)
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.9
Node: 10.15.3
OS: win32 x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.13.9
@angular-devkit/build-optimizer   0.13.9
@angular-devkit/build-webpack     0.13.9
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@ngtools/webpack                  7.3.9
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.5.2
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**
https://github.com/angular/angular-cli/blob/ac23dc091312ce8f8452071a0dc6899b9ecb0f82/packages/schematics/angular/universal/index.ts#L84

### PR DESCRIPTION
**Pull request by alan-agius4**
Fixes #14490

### CODE REVIEW

File: packages/schematics/angular/utility/ast-utils.ts [hunk 1]
```diff
@@ -290,8 +290,8 @@ export function getDecoratorMetadata(source: ts.SourceFile, identifier: string,
       if (expr.expression.kind == ts.SyntaxKind.Identifier) {
         const id = expr.expression as ts.Identifier;
 
-        return id.getFullText(source) == identifier
-          && angularImports[id.getFullText(source)] === module;
+        return id.getText(source) == identifier
```
Comment (clydin) [inline packages/schematics/angular/utility/ast-utils.ts]: Nit: Should be able to use the text property here
