### PR TITLE
fix #5444

### LINKED ISSUE #5444: ng eject breaks routing
If I try routing before ejecting the webpack, it works as expected. As soon as you do ng eject, the application does compiles and runs, but router does not work. The first call is routed properly, but if you try to refresh or navigate to other route, the application returns CANNOT /GET route.

Any suggestions?

### PR DESCRIPTION
**Pull request by martzcodes**
Greetings from ng-conf!  I talked to two of the cli devs here but didn't catch there names.  We came across this similar issue in a workshop on Tuesday.

Added devServer to the common.ts file.  When `ng eject` runs it will include devServer

Fixes #5444

### CODE REVIEW

**Comment by entrocode** [comment]
I signed it!

**Comment by clydin** [comment]
As the CLI doesn't need or use this setting (in this form), this should probably be added to the ejected webpack configuration during the eject process.  Potentially with any other relevant dev server settings.

**Comment by entrocode** [comment]
@clydin Ok, I can shift that over

**Comment by clydin** [comment]
Here is where the dev server is currently configured: https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/serve.ts#L136

Not sure if anything else is relevant and/or useful.

**Comment by entrocode** [comment]
@clydin should it be added to here: https://github.com/angular/angular-cli/blob/master/packages/%40angular/cli/tasks/eject.ts#L320  ?

**Comment by entrocode** [comment]
@clydin updated... unless you wanted all of the values from serve get moved over (?)

**Comment by clydin** [comment]
If that fixes the issue in question, I'd leave it at that.

**Comment by sumitarora** [comment]
@entrocode Does issue occur with both `HashLocationStrategy` and `PathLocationStrategy` or just the one ?

**Comment by entrocode** [comment]
@sumitarora definitely `PathLocationStrategy`... I'll run a quick test for `HashLocationStrategy`

**Comment by entrocode** [comment]
@sumitarora It doesn't seem to impact `HashLocationStrategy`

**Comment by entrocode** [comment]
@clydin looks like the build failed because the commit message wasn't properly formatted... any guidance on that?

**Comment by clydin** [comment]
fix(@angular/cli): <short description of fix>

**Comment by sumitarora** [comment]
@entrocode Please squash commits in one only.

File: packages/@angular/cli/tasks/eject.ts [hunk 1]
```diff
@@ -320,6 +320,9 @@ class JsonWebpackSerializer {
   serialize(config: any): string {
     // config = Object.assign({}, config);
     config['plugins'] = this._pluginsReplacer(config['plugins']);
+    config['devServer'] = {
+      'historyApiFallback': true
+    }; // routes using PathLocationStrategy break without this
```
Comment (hansl) [inline packages/@angular/cli/tasks/eject.ts]: Move this comment over the config, start with a capital letter and add a period at the end. Otherwise LGTM

Comment (entrocode) [inline packages/@angular/cli/tasks/eject.ts]: Done. Thanks

**Comment by entrocode** [comment]
@clydin Looks like npm install failed?

**Comment by entrocode** [comment]
@hansl I'm not sure if I need to do anything to resolve the requested changes.  Let me know if there's something else on my end

**Comment by martzcodes** [comment]
not to confuse anyone, but I renamed my account from entrocode to martzcodes
