### PR TITLE
fix(@angular-devkit/build-angular): always use ECMA 5 optimizations with terser

### LINKED ISSUE #15580: @angular-devkit/build-angular:v0.803.4 build fails for differential loading with optimization=true
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 
`@angular-devkit/build-angular:v0.803.3`

### Description

 A clear and concise description of the problem...

Build fails with the latest `@angular-devkit/build-angular:v0.803.4` if `optimization` is enabled i.e.
`ng build --optimization=true`

## 🔬 Minimal Reproduction

I tried to create a new app to reproduce it without success yet and I am afraid I cannot share the repo either.
But I did some digging and it seems related to fix 7a75c4cd215f06986b31afd85018ba918533a38d and differential loading. If I set my `browserlist` to `last 1 Chrome versions` the build is OK. 

## 🔥 Exception or Error
<pre><code>

[error] SyntaxError: /home/panos/ui/dist/vendor-es2015.js: Unexpected reserved word 'arguments' (1:2704314)

[0m[31m[1m>[22m[39m[90m 1 | [39m(window[33m.[39mwebpackJsonp[33m=[39mwindow[33m.[39mwebpackJsonp[33m||[39m[])[33m.[39mpush([[[35m21[39m][33m,[39m{[32m"/Co4"[39m[33m:[39m[36mfunction[39m(module[33m,[39m__webpack_exports__[33m,[39m__webpack_require__){[32m"use strict"[39m[33m;[39m__webpack_require__[33m.[39md(__webpack_exports__[33m,[39m[32m"a"[39m[33m,[39m[36mfunction[39m(){[36mreturn[39m [33mMatAutocomplete[39m})[33m,[39m__webpack_require__[33m.[39md(__webpack_exports__[33m,[39m[32m"b"[39m[33m,[39m[36mfunction[39m(){[36mreturn[39m [33mMatAutocompleteModule[39m})[33m,[39m__webpack_require__[33m.[39md(__webpack_exports__[33m,[39m[32m"c"[39m[33m,[39m[36mfunction[39m(){[36mreturn[39m [33mMatAutocompleteTrigger[39m})[33m;[39m[36mvar[39m _angular_cdk_a11y__WEBPACK_IMPORTED_MODULE_0__[33m=[39m__webpack_require__([32m"5GAg"[39m)[33m,[39m_angular_cdk_coercion__WEBPACK_IMPORTED_MODULE_1__[33m=[39m__webpack_require__([32m"KCVW"[39m)[33m,[39m_angular_core__WEBPACK_IMPORTED_MODULE_2__[33m=[39m__webpack_require__([32m"8Y7J"[39m)[33m,[39m_angular_material_core__WEBPACK_IMPORTED_MODULE_3__[33m=[39m__webpack_require__([32m"Xd0L"[39m)[33m,[39m_angular_cdk_bidi__WEBPACK_IMPORTED_MODULE_4__[33m=[39m__webpack_require__([32m"IP0z"[39m)[33m,[39m_angular_cdk_keycodes__WEBPACK_IMPORTED_MODULE_5__[33m=[39m__webpack_require__([32m"dvZr"[39m)[33m,[39m_angular_cdk_overlay__WEBPACK_IMPORTED_MODULE_6__[33m=[39m__webpack_require__([32m"QQfA"[39m)[33m,[39m_angular_cdk_platform__WEBPACK_IMPORTED_MODULE_7__[33m=[39m__webpack_require__([32m"/HVE"[39m)[33m,[39m_angular_cdk_portal__WEBPACK_IMPORTED_MODULE_8__[33m=[39m__webpack_require__([32m"zMNK"[39m)[33m,[39m_angular_cdk_scrolling__WEBPACK_IMPORTED_MODULE_9__[33m=[39m__webpack_require__([32m"hOhj"[39m)[33m,[39m_angular_common__WEBPACK_IMPORTED_MODULE_10__[33m=[39m__webpack_require__([32m"SVse"[39m)[33m,[39m_angular_forms__WEBPACK_IMPORTED_MODULE_11__[33m=[39m__webpack_require__([32m"s7LF"[39m)[33m,[39m_angular_material_form_field__WEBPACK_IMPORTED_MODULE_12__[33m=[39m__webpack_require__([32m"HsOI"[39m)[33m,
</code></pre>

## 🌍 Your Environment
<pre><code>

Angular CLI: 8.3.4
Node: 12.10.0
OS: linux x64
Angular: 8.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.4
@angular-devkit/build-angular     0.803.4
@angular-devkit/build-optimizer   0.803.4
@angular-devkit/build-webpack     0.803.4
@angular-devkit/core              8.3.4
@angular-devkit/schematics        8.3.4
@angular/cdk                      8.2.0
@angular/cli                      8.3.4
@angular/flex-layout              8.0.0-beta.27
@angular/material                 8.2.0
@ngtools/webpack                  8.3.4
@schematics/angular               8.3.4
@schematics/update                0.803.4
rxjs                              6.5.3
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by clydin**
There appears to be defects related to terser's ECMA 6 options.  The optimizations present a minimal size improvement in general and was the default for differential loading prior to #15566.  Further investigation is required to determine the underlying cause within terser.

Fixes #15580

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts [hunk 1]
```diff
@@ -332,11 +332,14 @@ export function getCommonConfig(wco: WebpackConfigOptions): Configuration {
       }
     }
 
+    // TODO: Investigate why this fails for some packages: wco.supportES2015 ? 6 : 5;
+    const terserEcma = 5;
+
     const terserOptions = {
       warnings: !!buildOptions.verbose,
       safari10: true,
       output: {
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts]: Shouldn't this be `  const terserOptions = { ecma:	
        wco.supportES2015 &&	
        (!differentialLoadingNeeded || (differentialLoadingNeeded && fullDifferential))	
          ? 6	
          : 5}` to actually restory the previous behaviour?

Comment (clydin) [reply packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/common.ts]: Somethings going wrong when its set to 6;  it was just rarely used before outside of differential loading.  The CLI also doesn't have direct control of the terser version in this situation (its transitive via `terser-webpack-plugin`) so I think its overall safer to avoid the setting completely for now.

**Comment by filipesilva** [comment]
Is there a repro we can provide to the Terser team so they can address this?
