### PR TITLE
fix(@angular-devkit/build-angular): support differential loading for web workers

### LINKED ISSUE #16275: Adding web worker via "ng generate webWorker" does not generate differential builds
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

Unsure, I've only just encountered a scenario that would reveal this bug.

### Description
Differential builds are not generated for web workers, only es2015.

2019-11-24 11_58_26-NgWorkerEs5Test

## 🔬 Minimal Reproduction

- Step 1
`ng new NgWorkerDiffTest --routing=false --style=scss & cd NgWorkerDiffTest & ng generate webWorker MyWorker`
- Step 2
Modify `app.component.ts` to include:
<pre>
<code>
    if (typeof Worker !== "undefined") {
      const worker = new Worker("./my-worker.worker", { type: "module" });
    }
</code>
</pre>
- Step 3
`ng build` or `ng build --prod` - neither will produce anything but es2015 for the worker.

## 🌍 Your Environment
<pre><code>

Angular CLI: 9.0.0-rc.3
Node: 12.12.0
OS: win32 x64
Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.900.0-rc.3
@angular-devkit/core         9.0.0-rc.3
@angular-devkit/schematics   9.0.0-rc.3
@schematics/angular          9.0.0-rc.3
@schematics/update           0.900.0-rc.3
rxjs                         6.5.3
</code></pre>

**Anything else relevant?**

In a way - IE11 will fail to load workers due to syntax errors.

### PR DESCRIPTION
**Pull request by clydin**
Fixes #16275

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/browser/index.ts [hunk 1]
```diff
@@ -334,7 +334,8 @@ export function buildWebpackBrowser(
               const seen = new Set<string>();
               for (const file of emittedFiles) {
                 // Assets are not processed nor injected into the index
-                if (file.asset) {
+                // WorkerPlugin adds worker files to assets
+                if (file.asset && !file.file.endsWith('.worker.js')) {
```
Comment (alan-agius4) [inline packages/angular_devkit/build_angular/src/browser/index.ts]: I am not following how this will fix this issue.

How is the reference the file change? When doing `new WebWorker`

File: tests/legacy-cli/e2e/tests/build/worker.ts [hunk 2]
```diff
@@ -23,6 +23,14 @@ export default async function () {
...
 
+  await ng('build');
+  await expectFileToExist('dist/test-project/0-es5.worker.js');
+  await expectFileToExist('dist/test-project/0-es2015.worker.js');
+
+  await ng('build', '--prod', '--output-hashing=none');
+  await expectFileToExist('dist/test-project/0-es5.worker.js');
+  await expectFileToExist('dist/test-project/0-es2015.worker.js');
+
   // console.warn has to be used because chrome only captures warnings and errors by default
```
Comment (alan-agius4) [inline tests/legacy-cli/e2e/tests/build/worker.ts]: Should add a test that the reference to the web worker file is correct.

Example in the es2015 the es2015 worker is referenced and so on for the es5 version

File: packages/angular_devkit/build_angular/src/browser/index.ts (hunk 1 above)
Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/browser/index.ts]: Or that’s part of the runtime js substitutions which we already handle?

Comment (clydin) [reply packages/angular_devkit/build_angular/src/browser/index.ts]: That makes it downlevel the file. Webpack doesn’t know that it exists outside of it being an asset.

Comment (clydin) [reply packages/angular_devkit/build_angular/src/browser/index.ts]: Implemented the second half of this that will update the file references.
