### PR TITLE
fix(@angular-devkit/build-angular): localized bundle generation fails in watch mode

### LINKED ISSUE #22395: Localized bundle generation fails if `--watch` flag is used
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

Yes

### Description

Build with `--watch` option fails with error like: `✖ Localized bundle generation failed: ENOENT: no such file or directory, open '/tmp/angular-cli-i18n-oPSjKQ/polyfills.js'`. Error message changes from time to time (it complains about different directories in /tmp and two files: polyfills.js and main.js).
Full command is: `npm run build -- --configuration development --watch`

Project builds without `--watch` option without errors. Full command is: `npm run build -- --configuration development`

It used to work correctly on "^12.2.3" version of angular packages, and it broke since I've updated to "^13.1.0".

### Please provide a link to a minimal reproduction of the bug

https://github.com/human33/angular-i18n-min-reproduction

### Please provide the exception or error you saw

```true
✖ Localized bundle generation failed: ENOENT: no such file or directory, open '/tmp/angular-cli-i18n-oPSjKQ/polyfills.js'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.2
Node: 12.22.5
Package Manager: npm 7.5.2
OS: linux x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@schematics/angular             13.1.2
rxjs                            7.4.0
typescript                      4.5.4
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by alan-agius4**
Previously, we used to delete the temporary emitted JS and map files. However this causes a problem in watch mode, as Webpack will not re-emit these deleted files during the next incremental re-build.

With this change we now delete the entire temporary directory when the process is being terminated instead of a file by file bases.

Closes #22395

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/builders/browser/index.ts [hunk 1]
```diff
@@ -73,6 +73,12 @@ export type BrowserBuilderOutput = json.JsonObject &
     outputPath: string;
   };
 
+/**
+ * Maximum time for single build/rebuild
+ * This accounts for CI variability.
+ */
+export const BUILD_TIMEOUT = 40000;
```
Comment (dgp1130) [inline packages/angular_devkit/build_angular/src/builders/browser/index.ts:80]: Nit: Add a unit to this variable so future readers know what it represents (I assume milliseconds?). Can add that as a var name suffix or part of the comment.

May also want to consider adding an `_` for readability. I originally read it as `4_000` but it's actually `40_000`.

File: packages/angular_devkit/build_angular/src/utils/i18n-options.ts [hunk 2]
```diff
@@ -249,10 +249,35 @@ export async function configureI18nBuild<T extends BrowserBuilderSchema | Server
     buildOptions.outputPath = tempPath;
 
     // Remove temporary directory used for i18n processing
-    process.on('exit', () => {
+    const deleteTempDirectory = () => {
```
Comment (dgp1130) [inline packages/angular_devkit/build_angular/src/utils/i18n-options.ts:252]: Nit: Can this be moved to the top-level scope (accept `tempPath` as a parameter)? Does it need to be in this closure?

**Review by dgp1130 — APPROVED** [review]
