### PR TITLE
fix(@schematics/angular): add new route before wildcard route

### LINKED ISSUE #15255: Angular CLI adds the route to the wrong line while generating a module
# 🐞 Bug report

### Command (mark with an `x`)

```
- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Is this a regression?
No

### Description
If routes have a route with `{path: ** ...}` in `app-routing.module`. Angular CLI adds the route to the wrong line while generating a module.

## 🔬 Minimal Reproduction
Create a new application
```bash
ng new issue-test-app --routing --style=css

cs issue-test-app
```

Add a new route in app-routing.module
```ts
const routes: Routes = [
  { path: '**', redirectTo: '/' },
];
```

Generate a module via CLI
```bash
ng generate module dashboard --route dashboard --module app.module
```

CLI added the route to the wrong line.

Edited routes:
```ts
const routes: Routes = [
  { path: '**', redirectTo: '/' },
  { path: 'dashboard', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule) },
];
```
Now, I can't access `localhost:4200/dashboard`. Angular always redirect me to `/` path.

Routes must be like below
```ts
const routes: Routes = [
  { path: 'dashboard', loadChildren: () => import('./dashboard/dashboard.module').then(m => m.DashboardModule) },
  { path: '**', redirectTo: '/' },
];
```

## 🌍 My Environment
<pre><code>
Angular CLI: 8.2.0
Node: 10.16.0
OS: darwin x64
Angular: undefined
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.802.0
@angular-devkit/core         8.2.0
@angular-devkit/schematics   8.2.0
@angular/cli                 8.2.0
@schematics/angular          8.2.0
@schematics/update           0.802.0
rxjs                         6.4.0
</code></pre>

### PR DESCRIPTION
**Pull request by timdeschryver**
Adds a new route before the wildcard route to prevent that we always redirect to the wildcard route.

For example, starting point:

```
const routes = [
  { path: '**', component: AppComponent }
];
```

Before:

```ts
const routes = [
  { path: '**', component: AppComponent },
  { path: 'foo', component: FooComponent }
];
```

After:

```ts
const routes = [
  { path: 'foo', component: FooComponent },
  { path: '**', component: AppComponent }
];
```

Closes #15255

### CODE REVIEW

**Comment by alan-agius4** [comment]
@timdeschryver, the change itself looks good, however can you kindly remove the style changes and leave them for another PR.

Thanks

File: packages/schematics/angular/utility/ast-utils.ts [hunk 1]
```diff
@@ -642,27 +688,45 @@ export function addRouteDeclarationToModule(
...
   const text = routesArr.getFullText(source);
 
   let route: string = routeLiteral;
-  if (occurencesCount > 0) {
-    const identation = text.match(/\r?\n(\r?)\s*/) || [];
-    route = `,${identation[0] || ' '}${routeLiteral}`;
+  let insertPos = routesArr.elements.pos;
+
+  if (occurrencesCount > 0) {
+    const routeLiterals = findNodes(routesArr, ts.SyntaxKind.ObjectLiteralExpression);
```
Comment (alan-agius4) [inline packages/schematics/angular/utility/ast-utils.ts]: This whole part to determine if it's a wilecard route can be simplified a bit, and make it more safe and performant by removing the `getText` which is slower than using `.text` directly.

Something like the below should be enough.

```ts
    const lastRouteLiteral = [...routesArr.elements].pop();
    const lastRouteIsWildcard = ts.isObjectLiteralExpression(lastRouteLiteral) && lastRouteLiteral
      .properties
      .some(n => (
        ts.isPropertyAssignment(n)
        && ts.isIdentifier(n.name)
        && n.name.text === 'path'
        && ts.isStringLiteral(n.initializer)
        && n.initializer.text === '**'
      ));
```

Comment (timdeschryver) [reply packages/schematics/angular/utility/ast-utils.ts]: Thanks for the review, it does look better.

**Comment by timdeschryver** [comment]
@alan-agius4 done, thanks again for the guidance 👍

**Comment by alan-agius4** [comment]
@, you are welcome.

Thanks again for your contribution to Angular CLI.

**Comment by dgp1130** [comment]
Merged to patch branch 9.0.x: https://github.com/angular/angular-cli/commits/9.0.x
