### PR TITLE
fix: remove ember references in console output

### LINKED ISSUE #4025: Migrate ember references in error messages.
### OS?
Mac OS X El Capitan

### Versions.
angular-cli: 1.0.0-beta.25.5
node: 7.3.0
os: darwin x64
@angular/common: 2.4.3
@angular/compiler: 2.4.3
@angular/core: 2.4.3
@angular/forms: 2.4.3
@angular/http: 2.4.3
@angular/platform-browser: 2.4.3
@angular/platform-browser-dynamic: 2.4.3
@angular/router: 3.4.3
@angular/compiler-cli: 2.4.3

### Repro steps.
run `ng generate` on the command line.

### The log given by the failure.
`The ember generate command requires a blueprint name to be specified. For more details, use ember help.`

### Mention any other details that might be useful.
I'm pretty sure that this is just a by-product of angular-cli being based on ember-cli. The error messages should be migrated at some point though for clarity. I looked for an open bug that was tracking this but couldn't find one.

### PR DESCRIPTION
**Pull request by clydin**
Closes #4025

### CODE REVIEW

File: packages/angular-cli/ember-cli/lib/utilities/windows-admin.js [hunk 1]
```diff
@@ -21,8 +21,7 @@ module.exports = {
 
           if (!elevated && ui && ui.writeLine) {
             ui.writeLine(chalk.yellow('\nRunning without elevated rights. ' +
```
Comment (hansl) [inline packages/angular-cli/ember-cli/lib/utilities/windows-admin.js]: Actually I _think_ this is false now, since we don't use Broccoli. But I don't have a windows computer to test this. Could you try running it in non-admin, and admin, and say run a `ng build`/`ng version`/`ng test` and see if that makes a difference? If so then we should keep it, otherwise just remove the warning. It's noise :)

**Comment by hansl** [comment]
LGTM, thanks!

**Comment by hansl** [comment]
CLA is good.
