### PR TITLE
fix(@angular/cli): infer schematic defaults correctly when using `--project`

### LINKED ISSUE #20666: Generate minimal component in app, with defaultProject lib
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [x] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

When I generate a component, with `--minimal` ( inlineTemplate, inlineStyle, skipTests => true, style: scss), it is generated with test, template and css. 

 
## 🔬 Minimal Reproduction

I created a NG app with `ng new bug-ng-cli --create-application false --strict false`. 
I run `ng add @angular-eslint/schematics`
I run `ng g application demo --minimal --minimal --routing --style scss`
I run `ng g @angular-eslint/schematics:convert-tslint-to-eslint --remove-tslint-if-no-more-tslint-targets --ignore-existing-tslint-config demo`
I run `ng g library foo`

If i run:

```bash
▶ ng g c components/authComponent --project=demo -d
CREATE projects/demo/src/app/components/auth-component/auth-component.component.ts (288 bytes)
UPDATE projects/demo/src/app/app.module.ts (516 bytes)
```

It is Ok.

But, If **I change my defaultProject from demo to foo (library)**

```bash
▶ ng g c components/authComponent --project=demo -d
CREATE projects/demo/src/app/components/auth-component/auth-component.component.css (0 bytes)
CREATE projects/demo/src/app/components/auth-component/auth-component.component.html (29 bytes)
CREATE projects/demo/src/app/components/auth-component/auth-component.component.spec.ts (676 bytes)
CREATE projects/demo/src/app/components/auth-component/auth-component.component.ts (306 bytes)
UPDATE projects/demo/src/app/app.module.ts (516 bytes)
```

The repository example is: https://github.com/krbaio3/bug-ng-cli.git

Thanks!

### PR DESCRIPTION
**Pull request by alan-agius4**
Previously, the `--project` flag was ignored when gathering and merging the schematics defaults from the angular workspace configuration file.
    
Closes #20666

### CODE REVIEW

**Review by clydin — APPROVED** [review]

File: packages/angular/cli/models/schematic-command.ts [hunk 1]
```diff
@@ -242,14 +242,17 @@ export abstract class SchematicCommand<
...
-          )),
-          ...current,
-        }),
+        async (schematic, current) => {
+          const projectName =
+            typeof (current as Record<string, unknown>).project === 'string'
+              ? ((current as Record<string, unknown>).project as string)
+              : getProjectName();
+
+          return {
```
Comment (alan-agius4) [inline packages/angular/cli/models/schematic-command.ts:251]: We cannot validate the project name at this stage, since the project might now exist yet, example when using `ng g lib` or `ng g app`, when under the will invoke `ng g c` will an unknown project name.

**Comment by alan-agius4** [comment]
@clydin PTAL

**Review by clydin — APPROVED** [review]
