### PR TITLE
fix(@angular-devkit/build-angular): respect `preserveSymlinks` when using `bundleDependencies` in server builder

### LINKED ISSUE #13817: Build of server side bundle is combining to the bundle packages which are linked.
# 🐞 Bug report

### Command
```
- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [x] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```
### Description
Build of server side bundle is combining to the bundle packages which are linked (`npm link xyz`). Same package, if is just installed (`npm i xyz`) is just referenced by `require`. This cause a problems with few workflows like auto server side restart by `nodemon`, debugging, ect. It is confusing that build is  handling same package in two different ways. Build should handle in same way packages which are under `node_modules`, no matter haw that modules are installed.

## 🔬 Minimal Reproduction
1. `ng init abc`
2. `cd abc`
3. `npm i uuid @types/uuid` (this is just example of some 3Party package,  but it can be any other)
4. create file `src/main-server.ts`:
```
import {v4} from 'uuid';
console.log(v4());
```
5. create file `src/tsconfig.server.json`:
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": { "outDir": "../out-tsc/server", "module": "commonjs" }
}
```
6. in `angular.json` under the  `projects/abc/architect` add:
```
...
"server": {
  "builder": "@angular-devkit/build-angular:server",
  "options": {
    "bundleDependencies": "none", <-- this doesn't help :(
    "preserveSymlinks": true,
    "outputPath": "dist/server",
    "main": "src/main-server.ts",
    "tsConfig": "src/tsconfig.server.json",
    "fileReplacements": [
      {
        "replace": "src/environments/environment.ts",
        "with": "src/environments/environment.prod.ts"
      }
    ]
  }
}
...
```
7. call `ng run abc:server`, generated bundle is 4.55 kB and contains just reference to `uuid` package:
```
/***/ "uuid":
/*!***********************!*\
  !*** external "uuid" ***!
  \***********************/
/*! no static exports found */
/***/ (function(module, exports) { module.exports = require("uuid");/***/ })
/******/ })));
```
8. now clone the package `git clone https://github.com/kelektiv/node-uuid.git -- node-uuid`
9. link cloned package by `npm link` instde cloned repo
10. under the abc project link uuid package by `npm link uuid`
11. build bundle again by `ng run abc:server`, now bundle size is 11.2 kB and it contains content of linked package 

## 🌍 Your Environment
<pre><code>
Angular CLI: 7.3.4
Node: 10.15.1
OS: win32 x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.4
@angular-devkit/build-angular     0.13.4
@angular-devkit/build-optimizer   0.13.4
@angular-devkit/build-webpack     0.13.4
@angular-devkit/core              7.3.4
@angular-devkit/schematics        7.3.4
@angular/cli                      7.3.4
@ngtools/webpack                  7.3.4
@schematics/angular               7.3.4
@schematics/update                0.13.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

### PR DESCRIPTION
**Pull request by alan-agius4**
- fix(@angular-devkit/build-angular): don't bundle linked modules when `bundleDependencies` in `none` in  server builder

Fixes #13817

### CODE REVIEW

File: packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts [hunk 1]
```diff
@@ -43,18 +35,23 @@ export function getServerConfig(wco: WebpackConfigOptions) {
...
         // Absolute & Relative paths are not externals
         if (request.match(/^\.{0,2}\//)) {
           return callback();
         }
 
         try {
           // Attempt to resolve the module via Node
-          const e = require.resolve(request);
+          // we cannot use require.resolve, because it has preserveSymlinks logic
+          const e = resolve(request, {
```
Comment (clydin) [inline packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts]: We can actually use `require.resolve` here.  If execution got here and the request can be resolved then it should always be an external.  The conditionals below this that test for node_modules can be removed.  All builtins are also externals for the node target.

Comment (alan-agius4) [reply packages/angular_devkit/build_angular/src/angular-cli-files/models/webpack-configs/server.ts]: updated
