### PR TITLE
fix(@angular/cli): change the url for doc search

### LINKED ISSUE #16840: Wrong request for ng doc -s
When i run ng doc component it works well but when i try to use -s for all searches option it gives wrong value 

image

### PR DESCRIPTION
**Pull request by santoshyadav198613**
Fixes #16840

### CODE REVIEW

**Comment by dgp1130** [comment]
Merged to patch branch 9.0.x as well.

File: packages/angular/cli/commands/doc-impl.ts [hunk 1]
```diff
@@ -41,13 +41,13 @@ export class DocCommand extends Command<DocCommandSchema> {
...
         domain = `v${currentNgVersion}.angular.io`;
-      } catch (e) {}
+      } catch (e) { }
     }
 
     let searchUrl = `https://${domain}/api?query=${options.keyword}`;
 
     if (options.search) {
-      searchUrl = `https://www.google.com/search?q=site%3A${domain}+${options.keyword}`;
+      searchUrl = `https://${domain}/?search=${options.keyword}`;
```
Comment (gkalpak) [inline packages/angular/cli/commands/doc-impl.ts]: I just realized that for archive version (i.e. older than the current stable), non-docs pages (including the home page) are redirected to `/docs` (losing the query params). So, this URL should be `https://${domain}/docs?search=${options.keyword}` 😅
(My bad for suggesting the wrong URL 😇)

I submitted #16856.
